import os
import glob
import numpy as np
from PIL import Image, ImageFilter

ASSETS = "/opt/lara/public/assets/modeller"

def process_model(img_path):
    print(f"Processing {img_path}...")
    img = Image.open(img_path).convert("RGBA")
    arr = np.array(img)
    
    # Belly sample
    belly_region = arr[580:610, 500:524]
    solid = belly_region[belly_region[..., 3] > 200]
    if len(solid) > 0:
        avg_skin = solid.mean(axis=0).astype(np.float32)
    else:
        avg_skin = np.array([210, 160, 130, 255], dtype=np.float32)
        
    skin_color = avg_skin[:3].astype(np.uint8)
    
    # Create a copy to modify
    out_arr = arr.copy()
    
    # Paint bra (Y=440 to 550)
    for y in range(430, 550):
        for x in range(1024):
            alpha = arr[y, x, 3]
            if alpha > 20:
                # To preserve some shading but remove the bra color, 
                # we just do a flat paint but keep the alpha edge smooth
                out_arr[y, x, :3] = skin_color
                
    # Paint panties (Y=650 to 780)
    for y in range(650, 780):
        for x in range(1024):
            alpha = arr[y, x, 3]
            if alpha > 20:
                out_arr[y, x, :3] = skin_color
                
    # Convert back to image
    flat_img = Image.fromarray(out_arr)
    
    # We want to blur the painted regions slightly so it blends with the real skin
    mask = Image.new("L", (1024, 1365), 0)
    from PIL import ImageDraw
    draw = ImageDraw.Draw(mask)
    # create soft transition area
    draw.rectangle([0, 420, 1024, 560], fill=255)
    draw.rectangle([0, 640, 1024, 790], fill=255)
    
    mask_blur = mask.filter(ImageFilter.GaussianBlur(radius=10))
    
    blurred_flat = flat_img.filter(ImageFilter.GaussianBlur(radius=3))
    
    # Composite the original image with the blurred flat painted image using the mask
    final_img = Image.composite(blurred_flat, img, mask_blur)
    
    # Restore the exact original alpha channel so silhouette is perfect
    final_arr = np.array(final_img)
    final_arr[..., 3] = arr[..., 3]
    
    final_img = Image.fromarray(final_arr)
    final_img.save(img_path, "PNG")
    print(f"  Done: {os.path.basename(img_path)}")

def main():
    models = glob.glob(os.path.join(ASSETS, "m_*.png"))
    for m in models:
        # Avoid processing dolgun base models if they are generated by dolgun_uret.py 
        # Eski dolgun_uret.py artık kullanılmıyor; beden varyantları beden_uret.py ile üretilir.
        process_model(m)

if __name__ == "__main__":
    main()
