import {test,expect,type Page} from '@playwright/test';
async function lesson(page:Page,id:string){await page.goto(`/#lesson/${id}`);await expect(page.locator('.lesson-card')).toBeVisible();while(await page.getByRole('button',{name:'Devam',exact:true}).count())await page.getByRole('button',{name:'Devam',exact:true}).click();await page.getByRole('button',{name:'Birlikte yapalım',exact:true}).click()}
const sounds=(page:Page)=>page.evaluate(()=>(window as unknown as {sounds:number}).sounds);
test.beforeEach(async({page})=>{await page.addInitScript(()=>{const w=window as unknown as {sounds:number;AudioContext:typeof AudioContext};w.sounds=0;const Real=w.AudioContext;w.AudioContext=class extends Real{createOscillator(){w.sounds++;return super.createOscillator()}createBufferSource(){w.sounds++;return super.createBufferSource()}}})});
test('seçenek dokununca hemen kontrol edilir; yanlış seçenek kapanır, doğru olan yeşil kalır, ikisi de ses verir',async({page})=>{await lesson(page,'life-traffic');await expect(page.getByRole('button',{name:'Kontrol et'})).toHaveCount(0);const wrong=page.locator('.options button',{hasText:'Geç'}),right=page.locator('.options button',{hasText:'Bekle'});await wrong.click();await expect(page.locator('.feedback')).toHaveClass(/retry/);await expect(wrong).toHaveClass(/is-wrong/);await expect(wrong).toHaveAttribute('aria-disabled','true');const afterWrong=await sounds(page),hint=await page.locator('.feedback').innerText();expect(afterWrong).toBeGreaterThan(0);await wrong.click({force:true});await page.waitForTimeout(300);expect(await sounds(page)).toBe(afterWrong);await expect(page.locator('.feedback')).toHaveText(hint,{useInnerText:true});await right.click();await expect(page.getByText('Evet, buldun!')).toBeVisible();await expect(right).toHaveClass(/is-correct/);await expect(page.getByRole('button',{name:'Devam edelim'})).toBeFocused();expect(await sounds(page)).toBeGreaterThan(afterWrong);const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('lara-progress-v1')!));expect(saved.attempts).toHaveLength(1);expect(saved.attempts[0].correct).toBe(false)});
test('telefonda seçimden sonra geri bildirim ve devam düğmesi alt menünün üstünde görünür',async({page})=>{await page.setViewportSize({width:390,height:844});await lesson(page,'life-traffic');await page.locator('.options button',{hasText:'Bekle'}).evaluate(b=>(b as HTMLButtonElement).click());const next=page.getByRole('button',{name:'Devam edelim'});await expect(next).toBeFocused();await expect.poll(async()=>{const b=(await next.boundingBox())!,nav=(await page.locator('.mobile-nav').boundingBox())!;return b.y+b.height<=nav.y&&b.y>=0}).toBe(true);await expect(page.locator('.feedback.correct')).toBeInViewport()});
test('ses varsayılan açıktır; kapatılınca cevaplar sessiz kalır',async({page})=>{await page.goto('/');await page.getByRole('button',{name:'Sesi kapat'}).click();await expect(page.getByRole('button',{name:'Sesi aç'})).toBeVisible();await lesson(page,'english-0');await page.locator('.options button',{hasText:/^hello$/}).click();await expect(page.getByText('Evet, buldun!')).toBeVisible();expect(await sounds(page)).toBe(0)});
test('ritim dört vuruş tamamlanınca kendiliğinden kontrol edilir',async({page})=>{await lesson(page,'music-rhythm');await expect(page.getByRole('button',{name:'Kontrol et'})).toHaveCount(0);const beat=(x:string)=>page.getByRole('button',{name:x==='👏'?'👏 Vuruş':'— Sus'});for(const x of ['—','—','👏','—'])await beat(x).click();await expect(page.locator('.feedback')).toHaveClass(/retry/);await expect(page.locator('.input-beats')).toHaveClass(/is-wrong/);await page.getByRole('button',{name:'Yeniden dene'}).click();for(const x of ['👏','👏','—','👏'])await beat(x).click();await expect(page.getByText('Evet, buldun!')).toBeVisible();await expect(page.locator('.input-beats')).toHaveClass(/is-correct/)});
test('düzeltilebilen yapımlarda Kontrol et kalır; aynı yanlış cevap iki kez sayılmaz',async({page})=>{await lesson(page,'math-blocks');const check=page.getByRole('button',{name:'Kontrol et',exact:true});await expect(check).toBeDisabled();await page.getByRole('button',{name:'Bir birlik ekle',exact:true}).click();expect(await sounds(page)).toBeGreaterThan(0);await check.click();await expect(page.locator('.feedback')).toHaveClass(/retry/);await expect(check).toBeDisabled();await page.getByRole('button',{name:'Bir birlik ekle',exact:true}).click();await expect(check).toBeEnabled()});
