import {test,expect,type Page,type Locator} from '@playwright/test';
import {previewQuestion} from '../../lib/questions';
import {lessons} from '../../content';
async function lesson(page:Page,id:string){await page.goto(`/#lesson/${id}`);await expect(page.locator('.lesson-card')).toBeVisible();while(await page.getByRole('button',{name:'Devam',exact:true}).count())await page.getByRole('button',{name:'Devam',exact:true}).click();await page.getByRole('button',{name:'Birlikte yapalım',exact:true}).click()}
async function drag(page:Page,a:Locator,b:Locator,end=.5){await b.scrollIntoViewIfNeeded();const from=(await a.boundingBox())!,to=(await b.boundingBox())!;await page.mouse.move(from.x+from.width/2,from.y+from.height/2);await page.mouse.down();await page.mouse.move(to.x+to.width*end,to.y+to.height/2,{steps:12});await page.mouse.up()}
test('öğren ekranında seçim geri bildirim verir, saat serbestçe denenir',async({page})=>{const preview=previewQuestion(lessons.find(l=>l.id==='math-solids')!)!;await page.goto('/#lesson/math-solids');await page.locator('.options button').filter({hasText:new RegExp(`^${preview.options!.find(o=>o!==preview.answer)}$`)}).click();await expect(page.locator('.discovery-feedback')).toContainText('Bir daha inceleyelim');await page.locator('.options button').filter({hasText:new RegExp(`^${preview.answer}$`)}).click();await expect(page.locator('.discovery-feedback')).toContainText('Evet!');await page.goto('/#lesson/math-clock');await expect(page.locator('.interactive-clock')).toBeVisible();await expect(page.getByRole('button',{name:'Bu saati seç'})).toHaveCount(0);await page.getByLabel('Saat',{exact:true}).selectOption('7');await expect(page.getByLabel('Kurduğun saat')).toHaveText('07.00')});
for(const width of [390,768,1280])test(`şekil büyüklüğü ${width}px ekranda gerçekten değişir`,async({page})=>{await page.setViewportSize({width,height:1024});await lesson(page,'math-rotate');const slider=page.getByRole('slider',{name:'Büyüklük'});await slider.fill('50');await expect.poll(async()=>Math.round((await page.locator('.shape-turntable').boundingBox())!.width)).toBe(120);const small=(await page.locator('.shape-turntable').boundingBox())!.width;await slider.fill('90');await expect.poll(async()=>(await page.locator('.shape-turntable').boundingBox())!.width).toBeGreaterThan(small*1.5)});
test('kart sürükledikten sonra bir sonraki dokunuş kaybolmaz',async({page})=>{await page.setViewportSize({width:768,height:1024});await lesson(page,'tr-words-0');await drag(page,page.locator('.word-bank').getByRole('button',{name:'Lara',exact:true}),page.locator('.empty-word-slot').first());await page.locator('.word-bank').getByRole('button',{name:'şemsiyesini',exact:true}).click();await expect(page.locator('.sentence-reading p')).toHaveText('Lara şemsiyesini')});
test('yan yana iki kart sağa ve sola sürüklenerek yer değiştirebilir',async({page})=>{await page.setViewportSize({width:1280,height:900});await lesson(page,'tr-words-0');for(const word of ['Lara','şemsiyesini','arkadaşıyla','paylaştı.'])await page.locator('.word-bank').getByRole('button',{name:word,exact:true}).click();await drag(page,page.getByRole('button',{name:'2. kart: şemsiyesini'}),page.getByRole('button',{name:'3. kart: arkadaşıyla'}),.8);await expect(page.locator('.sentence-reading p')).toHaveText('Lara arkadaşıyla şemsiyesini paylaştı.');await drag(page,page.getByRole('button',{name:'3. kart: şemsiyesini'}),page.getByRole('button',{name:'2. kart: arkadaşıyla'}),.2);await expect(page.locator('.sentence-reading p')).toHaveText('Lara şemsiyesini arkadaşıyla paylaştı.')});
test('birlikler telefonda beşli iki sıra ve büyük dokunma alanları oluşturur',async({page})=>{await page.setViewportSize({width:360,height:800});await lesson(page,'math-blocks');for(let i=0;i<10;i++)await page.getByRole('button',{name:'Bir birlik ekle',exact:true}).click();await expect.poll(()=>page.getByRole('button',{name:'Bir birlik çıkar',exact:true}).evaluateAll(els=>new Set(els.map(e=>Math.round(e.getBoundingClientRect().top))).size)).toBe(2);const boxes=await page.getByRole('button',{name:'Bir birlik çıkar',exact:true}).evaluateAll(els=>els.map(e=>{const r=e.getBoundingClientRect();return {width:r.width,height:r.height,top:r.top}}));expect(new Set(boxes.map(b=>Math.round(b.top))).size).toBe(2);expect(boxes.every(b=>b.width>=44&&b.height>=44)).toBe(true)});
test('öz bildirim görevleri sonuç ekranında başarısız beceri gibi sunulmaz',async({page})=>{await lesson(page,'move-jump');for(let i=0;i<8;i++){await page.getByRole('button',{name:i<3?'Yaptım':'Anlattım',exact:false}).click();await page.getByRole('button',{name:i===7?'Keşfimi tamamla':'Devam edelim',exact:true}).click()}await expect(page.locator('.result')).toContainText('bu görevlerde otomatik not verilmez');await expect(page.locator('.skill-feedback')).toContainText('Keşfini tamamladın');await expect(page.locator('.skill-feedback')).not.toContainText('pratik yapabiliriz');const progress=await page.evaluate(()=>JSON.parse(localStorage.getItem('lara-progress-v1')!));expect(progress.stars).toBe(0)});
