import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {emptyProgress,completeLesson,exportProgress} from '../../lib/progress';
test('ana sayfa → matematik → etkinlik → sonuç → kalıcı ilerleme',async({page})=>{
 await page.goto('/');await page.getByRole('link',{name:'Keşfe başla'}).click();
 await page.getByRole('button',{name:'Devam',exact:true}).click();await page.getByRole('button',{name:'Birlikte yapalım',exact:true}).click();
 for(let i=0;i<8;i++){
   const instruction=await page.locator('.question-instruction').innerText();
   const n=Number(instruction.match(/\d+/)?.[0]);
   if(i%3===2){await expect(page.getByRole('button',{name:'Kontrol et',exact:true})).toHaveCount(0);await page.locator('.options button').filter({hasText:new RegExp(`^.[ ]*${Math.floor(n/10)}$`)}).click();}
   else {for(let t=0;t<Math.floor(n/10);t++)await page.getByRole('button',{name:'Bir onluk ekle',exact:true}).click();for(let u=0;u<n%10;u++)await page.getByRole('button',{name:'Bir birlik ekle',exact:true}).click();await page.getByRole('button',{name:'Kontrol et',exact:true}).click();}
   await expect(page.getByText('Evet, buldun!')).toBeVisible();await page.getByRole('button',{name:i===7?'Keşfimi tamamla':'Devam edelim',exact:true}).click();
 }
 await expect(page.getByRole('heading',{name:'Emeğine sağlık, Lara!'})).toBeVisible();await page.getByRole('link',{name:'Öğrenme dünyama dön'}).click();await page.reload();await expect(page.locator('.growth-card')).toContainText('1 konu tamamladın');
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('lara-progress-v1')!));expect(saved.completed['math-blocks']).toBeTruthy();expect(saved.attempts).toHaveLength(8);
});
for(const [w,h] of [[360,800],[390,844],[768,1024],[1024,768],[1280,720],[1920,1080]])test(`${w}×${h} ekranı ve erişilebilirlik`,async({page})=>{
 await page.setViewportSize({width:w,height:h});await page.goto('/');await expect(page.getByRole('heading',{name:'Merhaba, ben Lara'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`artifacts/home-${w}.png`,fullPage:true});
 const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(result.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))).toEqual([]);
 await page.goto('/#lesson/math-blocks');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('PWA çevrim dışıyken yeni bir ders açar',async({page,context})=>{await page.goto('/');await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);await context.setOffline(true);await page.reload();await expect(page.getByRole('heading',{name:'Merhaba, ben Lara'})).toBeVisible();await page.goto('/#lesson/tr-words-0');await expect(page.getByRole('heading',{name:'Kelimelerden köprü'})).toBeVisible();await context.setOffline(false)});
test('ebeveyn PIN, yedek export ve hatalı import',async({page})=>{await page.goto('/#parents');await page.getByLabel('Yeni PIN',{exact:true}).fill('4826');await page.getByLabel('PIN’i tekrar girin').fill('4826');await page.getByRole('button',{name:'PIN oluştur ve aç'}).click();await page.getByRole('button',{name:'Yedek ve gizlilik',exact:true}).click();const download=page.waitForEvent('download');await page.getByRole('button',{name:'İlerlemeyi Yedekle'}).click();expect((await download).suggestedFilename()).toMatch(/lara-ilerleme/);await page.locator('input[type=file]').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":99}')});await expect(page.locator('.backup-panel [role=alert]')).toContainText('geçerli');await page.getByRole('button',{name:'Kilitle',exact:true}).click();await expect(page.getByLabel('Ebeveyn PIN’i')).toBeVisible()});
test('tüm ders rotaları boş ekran vermeden açılır',async({page})=>{test.setTimeout(240000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/#subjects');await expect(page.getByRole('heading',{name:'Derslerim'})).toBeVisible();const expected=(await page.locator('.card-bottom>span:first-child').allInnerTexts()).reduce((sum,t)=>sum+parseInt(t),0);let visited=0;for(const id of ['math','tr','life','english','art','music','move']){await page.goto(`/#subject/${id}`);await expect(page.locator('.lesson-tile').first()).toBeVisible();const links=await page.locator('.lesson-tile').evaluateAll(els=>els.map(el=>(el as HTMLAnchorElement).hash));visited+=links.length;for(const link of links){await page.goto(`/${link}`);await expect(page.locator('.lesson-card')).toBeVisible();const count=await page.getByRole('button',{name:'Devam',exact:true}).count();if(count){while(await page.getByRole('button',{name:'Devam',exact:true}).count())await page.getByRole('button',{name:'Devam',exact:true}).click()}await page.getByRole('button',{name:'Birlikte yapalım',exact:true}).click();await expect(page.locator('.question-instruction')).toBeVisible();}}expect(expected).toBeGreaterThan(80);expect(visited).toBe(expected);expect(errors).toEqual([])});
test('geçerli yedek onaydan sonra yüklenir ve yeniden açılınca korunur',async({page})=>{await page.goto('/#parents');await page.getByLabel('Yeni PIN',{exact:true}).fill('4826');await page.getByLabel('PIN’i tekrar girin').fill('4826');await page.getByRole('button',{name:'PIN oluştur ve aç'}).click();await page.getByRole('button',{name:'Yedek ve gizlilik',exact:true}).click();const restored=completeLesson(emptyProgress(),'math-clock',4,5);await page.locator('input[type=file]').setInputFiles({name:'lara.json',mimeType:'application/json',buffer:Buffer.from(exportProgress(restored))});await expect(page.locator('.restore-preview')).toContainText('1 tamamlanan konu');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('lara-progress-v1')??'{}').completed?.['math-clock'])).toBeUndefined();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Önce yedekle, sonra geri yükle'}).click();await download;await page.goto('/#home');await page.reload();await expect(page.locator('.growth-card')).toContainText('1 konu tamamladın');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('lara-progress-v1')!).completed['math-clock'].correct)).toBe(4)});
