import {describe,it,expect} from 'vitest';
import {makeQuestion} from '../lib/questions';
import {routeCells} from '../lib/manipulatives';
import {lessons} from '../content';
const lesson=(id:string)=>lessons.find(l=>l.id===id)!;
describe('soru içeriği ve görsel tutarlılığı',()=>{
 it('yön haritasındaki yol, sıralanacak adımlarla aynıdır',()=>{const letters:Record<string,string>={Sağa:'R',Sola:'L',Yukarı:'U',Aşağı:'D'};for(let i=0;i<8;i++){const q=makeQuestion(lesson('math-directions'),i,1,i*7);expect(q.visual).toMatch(/^route:/);const cells=routeCells(q.visual!);expect(cells.every(([x,y])=>x>=0&&x<5&&y>=0&&y<4)).toBe(true);expect(new Set(cells.map(c=>c.join())).size).toBe(cells.length);const steps=q.answer.split('|');expect(new Set(q.items).size).toBe(steps.length);expect(q.items!.join('|')).not.toBe(q.answer);expect(q.items!.some(item=>/^\d/.test(item))).toBe(false);expect(steps.map(s=>{const [dir,n]=s.split(' ');return letters[dir]+n}).join(',')).toBe(q.visual!.split(':')[2])}});
 it('örüntü sorusu verilen sayılardaki kuralı bulmayı ister',()=>{for(let seed=0;seed<120;seed++)for(let i=0;i<8;i++){const q=makeQuestion(lesson('math-pattern'),i,1,seed);expect(q.type).toBe('choice');const parts=q.instruction.split('?')[0].match(/__|\d+/g)!.map(x=>x==='__'?Number(q.answer):Number(x)),step=parts[1]-parts[0];expect(Math.abs(step)).toBeGreaterThanOrEqual(2);for(let j=1;j<parts.length;j++)expect(parts[j]-parts[j-1]).toBe(step);if(q.instruction.includes('Sıradaki'))expect(Number(q.answer)).toBe(parts[3]+step);expect(Math.max(...parts,Number(q.answer))).toBeLessThanOrEqual(Math.abs(step)*10)}});
 it('tempo sorusunda hızlı örnek vuruş aralığı kısa olandır; seçenek sırası sabittir',()=>{for(let i=0;i<8;i++){const q=makeQuestion(lesson('music-tempo'),i,1,3);expect(q.type).toBe('tempo');expect(q.options).toEqual(['1. örnek','2. örnek']);const intervals=[q.value!,q.start!],pick=Number(q.answer[0])-1,fast=intervals.indexOf(Math.min(...intervals));expect(pick).toBe(q.instruction.includes('hızlı')?fast:1-fast)}for(let i=0;i<4;i++)expect(makeQuestion(lesson('music-pitch'),i,1,i).options).toEqual(['1. ses','2. ses'])});
 it('tabak ve grup görselleri cevapla tutarlıdır; bölmede cevap önceden gösterilmez',()=>{for(let seed=0;seed<60;seed++){const m=makeQuestion(lesson('math-multiply'),0,3,seed),[g,e]=m.visual!.split(':')[2].split('x').map(Number);expect(m.visual).toMatch(/^groups:/);expect(Number(m.answer)).toBe(g*e);expect(m.explanation).not.toContain('÷');const d=makeQuestion(lesson('math-divide'),0,3,seed),[,, total,plates]=d.visual!.split(':');expect(d.visual).toMatch(/^share:/);expect(Number(d.answer)).toBe(Number(total)/Number(plates));const c=makeQuestion(lesson('math-estimate'),0,1,seed);expect(c.visual).toBe(`count:🍒:${c.answer}`)}});
 it('Hayat Bilgisi durumları soru cümlesiyle biter',()=>{for(const l of lessons.filter(l=>l.subject==='life'))for(const q of l.questions!)expect(q.instruction.trim(),q.id).toMatch(/\?$/)});
});
