import {describe,it,expect} from 'vitest';
import {checkAnswer,completeLesson,difficulty,emptyProgress,exportProgress,parseBackup,recordAttempt,dueSkills} from '../lib/progress';
import {makeQuestion} from '../lib/questions';
import {lessons} from '../content';
import curriculum from '../curriculum/grade-2.json';
describe('öğrenme motoru',()=>{
 it('cevabı açık ve doğru değerlendirir',()=>{expect(checkAnswer('24','24')).toBe(true);expect(checkAnswer('23','24')).toBe(false);expect(checkAnswer('a|b','b|a')).toBe(false)});
 it('bağımsız başarı zorluğu artırır, yardım ve öz bildirim ustalık sayılmaz',()=>{let p=emptyProgress();for(let i=0;i<8;i++)p=recordAttempt(p,{id:`a${i}`,lessonId:'math-blocks',skill:'MAT.2.1.2',correct:true,assisted:false,selfReport:false,at:'2026-09-24T09:00:00Z'});expect(p.skills['MAT.2.1.2'].score).toBe(96);expect(difficulty(p.skills['MAT.2.1.2'])).toBe(3);const old=p;p=recordAttempt(p,{id:'art',lessonId:'art-colors',skill:'GS.2.5.1',correct:true,assisted:false,selfReport:true,at:'2026-09-24T09:00:00Z'});expect(p.skills['GS.2.5.1'].score).toBe(0);expect(p.stars).toBe(old.stars)});
 it('yanlış cevap tekrar planlar, yinelenen kayıt ödül oluşturmaz',()=>{const a={id:'q1',lessonId:'math-blocks',skill:'MAT.2.1.2',correct:false,assisted:false,selfReport:false,at:'2026-09-24T09:00:00Z'};const p=recordAttempt(emptyProgress(),a);expect(recordAttempt(p,a)).toEqual(p);expect(dueSkills(p,Date.parse('2026-09-26'))).toEqual(['MAT.2.1.2']);expect(difficulty(p.skills['MAT.2.1.2'])).toBe(1)});
 it('tamamlama ve yedek geri yükleme korunur',()=>{const p=completeLesson(emptyProgress(),'math-blocks',3,5);expect(parseBackup(exportProgress(p))).toEqual(p);expect(p.skills).toEqual({})});
 it('bozuk ve zararlı yedeği reddeder',()=>{for(const raw of ['{}','null','{"version":9}',JSON.stringify({...emptyProgress(),stars:-4}),JSON.stringify({...emptyProgress(),skills:JSON.parse('{"__proto__":{}}')})])expect(()=>parseBackup(raw)).toThrow()});
 it('tüm dersler gerçek kodlara ve üretilen sorulara bağlıdır',()=>{const codes=new Set(curriculum.map(x=>x.learningOutcomeCode));for(const l of lessons){for(const code of l.outcomes)expect(codes.has(code),`${l.id} → ${code}`).toBe(true);for(const d of [1,2,3] as const)for(let i=0;i<8;i++){const q=makeQuestion(l,i,d,42);expect(q.instruction.length,l.id).toBeGreaterThan(5);expect(q.answer.length,l.id).toBeGreaterThan(0);expect(codes.has(q.skill),`${l.id} ${q.skill}`).toBe(true);if(q.options){expect(new Set(q.options).size).toBe(q.options.length);expect(q.options).toContain(q.answer)}if(q.type==='ordering'){expect([...q.items!].sort()).toEqual(q.answer.split('|').sort())}}}});
 it('matematik sınırları ve dinamik sorular',()=>{for(const k of ['blocks','count','add','subtract','multiply','divide']){const l=lessons.find(l=>l.id===`math-${k}`)!;const answers=new Set();for(let seed=0;seed<70;seed++){const q=makeQuestion(l,0,3,seed);expect(Number(q.answer)).toBeGreaterThanOrEqual(0);expect(Number(q.answer)).toBeLessThanOrEqual(100);answers.add(q.answer)}expect(answers.size).toBeGreaterThan(3)}});
 it('matematiğin 25, Türkçenin 20 çıktısı kayıtlıdır',()=>{expect(curriculum.filter(c=>c.subject==='math')).toHaveLength(25);expect(curriculum.filter(c=>c.subject==='tr')).toHaveLength(20);for(const c of curriculum){expect(new URL(c.sourceUrl).hostname).toBe('tymm.meb.gov.tr');expect(c.grade).toBe(2);expect(c.academicYear).toBe('2026-2027')}});
});
