import {describe,it,expect} from 'vitest';
import {balloonRounds,codeLevels,codeSize,memoryDeck,memoryDecks,runProgram,spellHint,spellRounds,spellWords} from '../lib/games';
import {emptyProgress,exportProgress,parseBackup,recordGame} from '../lib/progress';
import {englishLessons} from '../content/english/lessons';
describe('oyun köşesi',()=>{
 it('hafıza destelerinde her eş tam iki kez bulunur',()=>{const words=new Set(englishLessons.flatMap(l=>l.vocabulary!.map(v=>v.word)));for(const {id} of memoryDecks)for(let seed=0;seed<60;seed++){const cards=memoryDeck(id,seed),pairs=new Map<string,number>();for(const c of cards)pairs.set(c.pair,(pairs.get(c.pair)??0)+1);expect(cards).toHaveLength(12);expect(pairs.size).toBe(6);expect([...pairs.values()].every(n=>n===2)).toBe(true);expect(new Set(cards.map(c=>c.id)).size).toBe(12);
  for(const [pair] of pairs){const faces=cards.filter(c=>c.pair===pair).map(c=>c.face);if(id==='english')expect(words.has(pair)).toBe(true);if(id==='place')expect(faces).toContain(`${Math.floor(Number(pair)/10)} onluk ${Number(pair)%10} birlik`);if(id==='add'){const sum=faces.find(f=>f.includes('+'))!.split(' + ').map(Number);expect(sum[0]+sum[1]).toBe(Number(pair))}}}});
 it('balon turlarında doğru cevap tek ve seçenekler arasında',()=>{for(let seed=0;seed<200;seed++)for(const r of balloonRounds(seed)){expect(r.options).toHaveLength(4);expect(new Set(r.options).size).toBe(4);expect(r.options).toContain(r.answer);expect(r.options.every(n=>Number.isInteger(n)&&n>=0&&n<=100)).toBe(true);
  const n=r.prompt.match(/\d+/g)?.map(Number)??[];if(r.kind==='add')expect(r.answer).toBe(n[0]+n[1]);if(r.kind==='subtract')expect(r.answer).toBe(n[0]-n[1]);if(r.kind==='place')expect(r.answer).toBe(n[0]*10+n[1]);if(r.kind==='skip')expect(r.answer-n[2]).toBe(n[1]-n[0]);if(r.kind==='compare')expect(r.answer).toBe(Math.max(...r.options))}});
 it('her kod bölümü çözülebilir; kenar ve taş engeli fark edilir',()=>{for(const level of codeLevels){expect(runProgram(level,level.solution).result).toBe('goal');expect([level.start,level.goal,...level.rocks].every(([x,y])=>x>=0&&y>=0&&x<codeSize&&y<codeSize)).toBe(true)}expect(runProgram(codeLevels[0],['left']).result).toBe('edge');expect(runProgram(codeLevels[2],['right','right']).result).toBe('rock');expect(runProgram(codeLevels[0],['right']).result).toBe('short');expect(runProgram(codeLevels[0],['right','right','right','down']).path.at(-1)).toEqual(codeLevels[0].goal)});
 it('harf treni kelimenin harflerini karışık verir ve ipucu doğru harfi ekler',()=>{for(let seed=0;seed<100;seed++){const rounds=spellRounds(seed);expect(rounds).toHaveLength(6);for(const r of rounds){expect(r.letters.map(l=>l.ch).sort()).toEqual([...r.word].sort());expect(r.letters.map(l=>l.ch).join('')).not.toBe(r.word);let built:number[]=[];for(let i=0;i<r.letters.length;i++)built=spellHint(r,built);expect(built.map(id=>r.letters.find(l=>l.id===id)!.ch).join('')).toBe(r.word)}}expect(new Set(spellWords.map(w=>w[0])).size).toBe(spellWords.length)});
 it('oyun sonucu müfredat puanına karışmaz ve yedekte korunur',()=>{let p=recordGame(emptyProgress(),'memory',18,'low','2026-09-25T10:00:00Z');p=recordGame(p,'memory',14,'low','2026-09-25T10:05:00Z');p=recordGame(p,'memory',20,'low','2026-09-25T10:10:00Z');p=recordGame(p,'code',3,'high','2026-09-25T10:15:00Z');expect(p.games).toEqual({memory:{plays:3,best:14,last:'2026-09-25T10:10:00Z'},code:{plays:1,best:3,last:'2026-09-25T10:15:00Z'}});expect(p.stars).toBe(0);expect(p.skills).toEqual({});expect(parseBackup(exportProgress(p))).toEqual(p);expect(()=>parseBackup(JSON.stringify({...p,games:{memory:{plays:-1,best:1,last:'2026-09-25'}}}))).toThrow();expect(()=>parseBackup(JSON.stringify({...p,games:[]}))).toThrow();expect(parseBackup(exportProgress(emptyProgress())).games).toBeUndefined()});
});
