import type {Lesson} from '@/lib/types';
export const creativeLessons:Lesson[]=[
 {id:'art-look',subject:'art',theme:'Hayat ve Sanat',title:'Renk avcısı',subtitle:'Çevrende tekrar eden renkleri bul.',icon:'🔎',minutes:7,outcomes:['GS.2.1.1','GS.2.1.2'],kind:'drawing',learn:['Bir ağacın yapraklarında yeşil tekrar eder. Bir çiçeğin yapraklarında aynı biçim görülebilir.','Çevrenden iki renk seç. Bu renkleri kendi hayalindeki bahçede kullan.'],task:'Aynı rengi en az üç yerde kullanarak bir bahçe çiz. Hangi rengi tekrarladığını söyle.'},
 {id:'art-pattern',subject:'art',theme:'Sanatın Görsel Dili',title:'Motiflerin dansı',subtitle:'Kendi desenini tasarla.',icon:'🧶',minutes:7,outcomes:['GS.2.2.2'],kind:'drawing',learn:['Halıda veya kilimde tekrar eden küçük şekillere motif denir.','Aynı şekli yan yana kullanıp bir desen oluşturabiliriz.'],task:'Üçgen ve karelerle tekrar eden bir desen çiz. Deseninin kuralını anlat.'},
 {id:'art-still',subject:'art',theme:'Sanatçılar ve Eserleri',title:'Meyvelerin portresi',subtitle:'Duran nesneleri resimle anlat.',icon:'🍐',minutes:8,outcomes:['GS.2.3.2'],kind:'drawing',learn:['Natürmort, meyve ve vazo gibi durgun nesneleri konu alan resimdir.','Yuvarlak bir elmanın yanına uzun bir şişe düşün. Biçimler birbirinden farklıdır.'],task:'Bir elma, bir armut ve bir bardaktan oluşan resim yap. Yuvarlak ve uzun biçimleri birlikte kullan.'},
 {id:'art-lines',subject:'art',theme:'Çizim ve Görsel İfade',title:'Çizgilerle doğa',subtitle:'Düz, dalgalı, kıvrımlı…',icon:'🌊',minutes:7,outcomes:['GS.2.4.1'],kind:'drawing',learn:['Düz bir çizgi yol olabilir. Dalgalı çizgi denizi hatırlatabilir.','Farklı çizgilerle bir manzaranın parçalarını anlatabilirsin.'],task:'Bir tepe, bir nehir ve ağaçlar çiz. En az iki farklı çizgi türü kullan.'},
 {id:'art-museum',subject:'art',theme:'Müze ve Kültür',title:'Minik oyuncak müzem',subtitle:'Oyuncakların da bir hikâyesi var.',icon:'🧸',minutes:8,outcomes:['GS.2.7.1','GS.2.7.2'],kind:'drawing',learn:['Müzelerde nesneler özenle korunur ve tanıtılır.','Oyuncaklar yapıldıkları malzemeye veya oynanışlarına göre gruplanabilir.'],task:'Bir oyuncak müzesi planı çiz. Yumuşak oyuncaklar ve tahta oyuncaklar için iki köşe ayır. Sonra bir yetişkinle üç oyuncağını gruplamayı dene.'},
 {id:'art-colors',subject:'art',theme:'Renk ve Estetik',title:'Renkler buluşuyor',subtitle:'İki renk, yepyeni bir keşif.',icon:'🎨',minutes:8,outcomes:['GS.2.5.1'],kind:'drawing',generator:'colors',learn:['Boyada kırmızı, sarı ve mavi ana renklerdir.','Kırmızı ile sarı turuncu; sarı ile mavi yeşil; kırmızı ile mavi mor oluşturur.','Renklerini karıştır. Sonra bir şehir manzarası çiz.'],task:'Evler, yollar ve ağaçlarla kendi kentini çiz. Ana ve ara renkler kullan.'},
 {id:'art-nature',subject:'art',theme:'Millî Değerler ve Sanat',title:'Sevdiğim manzara',subtitle:'Doğanın renklerini kâğıda taşı.',icon:'🏞️',minutes:8,outcomes:['GS.2.6.1'],kind:'drawing',learn:['Yaşadığın yerde sevdiğin bir ağacı, dağı ya da bahçeyi düşün.','Bir resim, bir yere duyduğun sevgiyi anlatabilir.'],task:'Sevdiğin bir doğal manzara çiz. Onu korumak için yapabileceğin bir şeyi anlat.'},
 {id:'move-jump',subject:'move',theme:'Hareketimi Geliştiriyorum',title:'Minik tavşan molası',subtitle:'Ayağa kalk, biraz hareket edelim.',icon:'🐇',minutes:3,outcomes:['BEO.2.1.1'],kind:'physicalTask',learn:['Önce çevrende boş ve güvenli bir alan bul.','Dizlerini hafifçe bükerek yumuşakça zıpla. İstersen oturarak kollarını kaldırıp indirebilirsin.'],task:'Rahat hissediyorsan 5 küçük zıplama yap. İstersen 5 kez kollarını kaldır. Yorulursan dinlen.'},
 {id:'move-balance',subject:'move',theme:'Hareketimi Geliştiriyorum',title:'Flamingonun dengesi',subtitle:'Kendi hızında dengeyi keşfet.',icon:'🦩',minutes:3,outcomes:['BEO.2.1.1'],kind:'physicalTask',learn:['Dengede dururken bir noktaya bakabilirsin.','Yakınında destek alabileceğin sağlam bir yüzey olsun.'],task:'Bir ayağını hafifçe kaldır. Rahat olduğun kadar dengede kal. Sonra diğer ayağınla dene. Oturarak bir ayağını kaldırmayı da seçebilirsin.'},
 {id:'move-rhythm',subject:'move',theme:'Ritimle Hareket Ediyorum',title:'Adım, alkış, gülümse',subtitle:'Hareketine bir ritim kat.',icon:'👏',minutes:3,outcomes:['BEO.2.3.1'],kind:'physicalTask',learn:['Ritim, seslerin ve sessizliklerin düzenidir.','Yavaş bir ritimle başlayıp kendi rahat hızını bul.'],task:'İki adım at, bir kez alkışla. Bu diziyi üç kez tekrarla. Oturarak iki kez dizine, bir kez ellerine vurabilirsin.'},
 {id:'music-rhythm',subject:'music',theme:'Müzik Dili',title:'Piko’nun ritmini yakala',subtitle:'Dinle, dokun, ritmi tamamla.',icon:'🥁',minutes:5,outcomes:['MÜZ.2.1.6'],kind:'rhythm',generator:'rhythm',learn:['Bir vuruş ses çıkarır. Bir sus işaretinde sessiz kalırız.','Önce örneği dinle. Sonra vuruş ve sus kartlarıyla aynı diziyi kur. Son olarak ellerinle ritme eşlik et.'],task:'Dört adımlı ritmi dinle ve yeniden oluştur.'},
 {id:'music-tempo',subject:'music',theme:'Müzik Dili',title:'Kaplumbağa ve tavşan',subtitle:'Aynı ritim, farklı hızlar.',icon:'🐢',minutes:5,outcomes:['MÜZ.2.1.6'],kind:'tempo',generator:'tempo',learn:['Tempo müziğin hızıdır. Yavaş ve hızlı olabilir.','Aynı ritmi farklı hızlarda dinle. Vuruş sayısı değişmeden hız değişebilir. Ellerini veya ayaklarını ritme uydur.'],task:'Yavaş ve hızlı örnekleri dinle, hangisinin daha hızlı olduğunu karşılaştır.'},
 {id:'music-pitch',subject:'music',theme:'Müzik Dili',title:'İnce mi, kalın mı?',subtitle:'Ses merdiveninde keşif.',icon:'🎶',minutes:5,outcomes:['MÜZ.2.1.2'],kind:'pitch',generator:'pitch',learn:['Bir kuşun sesi ince, büyük bir davulun sesi kalın olabilir.','İncelik ve kalınlık, sesin güçlü ya da hafif olmasıyla aynı şey değildir. İki sesi karşılaştır.']},
 {id:'music-song',subject:'music',theme:'Müzik Kültürü',title:'Filiz şarkısı',subtitle:'Söyle, hareket et, paylaş.',icon:'🌱',minutes:6,outcomes:['MÜZ.2.2.3','MÜZ.2.2.6'],kind:'speaking',task:'Özgün Filiz Şarkısı’nı kendi ezginle söyle: “Bir tohum ektim, güneşe baktım. Bir damla suyla, filizi büyüttüm.” Sonra büyüyen filizi kollarınla canlandır.',learn:['Şarkı söylerken bedenini rahat tut, nefesini zorlamadan söyle.','Bizim şarkımız: Bir tohum ektim, güneşe baktım. Bir damla suyla, filizi büyüttüm.','Sözcüklere kendi ezgini katabilir, filizin büyümesini kollarınla gösterebilirsin.']},
 {id:'move-rules',subject:'move',theme:'Oyunun Kurallarını Uyguluyorum',title:'Heykel oyunu',subtitle:'Başla, dur, arkadaşını dinle.',icon:'🗿',minutes:4,outcomes:['BEO.2.2.1','BEO.2.2.2'],kind:'physicalTask',task:'Bir yetişkin veya arkadaşınla oyna. “Başla” deyince yerinde yürü; “Dur” deyince heykel ol. Sonra sözcükleri söyleme sırasını değiştirin.',learn:['Oyunun başında herkes kuralı öğrenir.','Heykel oyununda “Başla” hareket, “Dur” beklemek demektir. Kimseyi itmeden kendi alanında hareket et.']},
 {id:'move-health',subject:'move',theme:'Sağlığım İçin Fiziksel Aktiviteye Katılıyorum',title:'Bedenimi dinliyorum',subtitle:'Hareket öncesi ve sonrası.',icon:'💚',minutes:4,outcomes:['BEO.2.4.1','BEO.2.4.3','BEO.2.4.5'],kind:'physicalTask',task:'Önce alanını kontrol et. Rahatça 10 kez yerinde adım at. Sonra durup nefesini fark et. Neler değişti? Yetişkininle paylaş.',learn:['Hareket edince nefesimiz ve kalbimiz biraz hızlanabilir.','Kendi rahat hızını seç. Yorulunca dinlen; rahatsız hissedersen bir yetişkine söyle.']}
];
