import type { SubjectId } from '@/lib/types';
export const subjects: {id:SubjectId;name:string;world:string;description:string;icon:string;color:string;slug:string;themes:string[]}[] = [
 {id:'math',name:'Matematik',world:'Sayı Gezegeni',description:'Say, birleştir, keşfet!',icon:'🪐',color:'peach',slug:'ilkokul-matematik-dersi',themes:['Sayılar ve Nicelikler (1)','Sayılar ve Nicelikler (2)','İşlemlerden Cebirsel Düşünmeye','Nesnelerin Geometrisi (1)','Nesnelerin Geometrisi (2)','Veriye Dayalı Araştırma']},
 {id:'tr',name:'Türkçe',world:'Hikâye Ormanı',description:'Her kelime bir macera.',icon:'🌳',color:'green',slug:'ilkokul-turkce-dersi',themes:['Değerlerimizle Varız','Atatürk ve Çocuk','Doğada Neler Oluyor?','Okuma Serüvenimiz','Yeteneklerimizi Tanıyoruz','Mucit Çocuk','Kültür Hazinemiz','Haklarımızı Biliyoruz']},
 {id:'life',name:'Hayat Bilgisi',world:'Keşif Dünyası',description:'Birlikte yaşamayı öğren.',icon:'🌍',color:'blue',slug:'hayat-bilgisi-dersi',themes:['Ben ve Okulum','Sağlığım ve Güvenliğim','Ailem ve Toplum','Yaşadığım Yer ve Ülkem','Doğa ve Çevre','Bilim, Teknoloji ve Sanat']},
 {id:'english',name:'İngilizce',world:'Kelime Şehri',description:'Hello, yeni arkadaşım!',icon:'🎈',color:'purple',slug:'ingilizce-dersi-temel-egitim',themes:['School Life','Classroom Life','Personal Life','Family Life','Homes & Houses & Neighbourhoods','Life in the City & the World']},
 {id:'art',name:'Görsel Sanatlar',world:'Renk Atölyesi',description:'Hayal et, rengini kat.',icon:'🎨',color:'pink',slug:'gorsel-sanatlar-dersi-temel-egitim',themes:['Hayat ve Sanat','Sanatın Görsel Dili','Sanatçılar ve Eserleri','Çizim ve Görsel İfade','Renk ve Estetik','Millî Değerler ve Sanat','Müze ve Kültür']},
 {id:'music',name:'Müzik',world:'Ritim Sahnesi',description:'Kendi ritmini bul.',icon:'🥁',color:'yellow',slug:'muzik-dersi-temel-egitim',themes:['Müzik Dili','Müzik Kültürü']},
 {id:'move',name:'Oyun ve Hareket',world:'Hareket Bahçesi',description:'Küçük bir hareket molası!',icon:'🤸',color:'mint',slug:'beden-egitimi-ve-oyun-dersi',themes:['Hareketimi Geliştiriyorum','Oyunun Kurallarını Uyguluyorum','Ritimle Hareket Ediyorum','Sağlığım İçin Fiziksel Aktiviteye Katılıyorum']}
];
