import type {Lesson} from '@/lib/types';
export const stories=[
 {theme:'Değerlerimizle Varız',title:'Sarı Şemsiye',icon:'☂️',text:'Lara okuldan çıkınca yağmur başladı. Çantasından sarı şemsiyesini çıkardı. Arkadaşı Ece durakta bekliyordu. Lara, “Birlikte yürüyelim mi?” diye sordu. İki arkadaş şemsiyenin altında eve yürüdü. Ece gülümseyerek teşekkür etti.',who:'Ece',where:'Durakta',why:'Arkadaşını yağmurdan korumak için',sentence:['Lara','şemsiyesini','arkadaşıyla','paylaştı.'],events:['Yağmur başladı.','Lara şemsiyesini açtı.','İki arkadaş birlikte yürüdü.'],word:'paylaşmak',meaning:'Bir şeyi başkasıyla birlikte kullanmak'},
 {theme:'Atatürk ve Çocuk',title:'Bayram Bahçesi',icon:'🇹🇷',text:'23 Nisan sabahı Lara okul bahçesine geldi. Ece ile renkli kâğıtlardan çiçekler yaptılar. Öğretmenleri, Atatürk’ün çocuklara duyduğu güveni anlattı. Lara şiirini okudu. Çocuklar birbirini alkışladı. Bahçe neşeyle doldu.',who:'Ece',where:'Okul bahçesinde',why:'23 Nisan’ı kutlamak için',sentence:['Çocuklar','bayramı','neşeyle','kutladı.'],events:['Lara bahçeye geldi.','Çocuklar çiçekler yaptı.','Lara şiirini okudu.'],word:'neşe',meaning:'Sevinç ve mutluluk'},
 {theme:'Doğada Neler Oluyor?',title:'Minik Tohum',icon:'🌱',text:'Lara ile Ece bir saksıya fasulye ekti. Saksıyı pencerenin yanına koydular. Her gün toprağını kontrol ettiler. Toprak kuruyunca az su verdiler. Bir sabah yeşil bir filiz gördüler. Küçük tohum artık büyüyordu.',who:'Ece',where:'Pencerenin yanında',why:'Tohumun büyümesine yardım etmek için',sentence:['Minik','tohum','yavaşça','büyüdü.'],events:['Fasulyeyi ektiler.','Toprağı suladılar.','Yeşil filizi gördüler.'],word:'filiz',meaning:'Tohumdan çıkan küçük bitki'},
 {theme:'Okuma Serüvenimiz',title:'Kitabın Yolculuğu',icon:'📚',text:'Lara kütüphanede bir uzay kitabı buldu. Önce kapağını ve resimlerini inceledi. Kitabı ödünç aldı. Evde ilginç bir bölümü Ece’ye okudu. Anlamadıkları sözcüğü sözlükten buldular. Ertesi hafta kitabı kütüphaneye geri götürdüler.',who:'Ece',where:'Kütüphanede',why:'Yeni bilgiler öğrenmek için',sentence:['Lara','kitabı','dikkatle','okudu.'],events:['Kitabın kapağını inceledi.','Kitabı ödünç aldı.','Kitabı geri götürdü.'],word:'ödünç',meaning:'Geri vermek üzere alınan'},
 {theme:'Yeteneklerimizi Tanıyoruz',title:'Küçük Sahne',icon:'🎭',text:'Lara resim yapmayı, Ece ise şarkı söylemeyi seviyordu. Sınıf gösterisi için birlikte çalıştılar. Lara sahneye bir gökkuşağı çizdi. Ece şarkısını söyledi. Birbirlerinin farklı yeteneklerini fark ettiler. Gösteri bitince birlikte eğildiler.',who:'Ece',where:'Sınıf sahnesinde',why:'Birlikte gösteri hazırlamak için',sentence:['Her','çocuğun','farklı','yetenekleri','vardır.'],events:['Birlikte çalıştılar.','Lara gökkuşağı çizdi.','Ece şarkısını söyledi.'],word:'yetenek',meaning:'Bir işi yapabilme becerisi'},
 {theme:'Mucit Çocuk',title:'Rüzgâr Arabası',icon:'💡',text:'Lara küçük bir karton kutu buldu. Ece ile kutuya dört kapak taktılar. Üstüne kâğıttan yelken eklediler. İlk denemede araba hareket etmedi. Yelkeni düzelttiler. Hafifçe üfleyince araba ilerledi. Denemek yeni fikirler getirmişti.',who:'Ece',where:'Karton arabanın yanında',why:'Rüzgârla hareket eden bir araç yapmak için',sentence:['Rüzgâr','küçük','arabayı','ilerletti.'],events:['Kutuyu buldular.','Kutuya tekerlek taktılar.','Yelkeni düzelttiler.'],word:'deneme',meaning:'Bir fikrin işe yarayıp yaramadığını görme'},
 {theme:'Kültür Hazinemiz',title:'Mendilin Renkleri',icon:'🧵',text:'Lara, Ece ile ninesini ziyaret etti. Ninesi eski bir mendil gösterdi. Mendilde renkli çiçek desenleri vardı. Her deseni eliyle işlediğini anlattı. Lara deseni defterine çizdi. Eve dönerken ailelerinden öğrendikleri bir oyunu oynadılar.',who:'Ece',where:'Ninesinin evinde',why:'Aileden kalan bir el işini tanımak için',sentence:['Mendilde','renkli','çiçek','desenleri','vardı.'],events:['Ninesini ziyaret etti.','Ninesi mendili gösterdi.','Lara deseni çizdi.'],word:'desen',meaning:'Bir yüzeyi süsleyen çizgi ve şekiller'},
 {theme:'Haklarımızı Biliyoruz',title:'Herkes İçin Oyun',icon:'🪁',text:'Lara ile Ece parkta oyun kurdu. Deniz de oynamak istedi. Çocuklar herkesin katılabileceği bir oyun seçtiler. Sırayla fikir söylediler. Birbirlerini dikkatle dinlediler. Lara, “Hepimizin oyun oynamaya hakkı var.” dedi.',who:'Ece',where:'Parkta',why:'Herkesin oyuna katılabilmesi için',sentence:['Her','çocuğun','oyun','hakkı','vardır.'],events:['Çocuklar oyun kurdu.','Deniz katılmak istedi.','Birlikte yeni oyun seçtiler.'],word:'hak',meaning:'Herkesin sahip olduğu temel olanak'}
];
export const trLessons:Lesson[]=stories.flatMap((s,i)=>[
 {id:`tr-story-${i}`,subject:'tr',theme:s.theme,title:s.title,subtitle:'Oku, dinle, hikâyeyi keşfet.',icon:s.icon,minutes:7,outcomes:['T.O.2.1','T.O.2.2','T.O.2.3','T.D.2.2','T.D.2.3'],learn:['Önce başlığa ve resme bak. Hikâye ne hakkında olabilir?',s.text,'Kim, nerede, ne yaptı? Cevaplarını metinden bul.'],story:s.text,kind:'choice',generator:`story-${i}`},
 {id:`tr-words-${i}`,subject:'tr',theme:s.theme,title:['Kelimelerden köprü','Bayram cümleleri','Filizin kelimeleri','Cümle treni','Yetenekli kelimeler','Fikir fabrikası','Desenli cümleler','Birlikte yazalım'][i],subtitle:'Kelime kartlarını taşı, cümleni kur.',icon:'🧩',minutes:7,outcomes:['T.Y.2.2','T.Y.2.3'],learn:['Kelimeler sıraya girince bir düşünce anlatır.','Cümleye büyük harfle başla. Bitince uygun işareti koy.',s.sentence.join(' ')],words:s.sentence,kind:'ordering',generator:`words-${i}`},
 {id:`tr-tell-${i}`,subject:'tr',theme:s.theme,title:['Bir iyilik anlat','Bayramı anlatıyorum','Doğa günlüğüm','Benim kitap köşem','Neyi severek yaparım?','Benim buluşum','Bir aile hatırası','Fikrimi söylüyorum'][i],subtitle:'Anlat, yaz ve kendini değerlendir.',icon:'💬',minutes:6,outcomes:['T.K.2.1','T.K.2.2','T.K.2.3','T.Y.2.1'],learn:['Önce ne anlatacağını düşün. Başlangıç, sonra olanlar ve son…','Yavaş ve anlaşılır konuş. Sonra düşünceni bir iki cümleyle yaz.'],story:s.text,kind:'speaking',generator:`tell-${i}`,task:`“${s.title}” hikâyesini kendi sözlerinle anlat. Sonra hikâyeye yeni bir son düşün.`}
 ] as Lesson[]);
