// Original questions derived from our own stories, not copied from textbooks.
export const storyWorkshops=[
 {detail:['Durakta kim bekliyordu?','Ece','Lara','Öğretmen'],place:'Ece, Lara ile karşılaşmadan önce nerede bekliyordu?',cause:'Lara neden birlikte yürümeyi önerdi?',inference:'Bir şeyi paylaşmak bir arkadaşımıza yardım edebilir.',alternatives:['Yardım etmek için mutlaka bir hediye almalıyız.','Yağmur yağınca herkes yalnız yürümelidir.'],sentences:[['Ece','durakta','Lara’yı','bekliyordu.'],['İki','arkadaş','birlikte','yürüdü.']]},
 {detail:['Şiiri kim okudu?','Lara','Ece','Öğretmen'],place:'Çocuklar bayramı nerede kutladı?',cause:'Çocuklar neden bahçeyi süsledi?',inference:'Birlikte hazırlanmak bayram sevincini paylaşmamızı sağlar.',alternatives:['Bir bayramda yalnızca şiir okunabilir.','Herkesin aynı etkinliği yapması gerekir.'],sentences:[['Lara','bahçede','şiirini','okudu.'],['Ece','kâğıttan','çiçekler','yaptı.']]},
 {detail:['Lara ile Ece saksıya ne ekti?','Fasulye','Elma çekirdeği','Çiçek yaprağı'],place:'Saksıyı nereye koydular?',cause:'Toprağı neden kontrol edip suladılar?',inference:'Bir bitkinin büyümesini görmek için bakım ve sabır gerekir.',alternatives:['Bir tohum ekildiği anda büyük bir ağaca dönüşür.','Bitkilere ne kadar çok su verirsek o kadar iyidir.'],sentences:[['Çocuklar','toprağı','kontrol','etti.'],['Yeşil','filiz','topraktan','çıktı.']]},
 {detail:['Lara nasıl bir kitap buldu?','Uzay kitabı','Yemek kitabı','Boyama kitabı'],place:'Lara uzay kitabını nerede buldu?',cause:'Lara neden kitabı alıp okudu?',inference:'Anlamadığımız sözcükler için sözlükten yararlanabiliriz.',alternatives:['Bir kitabı anlamak için yalnızca resimlere bakmalıyız.','Ödünç aldığımız kitap bizde kalır.'],sentences:[['Lara','kitabı','ödünç','aldı.'],['Çocuklar','sözcüğü','sözlükten','buldu.']]},
 {detail:['Şarkı söylemeyi kim seviyordu?','Ece','Lara','Öğretmen'],place:'Lara ve Ece gösterilerini nerede yaptı?',cause:'Lara ile Ece neden birlikte çalıştı?',inference:'Farklı yeteneklerimizle ortak bir işe katkı sağlayabiliriz.',alternatives:['Arkadaşların aynı yeteneğe sahip olması gerekir.','Gösteri hazırlarken yalnız çalışmalıyız.'],sentences:[['Lara','sahneye','gökkuşağı','çizdi.'],['Ece','şarkısını','neşeyle','söyledi.']]},
 {detail:['Tekerlek yapmak için ne kullandılar?','Dört kapak','Dört yaprak','İki kalem'],place:'Çocuklar deneme yaparken neyin yanındaydı?',cause:'Lara ile Ece neden karton kutuya yelken ekledi?',inference:'İlk deneme olmazsa fikrimizi değiştirip yeniden deneyebiliriz.',alternatives:['İlk denemede olmayan bir işi bırakmalıyız.','Her karton kutu kendiliğinden hareket eder.'],sentences:[['Çocuklar','yelkeni','birlikte','düzeltti.'],['Küçük','araba','yavaşça','ilerledi.']]},
 {detail:['Mendilin desenlerini kim işlemişti?','Lara’nın ninesi','Lara','Ece'],place:'Çocuklar mendili nerede inceledi?',cause:'Lara neden ninesinin gösterdiği mendili inceledi?',inference:'Büyüklerimizin el işleri ailemizin geçmişini tanımamıza yardım eder.',alternatives:['Eski eşyaların hiçbir hikâyesi yoktur.','Bütün mendillerde aynı desen vardır.'],sentences:[['Ninesi','eski','mendili','gösterdi.'],['Lara','deseni','defterine','çizdi.']]},
 {detail:['Oyuna sonradan kim katılmak istedi?','Deniz','Ece','Lara'],place:'Çocuklar oyunu nerede kurdu?',cause:'Çocuklar neden yeni bir oyun seçti?',inference:'Birlikte karar verirken herkesin fikrini dinlemeliyiz.',alternatives:['Oyunu yalnızca ilk gelen kişi seçmelidir.','Yeni gelen arkadaşlar oyuna katılamaz.'],sentences:[['Deniz','oyuna','katılmak','istedi.'],['Çocuklar','birbirlerini','dikkatle','dinledi.']]}
];
