'use client';
import {useRef,useState} from 'react';
import type {Question} from '@/lib/types';
import {blockValue,exchangeBlocks} from '@/lib/manipulatives';
import {sfx} from '@/lib/audio';
export function BlockPicture({ten=false}:{ten?:boolean}){return <svg className={ten?'ten-picture':'one-picture'} viewBox={ten?'0 0 24 204':'0 0 24 24'} aria-hidden="true">{Array.from({length:ten?10:1},(_,i)=><g key={i}><rect x="2" y={2+i*20} width="20" height="20" rx="2" fill={ten?'#78b6cf':'#f1ce63'} stroke={ten?'#386e83':'#8a6928'} strokeWidth="1.3"/><path d={`M5 ${7+i*20}v-2h13`} fill="none" stroke="#ffffffa0" strokeWidth="2"/></g>)}</svg>}
export default function BaseTenBlocks({q,onAnswer,disabled,sound=false,reveal=false}:{q:Question;onAnswer:(s:string)=>void;disabled:boolean;sound?:boolean;reveal?:boolean}){
 const [blocks,setBlocks]=useState({tens:0,ones:0}),[message,setMessage]=useState(''),[ghost,setGhost]=useState<{v:number;x:number;y:number}|null>(null);
 const workspace=useRef<HTMLDivElement>(null),tray=useRef<HTMLDivElement>(null),pointer=useRef<{v:number;remove:boolean;x:number;y:number;moved:boolean}|null>(null),suppress=useRef(false);
 const {tens,ones}=blocks,total=blockValue(tens,ones);
 function change(t:number,u:number){if(disabled||t<0||u<0||blockValue(t,u)>100)return false;setBlocks({tens:t,ones:u});onAnswer(String(blockValue(t,u)));return true}
 function transfer(v:number,remove=false){if(change(tens+(v===10?(remove?-1:1):0),ones+(v===1?(remove?-1:1):0)))sfx(sound,remove?'remove':'place');setMessage(remove?'Blok kutuya döndü.':'')}
 const handlers=(v:number,remove=false)=>({onPointerDown:(e:React.PointerEvent<HTMLButtonElement>)=>{if(disabled||e.button>0)return;suppress.current=false;e.currentTarget.setPointerCapture(e.pointerId);pointer.current={v,remove,x:e.clientX,y:e.clientY,moved:false}},onPointerMove:(e:React.PointerEvent<HTMLButtonElement>)=>{const p=pointer.current;if(p&&Math.hypot(e.clientX-p.x,e.clientY-p.y)>6){p.moved=true;setGhost({v,x:e.clientX,y:e.clientY})}},onPointerUp:(e:React.PointerEvent<HTMLButtonElement>)=>{const p=pointer.current;if(p?.moved){suppress.current=true;const r=(p.remove?tray:workspace).current?.getBoundingClientRect();if(r&&e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom)transfer(p.v,p.remove)}pointer.current=null;setGhost(null)},onPointerCancel:()=>{pointer.current=null;setGhost(null)},onClick:(e:React.MouseEvent<HTMLButtonElement>)=>{if(suppress.current){suppress.current=false;if(e.detail!==0)return}transfer(v,remove)}});
 function exchange(direction:'group'|'split'){const next=exchangeBlocks(tens,ones,direction);if(change(next.tens,next.ones))sfx(sound,'hop');setMessage(direction==='group'?'10 birlik birleşti, 1 onluk oldu. Sayımız değişmedi!':'1 onluk açıldı, 10 birlik oldu. Sayımız değişmedi!')}
 return <div className="base-ten-lab"><p className="tool-help">Kutudan blok alıp alana taşı veya dokun. Çıkarmak için bloğa dokun ya da kutuya geri taşı.</p>
  <div className="base-ten-tray" ref={tray} aria-label="Blok kutusu"><button {...handlers(10)} disabled={disabled||total>90} aria-label="Bir onluk ekle"><BlockPicture ten/><span><b>1 onluk</b><small>10 birlik</small></span><span aria-hidden="true">＋</span></button><button {...handlers(1)} disabled={disabled||total>=100} aria-label="Bir birlik ekle"><BlockPicture/><span><b>1 birlik</b><small>Tek bir küp</small></span><span aria-hidden="true">＋</span></button></div>
  <div ref={workspace} className={`place-value-board ${ghost?'receiving':''}`} aria-label="Blok çalışma alanı"><section className="tens-column"><h3>Onluklar <span>{tens}</span></h3><div className="tens-rack">{Array.from({length:tens},(_,i)=><button {...handlers(10,true)} disabled={disabled} key={i} aria-label="Bir onluk çıkar"><BlockPicture ten/></button>)}{tens===0&&<span className="empty-block-space">Onluk çubuklarını<br/>buraya getir</span>}</div></section><section className="ones-column"><h3>Birlikler <span>{ones}</span></h3><div className="ones-rack">{Array.from({length:Math.max(10,Math.ceil(ones/10)*10)},(_,i)=>i<ones?<button {...handlers(1,true)} key={i} disabled={disabled} aria-label="Bir birlik çıkar"><BlockPicture/></button>:<span key={i} className="unit-slot" aria-hidden="true"/>)}</div></section></div>
  <output className="place-value-equation"><span><b>{tens}</b> onluk <small>{tens*10}</small></span><i>+</i><span><b>{ones}</b> birlik <small>{ones}</small></span><i>=</i><strong>{total}</strong></output>
  <div className="exchange-actions"><button disabled={disabled||ones<10} onClick={()=>exchange('group')}>10 birlik → 1 onluk</button><button disabled={disabled||tens<1} onClick={()=>exchange('split')}>1 onluk → 10 birlik</button><button disabled={disabled||total===0} onClick={()=>{if(change(0,0))sfx(sound,'remove');setMessage('Yeni bir sayı kurabilirsin.')}}>↻ Yeniden kur</button></div><p className="exchange-message" role="status" key={message}>{message||'Her mavi çubukta tam 10 küçük birlik var.'}</p>
  {ghost&&<div className="block-drag-preview" style={{left:ghost.x,top:ghost.y}}><BlockPicture ten={ghost.v===10}/></div>}
  {reveal&&<div className="solution-model"><p>{q.answer} için {Math.floor(Number(q.answer)/10)} onluk ve {Number(q.answer)%10} birlik gerekir.</p><button onClick={()=>{const n=Number(q.answer);setBlocks({tens:Math.floor(n/10),ones:n%10})}}>Çözümü bloklarla göster</button></div>}
 </div>;
}
export function BundlingDemo(){const [grouped,setGrouped]=useState(false);return <div className="bundling-demo"><p><b>10 küçük birlik, 1 onluk eder.</b></p><div className={`bundle-model ${grouped?'is-bundled':''}`} aria-label={grouped?'Birleşmiş 10 birlik: 1 onluk':'Ayrı duran 10 birlik'}>{Array.from({length:10},(_,i)=><span key={i} style={{transform:`translate(${grouped?0:(i%5)*42-84}px, ${grouped?i*20-90:Math.floor(i/5)*48-24}px)`}}><BlockPicture/></span>)}</div><button onClick={()=>setGrouped(!grouped)}>{grouped?'↔ Onluğu birliklerine ayır':'→ 10 birliği birleştir'}</button><p aria-live="polite">{grouped?'1 onluk = 10 birlik. Miktar değişmedi.':'Birlikleri say, sonra bir çubukta birleştir.'}</p></div>}
