'use client';
import {useId,useRef,useState} from 'react';
import type {Question} from '@/lib/types';
export type ShapeName='square'|'triangle'|'circle'|'rectangle'|'cube'|'sphere'|'cylinder'|'prism';
export const shapeNames:Record<ShapeName,string>={square:'Kare',triangle:'Üçgen',circle:'Daire',rectangle:'Dikdörtgen',cube:'Küp',sphere:'Küre',cylinder:'Silindir',prism:'Dikdörtgenler prizması'};
export function ShapeGraphic({shape,outline=false}:{shape:ShapeName;outline?:boolean}){
 const id=useId().replaceAll(':','');const fill=outline?'#f0f1e9':'#83b9ce',stroke=outline?'#85937c':'#325d70';
 const style={stroke,strokeWidth:2.5,strokeLinejoin:'round' as const,fill,strokeDasharray:outline?'5 4':undefined};
 return <svg viewBox="0 0 120 120" className="shape-graphic" aria-hidden="true">
  {shape==='square'&&<rect x="20" y="20" width="80" height="80" {...style}/>}
  {shape==='rectangle'&&<rect x="10" y="32" width="100" height="56" {...style}/>}
  {shape==='triangle'&&<path d="M60 12 108 102H12Z" {...style} fill={outline?fill:'#e9b778'}/>}
  {shape==='circle'&&<circle cx="60" cy="60" r="43" {...style} fill={outline?fill:'#a3be84'}/>}
  {(shape==='cube'||shape==='prism')&&<g transform={shape==='prism'?'translate(-7 16) scale(1.12 .75)':undefined}><path d="M16 36 59 13 103 36 103 84 60 109 16 84Z" {...style}/><path d="M16 36 60 60 103 36 59 13Z" fill={outline?fill:'#b5d7e3'} stroke={stroke} strokeWidth="2.5"/><path d="M60 60v49l43-25V36Z" fill={outline?fill:'#5d97b0'} stroke={stroke} strokeWidth="2.5"/><path d="M16 36 60 60v49" fill="none" stroke={stroke} strokeWidth="2.5"/></g>}
  {shape==='sphere'&&<><defs><radialGradient id={id} cx="32%" cy="28%"><stop offset="0" stopColor="#eaf1d9"/><stop offset=".6" stopColor="#a6c57e"/><stop offset="1" stopColor="#61864c"/></radialGradient></defs><circle cx="60" cy="60" r="44" fill={outline?fill:`url(#${id})`} stroke={outline?stroke:'#486a36'} strokeWidth="2.5"/></>}
  {shape==='cylinder'&&<><path d="M24 30v61c0 21 72 21 72 0V30" {...style}/><path d="M25 91c0 20 70 20 70 0" fill="none" stroke={stroke} strokeWidth="2.5"/><ellipse cx="60" cy="30" rx="36" ry="16" {...style} fill={outline?fill:'#b5d7e3'}/></>}
 </svg>;
}
type Props={q:Question;onAnswer:(s:string)=>void;disabled:boolean;reveal?:boolean};
const vertices:Partial<Record<ShapeName,[number,number][]>>={square:[[20,20],[100,20],[100,100],[20,100]],triangle:[[60,12],[108,102],[12,102]],rectangle:[[10,32],[110,32],[110,88],[10,88]]};
export default function GeometryLab(props:Props){if(props.q.visual==='compose'||props.q.visual==='build')return <ShapeComposer {...props}/>;if(props.q.visual==='symmetry')return <MirrorGrid {...props}/>;return <ShapeExplorer {...props}/>}
function ShapeExplorer({q,onAnswer,disabled}:Props){
 const shape=(q.items?.[0]??'square') as ShapeName,[rotation,setRotation]=useState(0),[size,setSize]=useState(85),[corners,setCorners]=useState<number[]>([]),[selected,setSelected]=useState('');const solid=['cube','sphere','cylinder','prism'].includes(shape);
 return <div className="geometry-lab"><p className="tool-help">{solid?'Cismin çizimini incele. Düz yüzlerine ve yuvarlak bölümlerine dikkat et.':'Şekli döndür, büyüt, köşelerine dokun. Yönü değişse de aynı şekildir.'}</p><div className="shape-explorer"><div className="shape-turntable" style={{width:`${size*2.4}px`,maxWidth:'82%',transform:`rotate(${rotation}deg)`}}><ShapeGraphic shape={shape}/>{!solid&&<svg viewBox="0 0 120 120" className="corner-layer" aria-label="Şeklin köşeleri">{vertices[shape]?.map(([x,y],i)=><g role="button" tabIndex={disabled?-1:0} aria-disabled={disabled} aria-label={`${i+1}. köşeyi işaretle`} aria-pressed={corners.includes(i)} key={i} onClick={()=>!disabled&&setCorners(corners.includes(i)?corners.filter(c=>c!==i):[...corners,i])} onKeyDown={e=>{if(!disabled&&['Enter',' '].includes(e.key)){e.preventDefault();setCorners(corners.includes(i)?corners.filter(c=>c!==i):[...corners,i])}}}><circle cx={x} cy={y} r={Math.max(16,1100/size)} fill={corners.includes(i)?'#ffe3a1':'transparent'} stroke={corners.includes(i)?'#8c622a':'transparent'} strokeWidth="1.5"/>{corners.includes(i)&&<text x={x} y={y} dominantBaseline="central" textAnchor="middle" fontSize="9" fontWeight="800" transform={`rotate(${-rotation} ${x} ${y})`}>{corners.indexOf(i)+1}</text>}</g>)}</svg>}</div></div>
 {!solid&&<><div className="geometry-controls"><button disabled={disabled} onClick={()=>setRotation(r=>r-45)}>↶ Sola döndür</button><button disabled={disabled} onClick={()=>setRotation(r=>r+45)}>↷ Sağa döndür</button><label>Büyüklük<input type="range" min="50" max="90" step="5" value={size} disabled={disabled} onChange={e=>setSize(Number(e.target.value))}/></label></div><p className="counted-corners" aria-live="polite">{corners.length?`${corners.length} köşeyi işaretledin.`:'Şeklin kenarlarını parmağınla takip et.'}</p></>}
 <div className="options">{q.options?.map(o=><button key={o} disabled={disabled} className={selected===o?'selected':''} aria-pressed={selected===o} onClick={()=>{setSelected(o);onAnswer(o)}}>{o}</button>)}</div></div>;
}
export function compositionPlan(mode:string,variant=0):{shape:ShapeName;x:number;y:number}[]{return mode==='build'?[{shape:'cube',x:240,y:235},{shape:'cube',x:360,y:235},{shape:'cube',x:300,y:135}]:variant%2===0?[{shape:'square',x:300,y:245},{shape:'triangle',x:300,y:163},{shape:'circle',x:465,y:80}]:[{shape:'rectangle',x:300,y:180},{shape:'circle',x:255,y:240},{shape:'circle',x:345,y:240}]}
function ShapeComposer({q,onAnswer,disabled,reveal}:Props){
 const plan=compositionPlan(q.visual!,q.value),[placed,setPlaced]=useState<Record<number,number>>({}),[selected,setSelected]=useState<number|null>(null),[ghost,setGhost]=useState<{piece:number;x:number;y:number}|null>(null),[notice,setNotice]=useState('');
 const board=useRef<HTMLDivElement>(null),pointer=useRef<{piece:number;x:number;y:number;moved:boolean}|null>(null),suppress=useRef(false);
 function put(piece:number,slot:number){if(disabled)return;if(plan[piece].shape!==plan[slot].shape){setNotice('Kenarlarına bak: bu boşluğa başka bir parça uyuyor.');return}if(Object.values(placed).includes(slot)&&placed[piece]!==slot){setNotice('Bu yer dolu. Boş bir yer seç.');return}const next={...placed,[piece]:slot};setPlaced(next);setSelected(null);setNotice('Parça yerine oturdu!');onAnswer(Object.keys(next).length===plan.length?'done':'')}
 const handlers=(piece:number)=>({onPointerDown:(e:React.PointerEvent<HTMLButtonElement>)=>{if(disabled)return;suppress.current=false;e.currentTarget.setPointerCapture(e.pointerId);pointer.current={piece,x:e.clientX,y:e.clientY,moved:false}},onPointerMove:(e:React.PointerEvent<HTMLButtonElement>)=>{const p=pointer.current;if(p&&Math.hypot(e.clientX-p.x,e.clientY-p.y)>6){p.moved=true;setGhost({piece,x:e.clientX,y:e.clientY})}},onPointerUp:(e:React.PointerEvent<HTMLButtonElement>)=>{if(pointer.current?.moved&&board.current){suppress.current=true;const r=board.current.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*600,y=(e.clientY-r.top)/r.height*340;const slot=plan.findIndex(s=>Math.hypot(s.x-x,s.y-y)<48);if(slot>=0)put(piece,slot);else setNotice('Parçayı kesik çizgili bir yerin ortasına bırak.')}pointer.current=null;setGhost(null)},onPointerCancel:()=>{pointer.current=null;setGhost(null)},onClick:(e:React.MouseEvent<HTMLButtonElement>)=>{if(suppress.current){suppress.current=false;if(e.detail!==0)return}setSelected(piece);setNotice('Şimdi bu parçaya uygun boş yere dokun.')}});
 return <div className="shape-composer"><p className="tool-help">Parçaları kesik çizgilerin üstüne sürükle. İstersen önce parçaya, sonra yerine dokun.</p><div className="shape-pieces" aria-label="Şekil kutusu">{plan.map((p,i)=><button key={i} {...handlers(i)} disabled={disabled||placed[i]!==undefined} aria-label={`${i+1}. ${shapeNames[p.shape]} parçasını seç`} aria-pressed={selected===i} className={selected===i?'selected':''}><ShapeGraphic shape={p.shape}/><small>{shapeNames[p.shape]}</small></button>)}</div>
 <div className="composition-board" ref={board} aria-label="Şekilleri yerleştirme alanı"><span className="composition-ground"/>{plan.map((p,i)=>{const piece=Object.keys(placed).find(k=>placed[Number(k)]===i);return <button key={i} className="shape-slot" style={{left:`${p.x/6}%`,top:`${p.y/3.4}%`}} disabled={disabled} aria-label={`${i+1}. ${shapeNames[p.shape]} yeri${piece!==undefined?', dolu':''}`} onClick={()=>{if(selected!==null)put(selected,i);else setNotice(piece!==undefined?'Bu parça yerinde.':'Önce kutudan bir parça seç.')}}><ShapeGraphic shape={p.shape} outline={piece===undefined}/></button>})}</div>
 <p role="status" className="composition-status">{notice||'Bakalım bu parçalar birleşince ne olacak?'} <b>{Object.keys(placed).length} / {plan.length} parça</b></p><button disabled={disabled||!Object.keys(placed).length} onClick={()=>{setPlaced({});onAnswer('');setNotice('Parçalar kutuya döndü.')}}>↻ Yeniden kur</button>
 {ghost&&<div className="shape-drag-preview" style={{left:ghost.x,top:ghost.y}}><ShapeGraphic shape={plan[ghost.piece].shape}/></div>}{reveal&&<p>Önce kenarlara bak. {plan.map(p=>shapeNames[p.shape]).join(', ')} parçalarını aynı biçimdeki yerlere taşı.</p>}
 </div>;
}
function MirrorGrid({q,onAnswer,disabled,reveal}:Props){const pattern=(q.items??[]).map(Number),[cells,setCells]=useState<number[]>([]),[fold,setFold]=useState(false);return <div className="mirror-lab"><p className="tool-help">Ortadaki çizgi bir ayna. Soldaki boyalı karelerin karşılığını sağda boya.</p><div className="mirror-board"><div className="mirror-half">{Array.from({length:12},(_,i)=><span key={i} className={pattern.includes(i)?'painted':''}/>)}</div><div className="mirror-half mirror-edit">{Array.from({length:12},(_,i)=><button key={i} disabled={disabled} className={`${cells.includes(i)?'painted':''} ${fold&&q.answer.split('|').includes(String(i))?'mirror-hint':''}`} aria-label={`Sağ taraf, ${Math.floor(i/3)+1}. satır ${i%3+1}. sütun`} aria-pressed={cells.includes(i)} onClick={()=>{const next=cells.includes(i)?cells.filter(c=>c!==i):[...cells,i];next.sort((a,b)=>a-b);setCells(next);onAnswer(next.join('|'))}}/>)}</div></div>{reveal&&<button onClick={()=>setFold(!fold)}>{fold?'Yansımayı gizle':'Aynadaki yansımayı göster'}</button>}<p>Çizgiye yakın bir kare, öbür tarafta da çizgiye yakın olur.</p></div>}
