'use client';
import {useRef,useState} from 'react';
import type {Question} from '@/lib/types';
import {insertOrderedItem} from '@/lib/manipulatives';
type Props={q:Question;onAnswer:(s:string)=>void;disabled:boolean;reveal?:boolean};
export function SentenceBuilder({q,onAnswer,disabled,reveal}:Props){
 const [order,setOrder]=useState<string[]>([]),[ghost,setGhost]=useState<{word:string;x:number;y:number}|null>(null),[hover,setHover]=useState<number|null>(null);
 const target=useRef<HTMLDivElement>(null),pointer=useRef<{word:string;x:number;y:number;moved:boolean}|null>(null),suppress=useRef(false);const items=q.items??[],isSentence=q.skill.startsWith('T.Y');
 const change=(next:string[])=>{setOrder(next);onAnswer(next.join('|'))};
 function insert(word:string,index:number){change(insertOrderedItem(order,word,index))}
 function gapAt(x:number,y:number){const el=document.elementFromPoint(x,y)?.closest<HTMLElement>('[data-order-index]');if(!el||!target.current?.contains(el))return order.length;const index=Number(el.dataset.orderIndex),r=el.getBoundingClientRect();return index+(index<order.length&&x>r.left+r.width/2?1:0)}
 const handlers=(word:string)=>({onPointerDown:(e:React.PointerEvent<HTMLButtonElement>)=>{if(disabled||e.button>0)return;suppress.current=false;e.currentTarget.setPointerCapture(e.pointerId);pointer.current={word,x:e.clientX,y:e.clientY,moved:false}},onPointerMove:(e:React.PointerEvent<HTMLButtonElement>)=>{const p=pointer.current;if(p&&Math.hypot(e.clientX-p.x,e.clientY-p.y)>6){p.moved=true;setGhost({word,x:e.clientX,y:e.clientY});setHover(gapAt(e.clientX,e.clientY))}},onPointerUp:(e:React.PointerEvent<HTMLButtonElement>)=>{if(pointer.current?.moved){suppress.current=true;const r=target.current?.getBoundingClientRect();if(r&&e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom)insert(word,gapAt(e.clientX,e.clientY))}pointer.current=null;setGhost(null);setHover(null)},onPointerCancel:()=>{pointer.current=null;setGhost(null);setHover(null)},onClick:(e:React.MouseEvent<HTMLButtonElement>)=>{if(suppress.current){suppress.current=false;if(e.detail!==0)return}change(order.includes(word)?order.filter(w=>w!==word):[...order,word])},onKeyDown:(e:React.KeyboardEvent<HTMLButtonElement>)=>{const i=order.indexOf(word);if(!disabled&&i>=0&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const j=i+(e.key==='ArrowLeft'?-1:1);if(j>=0&&j<order.length){const next=[...order];[next[i],next[j]]=[next[j],next[i]];change(next)}}}});
 return <div className="sentence-workshop"><p className="tool-help">Kartları sırayla seç veya sürükle. Yerini değiştirmek için kartı taşı; klavyede sağ ve sol okları kullan.</p><div ref={target} className={`sentence-slots ${ghost?'receiving':''}`} aria-label={isSentence?'Cümle alanı':'Sıralama alanı'}>{Array.from({length:items.length},(_,i)=>order[i]?<button key={order[i]} {...handlers(order[i])} data-order-index={i} disabled={disabled} className={hover===i?'insert-before':''} aria-label={`${i+1}. kart: ${order[i]}`}><small>{i+1}</small><span>{order[i]}</span></button>:<span className="empty-word-slot" data-order-index={i} key={`empty-${i}`}><small>{i+1}</small>…</span>)}</div><div className="word-bank" aria-label="Kart kutusu">{items.filter(w=>!order.includes(w)).map(word=><button key={word} {...handlers(word)} disabled={disabled}>{word}</button>)}{order.length===items.length&&<span className="muted">Tüm kartlar yerinde. Şimdi {isSentence?'cümleni oku':'sırayı kontrol et'}.</span>}</div>{isSentence&&order.length>0&&<div className="sentence-reading"><small>BENİM CÜMLEM</small><p>{order.join(' ')}</p></div>}<button disabled={disabled||!order.length} onClick={()=>change([])}>↻ Kartları geri al</button>{reveal&&<p className="solution-model">{q.answer.split('|').join(isSentence?' ':' → ')}</p>}{ghost&&<span className="word-drag-preview" style={{left:ghost.x,top:ghost.y}}>{ghost.word}</span>}</div>;
}
export function Punctuation({q,onAnswer,disabled,reveal}:Props){const [mark,setMark]=useState(''),[ghost,setGhost]=useState<{mark:string;x:number;y:number}|null>(null);const slot=useRef<HTMLButtonElement>(null),pointer=useRef<{mark:string;x:number;y:number;moved:boolean}|null>(null),suppress=useRef(false);const names:Record<string,string>={'.':'Nokta','?':'Soru işareti','!':'Ünlem işareti'};const choose=(v:string)=>{setMark(v);onAnswer(v)};return <div className="punctuation-lab"><p className="tool-help">Cümleyi oku. Uygun işareti boşluğa taşı veya işarete dokun.</p><div className="punctuation-paper"><span>{q.items?.[0]}</span><button ref={slot} disabled={disabled} className={mark?'filled':''} aria-label="Cümlenin sonundaki işaret" onClick={()=>choose('')}>{mark||'…'}</button></div><div className="punctuation-tray">{['.','?','!'].map(m=><button key={m} disabled={disabled} aria-label={names[m]} aria-pressed={mark===m} className={mark===m?'selected':''} onPointerDown={e=>{suppress.current=false;e.currentTarget.setPointerCapture(e.pointerId);pointer.current={mark:m,x:e.clientX,y:e.clientY,moved:false}}} onPointerMove={e=>{const p=pointer.current;if(p&&Math.hypot(e.clientX-p.x,e.clientY-p.y)>6){p.moved=true;setGhost({mark:m,x:e.clientX,y:e.clientY})}}} onPointerUp={e=>{if(pointer.current?.moved){suppress.current=true;const r=slot.current?.getBoundingClientRect();if(r&&e.clientX>=r.left-20&&e.clientX<=r.right+20&&e.clientY>=r.top-20&&e.clientY<=r.bottom+20)choose(m)}pointer.current=null;setGhost(null)}} onPointerCancel={()=>{pointer.current=null;setGhost(null)}} onClick={e=>{if(suppress.current){suppress.current=false;if(e.detail!==0)return}choose(m)}}><strong>{m}</strong><small>{names[m]}</small></button>)}</div>{reveal&&<p className="solution-model">{q.items?.[0]}<b>{q.answer}</b> — {q.explanation}</p>}{ghost&&<span className="word-drag-preview punctuation-ghost" style={{left:ghost.x,top:ghost.y}}>{ghost.mark}</span>}</div>}
