'use client';
import {useEffect,useRef,useState} from 'react';
import type {Question} from '@/lib/types';
import {sfx} from '@/lib/audio';
import Choices from './Choices';
type Props={q:Question;onAnswer:(s:string,check?:boolean)=>void;disabled:boolean;sound:boolean;reveal?:boolean;wrong?:string[]};
export function Money({onAnswer,disabled,sound}:Props){const [coins,setCoins]=useState<number[]>([]);function change(arr:number[]){setCoins(arr);onAnswer(String(arr.reduce((a,b)=>a+b,0)))}return <div><div className="coin-tray">{[25,50,100].map(c=><button disabled={disabled||coins.length>=16} className="coin" key={c} onClick={()=>{change([...coins,c]);sfx(sound,'coin')}}>{c===100?'1 TL':`${c} kr`}</button>)}</div><div className="piggy"><span>🐷</span><div>{coins.map((c,i)=><button disabled={disabled} key={i} onClick={()=>{change(coins.filter((_,j)=>i!==j));sfx(sound,'remove')}}>{c} kr ×</button>)}</div><output>Toplam: {coins.reduce((a,b)=>a+b,0)} kuruş</output></div></div>}
export function Graph({q,onAnswer,disabled,sound}:Props){const [n,setN]=useState(0);return <div className="graph-tool"><p>Her meyve = 1 kişi</p><div><b>Elma</b><span>{'🍎'.repeat(n)||'—'}</span></div><div><b>Armut</b><span>{'🍐'.repeat(q.start??2)}</span></div><div className="tool-actions"><button disabled={disabled||n<=0} onClick={()=>{setN(n-1);onAnswer(String(n-1));sfx(sound,'remove')}}>− Bir elma</button><button disabled={disabled||n>=8} onClick={()=>{setN(n+1);onAnswer(String(n+1));sfx(sound,'place')}}>+ Bir elma</button></div></div>}
export function Measure({q,onAnswer,disabled,sound}:Props){const [show,setShow]=useState(false),[n,setN]=useState(5);return <div className="measure-tool"><div className="ruler-scene"><div className="pencil" role="img" aria-label="Kalem" style={{width:`calc(${q.value??5} * (100% - 12px) / 10)`}}><i/><b/><em/></div><div className={`ruler ${show?'':'hidden-ruler'}`}>{Array.from({length:11},(_,i)=><span key={i}>{i}</span>)}</div></div><p>Bu çizim bir modeldir; ekrandaki boyut gerçek santimetre değildir.</p><label>Tahminim / ölçümüm: {n} cm<input aria-label="Uzunluk" type="range" min="1" max="10" value={n} disabled={disabled} onChange={e=>{setN(Number(e.target.value));onAnswer(e.target.value);sfx(sound,'tick')}}/></label><div className="tool-actions"><button onClick={()=>{setShow(true);onAnswer(String(n));sfx(sound,'hop')}}>Cetveli göster ve karşılaştır</button></div></div>}
export function Rhythm({q,onAnswer,disabled,sound,wrong=[]}:Props){const [input,setInput]=useState<string[]>([]),[beat,setBeat]=useState(-1),[speed,setSpeed]=useState(600);const timers=useRef<ReturnType<typeof setTimeout>[]>([]);useEffect(()=>()=>timers.current.forEach(clearTimeout),[]);const play=()=>{timers.current.forEach(clearTimeout);q.items?.forEach((v,i)=>{timers.current.push(setTimeout(()=>{setBeat(i);if(v==='👏')sfx(sound,'clap')},i*speed))});timers.current.push(setTimeout(()=>setBeat(-1),(q.items?.length??4)*speed))};return <div className="rhythm-tool"><div className="beats">{q.items?.map((x,i)=><span className={beat===i?'active':''} key={i}>{x}<small>{x==='—'?'Sus':'Vur'}</small></span>)}</div><div className="tool-actions"><button onClick={play}>▶ Ritmi {sound?'dinle':'gör'}</button><label>Tempo <select value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={850}>Yavaş</option><option value={600}>Orta</option><option value={400}>Hızlı</option></select></label></div>{!sound&&<p className="muted">Ses kapalı. Işıkları izleyebilir veya üstten sesi açabilirsin.</p>}<div className={`beats input-beats ${disabled&&input.join('|')===q.answer?'is-correct':input.length&&wrong.includes(input.join('|'))?'is-wrong':''}`}>{Array.from({length:4},(_,i)=><span key={i}>{input[i]??'?'}</span>)}</div><div className="tool-actions">{['👏','—'].map(x=><button disabled={disabled||input.length>=4} key={x} onClick={()=>{const a=[...input,x];setInput(a);if(x==='👏')sfx(sound,'clap');onAnswer(a.join('|'),a.length===(q.items?.length??4))}}>{x==='👏'?'👏 Vuruş':'— Sus'}</button>)}<button disabled={disabled||!input.length} onClick={()=>{setInput([]);onAnswer('');sfx(sound,'remove')}}>Yeniden dene</button></div></div>}
export function Traffic({q,onAnswer,disabled,reveal,wrong}:Props){
 const walk=q.answer!=='Bekle',[selected,setSelected]=useState(''),[replay,setReplay]=useState(0),crossing=walk&&disabled&&(selected===q.answer||!!reveal),waiting=!walk&&disabled;
 const scene=walk?'Yaya ışığı yeşil. Araç durma çizgisinde durmuş.':'Yaya ışığı kırmızı. Yolda bir araç ilerliyor.',figure=walk?'#43604c':'#fff',still=walk?'#6b4a45':'#fff';
 return <div className="traffic-tool">
  <p className="traffic-status"><span className={`status-lamp ${walk?'go':'stop'}`} aria-hidden="true"/>Yaya ışığı: <b>{walk?'YEŞİL':'KIRMIZI'}</b><span>· {walk?'Araç durma çizgisinde bekliyor.':'Yolda araç ilerliyor.'}</span></p>
  <svg className="traffic-scene" viewBox="0 0 600 250" role="img" aria-label={`${scene} Bir çocuk yaya geçidinin başında, kaldırımda duruyor.${crossing?' Çocuk yaya geçidinden karşıya geçiyor.':''}`}>
   <rect width="600" height="30" fill="#cfe3bf"/><rect y="30" width="600" height="40" fill="#e6dcc8"/><rect y="70" width="600" height="120" fill="#6d7678"/><rect y="190" width="600" height="36" fill="#e6dcc8"/><rect y="226" width="600" height="24" fill="#b9d4a9"/>
   <path d="M0 130H318M412 130H600" stroke="#f3f0e3" strokeWidth="4" strokeDasharray="26 18"/>
   {[0,1,2,3,4,5].map(i=><rect key={i} x="330" y={78+i*18} width="70" height="10" rx="2" fill="#fdfcf7"/>)}
   <path d="M318 134V188" stroke="#fdfcf7" strokeWidth="5"/>
   <text x="16" y="56" className="scene-label">Kaldırım</text><text x="410" y="214" className="scene-label">← Yaya geçidi</text>
   <rect x="419" y="58" width="6" height="10" fill="#56605b"/><rect x="404" y="4" width="36" height="56" rx="8" fill="#2f3834"/>
   <circle cx="422" cy="18" r="11" fill={walk?'#4a3431':'#f0705f'}/><circle cx="422" cy="10.5" r="2" fill={still}/><path d="M422 13v8M419 16h6M422 21l-2 5M422 21l2 5" stroke={still} strokeWidth="2" strokeLinecap="round"/>
   <circle cx="422" cy="46" r="11" fill={walk?'#7fd36d':'#2f4a39'}/><circle cx="423" cy="38.5" r="2" fill={figure}/><path d="M422.5 41l-1 7M421.8 44l-3.5 2.5M421.8 44l3.5-1.5M421.5 48l-3 5M421.5 48l3 4.5" stroke={figure} strokeWidth="2" strokeLinecap="round"/>
   <g className={`walker ${crossing?'is-crossing':''}`}><path d="M358.5 36a6.5 6.5 0 0 1 13 0" fill="#6b4632"/><circle cx="365" cy="38" r="6.5" fill="#f2c7a5"/><path d="M365 45v13" stroke="#e0664f" strokeWidth="9" strokeLinecap="round"/><path d="M365 48l-8 7M365 48l8 7" stroke="#f2c7a5" strokeWidth="3.5" strokeLinecap="round"/><path d="M362 60l-3 8M368 60l3 8" stroke="#3d4f7a" strokeWidth="4.5" strokeLinecap="round"/></g>
   {waiting&&<text x="376" y="34" fontSize="22">✋</text>}
   <g key={replay} className={`car ${walk?'is-stopped':'is-driving'}`}><rect y="146" width="96" height="28" rx="10" fill="#3f7fc4"/><path d="M20 147l13-17h31l15 17z" fill="#3f7fc4"/><path d="M27 145l9-12h12v12zM52 145v-12h11l10 12z" fill="#d7ecf7"/><circle cx="24" cy="176" r="9.5" fill="#2b2f33"/><circle cx="74" cy="176" r="9.5" fill="#2b2f33"/><circle cx="24" cy="176" r="3.5" fill="#a3abb0"/><circle cx="74" cy="176" r="3.5" fill="#a3abb0"/><rect x="89" y="152" width="7" height="8" rx="2" fill="#ffe08a"/><rect y="152" width="5" height="8" rx="2" fill="#e5655a"/>{!walk&&<path d="M-30 153h18M-38 163h26M-28 173h16" stroke="#dfe4e6" strokeWidth="3.5" strokeLinecap="round"/>}</g>
  </svg>
  {!walk&&<button className="scene-replay" onClick={()=>setReplay(r=>r+1)}>▶ Sahneyi yeniden oynat</button>}
  <Choices q={q} picked={selected} wrong={wrong} disabled={disabled} letters onPick={o=>{setSelected(o);onAnswer(o,true)}}/>
 </div>;
}
export function WordMatch({q,onAnswer,disabled,wrong}:Props){const [selected,setSelected]=useState('');return <div><div className="visual-object" aria-hidden="true">{q.visual}</div><Choices q={q} picked={selected} wrong={wrong} disabled={disabled} lang="en" onPick={o=>{setSelected(o);onAnswer(o,true)}}/></div>}
