'use client';
import {useEffect,useRef,useState} from 'react';
import type {Question} from '@/lib/types';
import {sfx} from '@/lib/audio';
import Choices from './Choices';
import Picture,{Icon,many} from './Picture';
import {Art} from '../Illustration';
/** Ritimde 👏 vuruşu alkışlayan Piko ile gösterilir (dersin adı: Piko’nun ritmini yakala). */
const Clap=({size}:{size:number})=><Art name="piko-clap" size={size} className="clap-art"/>;
type Props={q:Question;onAnswer:(s:string,check?:boolean)=>void;disabled:boolean;sound:boolean;reveal?:boolean;wrong?:string[]};
/** Madeni paralar yazısız kil görsellerdir; değer yazısı üstüne HTML olarak basılır. 1 TL iki renklidir. */
const coinArt=(c:number)=>c===100?'/art/tool/coin-lira.webp':'/art/tool/coin-gold.webp';
export function Money({onAnswer,disabled,sound}:Props){const [coins,setCoins]=useState<number[]>([]);function change(arr:number[]){setCoins(arr);onAnswer(String(arr.reduce((a,b)=>a+b,0)))}return <div><div className="coin-tray">{[25,50,100].map(c=><button disabled={disabled||coins.length>=16} className={`coin coin-${c}`} key={c} onClick={()=>{change([...coins,c]);sfx(sound,'coin')}}><img src={coinArt(c)} alt="" draggable={false}/><span>{c===100?'1 TL':`${c} kr`}</span></button>)}</div><div className="piggy"><Art name="tool/piggy" size={120} className="piggy-art"/><div>{coins.map((c,i)=><button className="mini-coin" disabled={disabled} key={i} onClick={()=>{change(coins.filter((_,j)=>i!==j));sfx(sound,'remove')}}><img src={coinArt(c)} alt="" width={22} height={22} draggable={false}/>{c} kr ×</button>)}</div><output>Toplam: {coins.reduce((a,b)=>a+b,0)} kuruş</output></div></div>}
/** q.items: ["🍎|Elma","🍐|Armut"]; ilk satır çocuğun ayarladığı, ikinci satır q.start kadar hazır. */
export function Graph({q,onAnswer,disabled,sound}:Props){const [n,setN]=useState(0),[[ea,la],[eb,lb]]=(q.items??['🍎|Elma','🍐|Armut']).map(x=>x.split('|')),name=la.toLocaleLowerCase('tr-TR');return <div className="graph-tool"><p>Her simge = 1 kişi</p><div><b>{la}</b><span>{n?many(ea,n):'—'}</span></div><div><b>{lb}</b><span>{many(eb,q.start??2)}</span></div><div className="tool-actions"><button aria-label={`Bir ${name} simgesi çıkar`} disabled={disabled||n<=0} onClick={()=>{setN(n-1);onAnswer(String(n-1));sfx(sound,'remove')}}>− Bir <Icon e={ea}/></button><button aria-label={`Bir ${name} simgesi ekle`} disabled={disabled||n>=8} onClick={()=>{setN(n+1);onAnswer(String(n+1));sfx(sound,'place')}}>+ Bir <Icon e={ea}/></button></div></div>}
export function Measure({q,onAnswer,disabled,sound}:Props){const [show,setShow]=useState(false),[n,setN]=useState(5);return <div className="measure-tool"><div className="ruler-scene"><div className="pencil" role="img" aria-label="Kalem" style={{width:`calc(${q.value??5} * (100% - 12px) / 10)`}}><i/><b/><em/></div><div className={`ruler ${show?'':'hidden-ruler'}`}>{Array.from({length:11},(_,i)=><span key={i}>{i}</span>)}</div></div><p>Bu çizim bir modeldir; ekrandaki boyut gerçek santimetre değildir.</p><label>Tahminim / ölçümüm: {n} cm<input aria-label="Uzunluk" type="range" min="1" max="10" value={n} disabled={disabled} onChange={e=>{setN(Number(e.target.value));onAnswer(e.target.value);sfx(sound,'tick')}}/></label><div className="tool-actions"><button onClick={()=>{setShow(true);onAnswer(String(n));sfx(sound,'hop')}}>Cetveli göster ve karşılaştır</button></div></div>}
export function Rhythm({q,onAnswer,disabled,sound,wrong=[]}:Props){const [input,setInput]=useState<string[]>([]),[beat,setBeat]=useState(-1),[speed,setSpeed]=useState(600);const timers=useRef<ReturnType<typeof setTimeout>[]>([]);useEffect(()=>()=>timers.current.forEach(clearTimeout),[]);const play=()=>{timers.current.forEach(clearTimeout);q.items?.forEach((v,i)=>{timers.current.push(setTimeout(()=>{setBeat(i);if(v==='👏')sfx(sound,'clap')},i*speed))});timers.current.push(setTimeout(()=>setBeat(-1),(q.items?.length??4)*speed))};return <div className="rhythm-tool"><div className="beats">{q.items?.map((x,i)=><span className={beat===i?'active':''} key={i}>{x==='👏'?<Clap size={50}/>:x}<small>{x==='—'?'Sus':'Vur'}</small></span>)}</div><div className="tool-actions"><button onClick={play}>▶ Ritmi {sound?'dinle':'gör'}</button><label>Tempo <select value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={850}>Yavaş</option><option value={600}>Orta</option><option value={400}>Hızlı</option></select></label></div>{!sound&&<p className="muted">Ses kapalı. Işıkları izleyebilir veya üstten sesi açabilirsin.</p>}<div className={`beats input-beats ${disabled&&input.join('|')===q.answer?'is-correct':input.length&&wrong.includes(input.join('|'))?'is-wrong':''}`}>{Array.from({length:4},(_,i)=><span key={i}>{input[i]==='👏'?<Clap size={44}/>:input[i]??'?'}</span>)}</div><div className="tool-actions">{['👏','—'].map(x=><button disabled={disabled||input.length>=4} key={x} onClick={()=>{const a=[...input,x];setInput(a);if(x==='👏')sfx(sound,'clap');onAnswer(a.join('|'),a.length===(q.items?.length??4))}}>{x==='👏'?<><Clap size={30}/> Vuruş</>:'— Sus'}</button>)}<button disabled={disabled||!input.length} onClick={()=>{setInput([]);onAnswer('');sfx(sound,'remove')}}>Yeniden dene</button></div></div>}
/** Kil sokak sahnesi (public/art/tool/street, 1536×768 kırpım koordinatları). Yaya ışığı görseli boş lambalıdır; duran/yürüyen simgesi ve yanan lambanın parıltısı burada çizilir. Kırmızıda araba bir kez geçer ve yeniden oynatılabilir, yeşilde durma çizgisinde bekler; Piko yalnız doğru cevap onaylanınca karşıya geçer. */
const standing=<><circle cy="-7.5" r="2.2" fill="currentColor" stroke="none"/><path d="M0-5v8M-3-2h6M0 3l-2 5M0 3l2 5"/></>,walking=<><circle cx="1" cy="-7.5" r="2.2" fill="currentColor" stroke="none"/><path d="M.5-5l-1 7M-.2-2l-3.5 2.5M-.2-2l3.5-1.5M-.5 2l-3 5M-.5 2l3 4.5"/></>;
function Lamp({y,on,color,figure}:{y:number;on:boolean;color:string;figure:React.ReactNode}){return <g transform={`translate(1270 ${y})`} className={on?'lamp is-on':'lamp'}>{on&&<circle r="46" fill={color} opacity=".32"/>}<circle r="27" fill={on?color:'#262b29'}/><g transform="scale(2.4)" color={on?'#fff':color} stroke="currentColor" strokeOpacity={on?1:.4} fillOpacity={on?1:.4} strokeWidth="2" strokeLinecap="round" fill="none">{figure}</g></g>}
export function Traffic({q,onAnswer,disabled,reveal,wrong}:Props){
 const walk=q.answer!=='Bekle',[selected,setSelected]=useState(''),[replay,setReplay]=useState(0),crossing=walk&&disabled&&(selected===q.answer||!!reveal);
 const scene=walk?'Yaya ışığı yeşil. Araba durma çizgisinde durmuş.':'Yaya ışığı kırmızı. Yolda bir araba ilerliyor.';
 return <div className="traffic-tool">
  <p className="traffic-status"><span className={`status-lamp ${walk?'go':'stop'}`} aria-hidden="true"/>Yaya ışığı: <b>{walk?'YEŞİL':'KIRMIZI'}</b><span>· {walk?'Araba durma çizgisinde bekliyor.':'Yolda araba ilerliyor.'}</span></p>
  <svg className="traffic-scene" viewBox="0 0 1536 768" role="img" aria-label={`${scene} Piko yaya geçidinin başında, kaldırımda bekliyor.${crossing?' Piko yaya geçidinden karşıya geçiyor.':''}`}>
   <image href="/art/tool/street.webp" width="1536" height="768" preserveAspectRatio="none"/>
   <text x="36" y="262" className="scene-label">Kaldırım</text><text x="1204" y="684" className="scene-label">← Yaya geçidi</text>
   <image href="/art/tool/ped-light.webp" x="1231" y="22" width="79" height="250"/>
   <Lamp y={74} on={!walk} color="#f0705f" figure={standing}/><Lamp y={137} on={walk} color="#7fd36d" figure={walking}/>
   <g className={`walker ${crossing?'is-crossing':''}`}><image href={crossing?'/art/piko-walk-sm.webp':'/art/piko-wait-sm.webp'} x="955" y="112" width="156" height="156"/></g>
   <g key={replay} className={`car ${walk?'is-stopped':'is-driving'}`}>{!walk&&<path d="M-80 452h54M-104 492h78M-76 532h50" stroke="#fffdf5" strokeOpacity=".85" strokeWidth="11" strokeLinecap="round"/>}<image href="/art/tool/car.webp" y="398" width="297" height="190"/></g>
  </svg>
  {!walk&&<button className="scene-replay" onClick={()=>setReplay(r=>r+1)}>▶ Sahneyi yeniden oynat</button>}
  <Choices q={q} picked={selected} wrong={wrong} disabled={disabled} letters onPick={o=>{setSelected(o);onAnswer(o,true)}}/>
 </div>;
}
export function WordMatch({q,onAnswer,disabled,wrong}:Props){const [selected,setSelected]=useState('');return <div>{q.visual&&<Picture visual={q.visual}/>}<Choices q={q} picked={selected} wrong={wrong} disabled={disabled} lang="en" onPick={o=>{setSelected(o);onAnswer(o,true)}}/></div>}
