'use client';
import {useEffect,useRef,useState} from 'react';
import type {Question} from '@/lib/types';
import {tone} from '@/lib/audio';
type Props={q:Question;onAnswer:(s:string)=>void;disabled:boolean;sound:boolean;reveal?:boolean};
export function Money({q,onAnswer,disabled}:Props){const [coins,setCoins]=useState<number[]>([]);function change(arr:number[]){setCoins(arr);onAnswer(String(arr.reduce((a,b)=>a+b,0)))}return <div><div className="coin-tray">{[25,50,100].map(c=><button disabled={disabled||coins.length>=16} className="coin" key={c} onClick={()=>change([...coins,c])}>{c===100?'1 TL':`${c} kr`}</button>)}</div><div className="piggy"><span>🐷</span><div>{coins.map((c,i)=><button disabled={disabled} key={i} onClick={()=>change(coins.filter((_,j)=>i!==j))}>{c} kr ×</button>)}</div><output>Toplam: {coins.reduce((a,b)=>a+b,0)} kuruş</output></div></div>}
export function Graph({q,onAnswer,disabled}:Props){const [n,setN]=useState(0);return <div className="graph-tool"><p>Her meyve = 1 kişi</p><div><b>Elma</b><span>{'🍎'.repeat(n)||'—'}</span></div><div><b>Armut</b><span>{'🍐'.repeat(q.start??2)}</span></div><div className="tool-actions"><button disabled={disabled||n<=0} onClick={()=>{setN(n-1);onAnswer(String(n-1))}}>− Bir elma</button><button disabled={disabled||n>=8} onClick={()=>{setN(n+1);onAnswer(String(n+1))}}>+ Bir elma</button></div></div>}
export function Measure({q,onAnswer,disabled}:Props){const [show,setShow]=useState(false),[n,setN]=useState(5);return <div className="measure-tool"><div className="ruler-scene"><div className="pencil" style={{width:`${(q.value??5)*10}%`}}>✎</div><div className={`ruler ${show?'':'hidden-ruler'}`}>{Array.from({length:11},(_,i)=><span key={i}>{i}</span>)}</div></div><p>Bu çizim bir modeldir; ekrandaki boyut gerçek santimetre değildir.</p><label>Tahminim / ölçümüm: {n} cm<input aria-label="Uzunluk" type="range" min="1" max="10" value={n} disabled={disabled} onChange={e=>{setN(Number(e.target.value));onAnswer(e.target.value)}}/></label><div className="tool-actions"><button onClick={()=>{setShow(true);onAnswer(String(n))}}>Cetveli göster ve karşılaştır</button></div></div>}
export function Rhythm({q,onAnswer,disabled,sound}:Props){const [input,setInput]=useState<string[]>([]),[beat,setBeat]=useState(-1),[speed,setSpeed]=useState(600);const timers=useRef<ReturnType<typeof setTimeout>[]>([]);useEffect(()=>()=>timers.current.forEach(clearTimeout),[]);const play=()=>{timers.current.forEach(clearTimeout);q.items?.forEach((v,i)=>{timers.current.push(setTimeout(()=>{setBeat(i);if(v==='👏')tone(sound,440,.18)},i*speed))});timers.current.push(setTimeout(()=>setBeat(-1),(q.items?.length??4)*speed))};return <div className="rhythm-tool"><div className="beats">{q.items?.map((x,i)=><span className={beat===i?'active':''} key={i}>{x}<small>{x==='—'?'Sus':'Vur'}</small></span>)}</div><div className="tool-actions"><button onClick={play}>▶ Ritmi {sound?'dinle':'gör'}</button><label>Tempo <select value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={850}>Yavaş</option><option value={600}>Orta</option><option value={400}>Hızlı</option></select></label></div>{!sound&&<p className="muted">Ses kapalı. Işıkları izleyebilir veya üstten sesi açabilirsin.</p>}<div className="beats input-beats">{Array.from({length:4},(_,i)=><span key={i}>{input[i]??'?'}</span>)}</div><div className="tool-actions">{['👏','—'].map(x=><button disabled={disabled||input.length>=4} key={x} onClick={()=>{const a=[...input,x];setInput(a);onAnswer(a.join('|'));if(x==='👏')tone(sound,440)}}>{x==='👏'?'👏 Vuruş':'— Sus'}</button>)}<button disabled={disabled} onClick={()=>{setInput([]);onAnswer('')}}>Yeniden dene</button></div></div>}
export function Traffic({q,onAnswer,disabled}:Props){const safe=q.answer!=='Bekle';const [crossed,setCrossed]=useState(false);return <div className="traffic-tool"><div className="road"><div className={`traffic-light ${safe?'green-light':'red-light'}`}><span/><span/><b>{safe?'YEŞİL':'KIRMIZI'}</b></div><div className="crosswalk"/><div className={`car ${safe?'stopped':''}`}>🚙</div><div className={`pedestrian ${crossed?'crossed':''}`}>🚶</div></div><div className="options">{q.options?.map(o=><button disabled={disabled} key={o} onClick={()=>{onAnswer(o);if(safe&&o===q.answer)setCrossed(true)}}>{o}</button>)}</div></div>}
export function WordMatch({q,onAnswer,disabled}:Props){return <div><div className="visual-object" aria-hidden="true">{q.visual}</div><div className="options">{q.options?.map(o=><button disabled={disabled} key={o} onClick={()=>onAnswer(o)} lang="en">{o}</button>)}</div></div>}
