import {Art} from '../Illustration';
/** Sayma simgeleri: emoji → [public/art/i/ altındaki kil görsel, okunuşu]. Listede olmayan emoji olduğu gibi yazılır. */
export const icons:Record<string,[string,string]>={'🍒':['cherry','kiraz'],'🍓':['strawberry','çilek'],'🌼':['daisy','papatya'],'⭐':['star','yıldız'],'🐞':['ladybug','uğur böceği'],'🎈':['balloon','balon'],'🐟':['fish','balık'],'🍪':['cookie','kurabiye'],'🍎':['apple','elma'],'🌷':['tulip','lale'],'🖍️':['crayon','boya kalemi'],'✏️':['pencil','kalem'],'🥚':['egg','yumurta'],'📚':['book','kitap'],'🌻':['sunflower','ayçiçeği'],'🥛':['glass','bardak'],'☕':['cup','fincan'],'🍵':['tea-glass','çay bardağı'],'🍐':['pear','armut'],'🐱':['cat','kedi'],'🐶':['dog','köpek'],'☀️':['sun','güneş'],'❄️':['snowflake','kar tanesi'],'🌹':['rose','gül'],'🚂':['train','tren'],'✈️':['plane','uçak'],'⚽':['ball','top'],'🪁':['kite','uçurtma'],'🌸':['blossom','pembe çiçek'],'🍀':['clover','yonca'],'🔺':['triangle','kırmızı üçgen'],'🔵':['circle','mavi daire'],'🟩':['square-green','yeşil kare'],'🟥':['square-red','kırmızı kare'],'🟨':['square-yellow','sarı kare'],'🟦':['square-blue','mavi kare'],'🐝':['bee','arı'],'🌙':['moon','ay'],'🦋':['butterfly','kelebek'],'🍊':['orange','portakal']};
const word=(e:string)=>icons[e]?.[1]??e;
export function Icon({e}:{e:string}){const icon=icons[e];return icon?<img className="count-icon" src={`/art/i/${icon[0]}.webp`} width={36} height={36} alt="" draggable={false}/>:<>{e}</>}
export const many=(e:string,n:number)=>Array.from({length:n},(_,i)=><Icon key={i} e={e}/>);
/** Metindeki (örüntü dizisi, seçenek) simge emojilerini kil simgeyle yazar; ekran okuyucu simgenin adını okur. */
export function IconText({text}:{text:string}){return <>{text.split(/(\p{Extended_Pictographic}\uFE0F?)/u).map((part,i)=>icons[part]?<img key={i} className="inline-icon" src={`/art/i/${icons[part][0]}.webp`} width={36} height={36} alt={icons[part][1]} draggable={false}/>:part)}</>}
/** Soru görseli: "art:hb/friends-talk" kil sahne, "count:🍒:23" beşli gruplar ve kalanlar, "groups:🍓:3x4" dolu tabaklar, "share:🍓:12:3" paylaştırılacak çilekler ve boş tabaklar, "pile:🍓:12" yığın, "chart:🍎:Elma:4:🍐:Armut:2" iki satırlık resim grafiği; diğerleri düz metin. */
export default function Picture({visual}:{visual:string}){
 const [kind,item,a,b]=visual.split(':');
 if(kind==='art')return <div className="visual-object picture-art"><Art name={item} size={144}/></div>;
 if(kind==='count'){const n=Number(a),full=Math.floor(n/5),rest=n%5;return <div className="visual-object picture-set" role="img" aria-label={`${full} grup, her grupta 5 ${word(item)}${rest?`, ayrıca ${rest} ${word(item)}`:''}`}>{Array.from({length:full},(_,i)=><span className="picture-group" key={i}>{many(item,5)}</span>)}{rest>0&&<span className="picture-group">{many(item,rest)}</span>}</div>}
 if(kind==='chart'){const [,,,,eb,lb,nb]=visual.split(':'),rows=[[item,a,b],[eb,lb,nb]];return <div className="graph-tool chart-picture" role="img" aria-label={`Resim grafiği: ${rows.map(([,l,n])=>`${l} ${n} kişi`).join(', ')}. Her simge bir kişi.`}><p>Her simge = 1 kişi</p>{rows.map(([e,l,n])=><div key={l}><b>{l}</b><span>{many(e,Number(n))}</span></div>)}</div>}
 if(kind==='groups'){const [plates,each]=a.split('x').map(Number);return <div className="visual-object picture-set" role="img" aria-label={`${plates} grup, her grupta ${each} ${word(item)}`}>{Array.from({length:plates},(_,i)=><span className="plate" key={i}>{many(item,each)}</span>)}</div>}
 if(kind==='pile'){const total=Number(a);return <div className="visual-object picture-set" role="img" aria-label={`${total} ${word(item)}`}><span className="picture-pile">{many(item,total)}</span></div>}
 if(kind==='share'){const total=Number(a),plates=Number(b);return <div className="visual-object picture-set" role="img" aria-label={`${total} ${word(item)} ve ${plates} boş tabak`}><span className="picture-pile">{many(item,total)}</span><span className="share-arrow" aria-hidden="true">→</span>{Array.from({length:plates},(_,i)=><span className="plate is-empty" key={i}>?</span>)}</div>}
 return <div className={`visual-object ${visual.length>20?'objects':''}`} aria-label="Sorunun görseli">{visual}</div>;
}
