'use client';
import '@/app/activities.css';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {ArrowLeft,ArrowRight,Lightbulb,Volume2,Check,RotateCcw} from 'lucide-react';
import type {Lesson,Progress,Question} from '@/lib/types';
import {makeQuestion,nextQuestion,previewQuestion,questionKeys} from '@/lib/questions';
import {newSeed} from '@/lib/random';
import {checkAnswer,completeLesson,difficulty,recordAttempt} from '@/lib/progress';
import {sfx,speak,stopSpeech} from '@/lib/audio';
import Activity,{instant} from './activities/Activity';
import {Art} from './Illustration';
import {subjects} from '@/content/subjects';
import {BundlingDemo} from './activities/BaseTenBlocks';
import ClockTool from './activities/ClockTool';
import GeometryLab from './activities/GeometryLab';
import curriculum from '@/curriculum/grade-2.json';
const stages=['Öğren','Birlikte yapalım','Sen dene','Mini oyun','Mini test','Sonuç'];
const confetti=Array.from({length:22},(_,i)=><i key={i} style={{'--x':`${(i*37+7)%94+3}%`,'--d':`${(i*53%22)*.06}s`,'--t':`${2.2+(i*29%10)*.13}s`,'--dx':`${(i*41%21-10)*7}px`,'--h':i*47%360} as CSSProperties}/>);
export default function LessonPlayer({lesson,progress,update}:{lesson:Lesson;progress:Progress;update:(p:Progress)=>void}){
 const [previewAnswer,setPreviewAnswer]=useState('');
 const [stage,setStage]=useState(0),[index,setIndex]=useState(0),[seed,setSeed]=useState(newSeed),[q,setQ]=useState<Question|null>(null),[answer,setAnswer]=useState(''),[tries,setTries]=useState(0),[hint,setHint]=useState(0),[status,setStatus]=useState<'idle'|'retry'|'correct'|'revealed'>('idle'),[quizCorrect,setQuizCorrect]=useState(0),[results,setResults]=useState<{skill:string;correct:boolean;observed:boolean}[]>([]),[voiceMessage,setVoiceMessage]=useState(''),[learnIndex,setLearnIndex]=useState(0),[wrong,setWrong]=useState<string[]>([]);const heading=useRef<HTMLHeadingElement>(null),actions=useRef<HTMLDivElement>(null),seen=useRef<string[]>([]),preview=previewQuestion(lesson);
 useEffect(()=>()=>stopSpeech(),[]);
 useEffect(()=>{heading.current?.focus()},[stage,index]);
 useEffect(()=>{if(status==='idle')return;if(status==='correct'||status==='revealed')actions.current?.querySelector<HTMLElement>('.primary')?.focus({preventScroll:true});actions.current?.scrollIntoView({block:'nearest',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})},[status,tries]);
 /** Tur ilk soruyla başlar; turda (ve öğren ekranındaki keşifte) çıkan soru bir daha sorulmaz. */
 function load(i:number,s:number){stopSpeech();setIndex(i);setStage(s);if(i===0)seen.current=preview?questionKeys(preview):[];const next=nextQuestion(lesson,i,s===1?1:difficulty(progress.skills[lesson.outcomes[0]]),seed,seen.current);seen.current.push(...questionKeys(next));setQ(next);setAnswer('');setTries(0);setHint(s===1?1:0);setStatus('idle');setVoiceMessage('');setWrong([])}
 function read(text:string,lang='tr-TR'){if(!speak(text,lang))setVoiceMessage(lang==='tr-TR'?'Bu cihazda çevrim dışı Türkçe ses yok. Metni okuyabilir veya bir yetişkinle dinleyebilirsin.':'Bu cihazda çevrim dışı İngilizce ses yok. Kelime kartlarıyla devam edebilirsin.')}
 function submit(value=answer){if(!q||!value||status==='correct'||status==='revealed')return;const correct=checkAnswer(value,q.answer,q.acceptedAnswers),next=tries+1;setTries(next);
  if(next===1){const at=new Date().toISOString();update(recordAttempt(progress,{id:q.id,lessonId:lesson.id,skill:q.skill,correct,assisted:hint>0||stage===1,selfReport:!!q.selfReport,at}));}
  if(correct){setStatus('correct');sfx(progress.sound,'correct');if(stage===4){const independent=tries===0&&hint===0&&!q.selfReport;setQuizCorrect(c=>c+(independent?1:0));setResults(r=>[...r,{skill:q.skill,correct:independent,observed:!!q.selfReport}])}}
  else{setWrong(w=>[...w,value]);if(next>=3){setStatus('revealed');sfx(progress.sound,'reveal');if(stage===4)setResults(r=>[...r,{skill:q.skill,correct:false,observed:!!q.selfReport}])}else{setStatus('retry');setHint(Math.min(2,next));sfx(progress.sound,'wrong')}}
 }
 /** Tek dokunuşluk yanıtlar (check) seçildiği anda kontrol edilir. */
 function choose(value:string,check=false){setAnswer(value);if(check)submit(value)}
 function next(){if(stage===1)load(1,2);else if(stage===2)load(2,3);else if(stage===3)load(3,4);else if(stage===4&&index<7)load(index+1,4);else{update(completeLesson(progress,lesson.id,quizCorrect,5));setStage(5);sfx(progress.sound,'finish')}}
 const color=subjects.find(s=>s.id===lesson.subject)?.color??'green',mastered=Object.values(progress.skills).filter(s=>s.score>=70).length,previewCorrect=!!preview&&checkAnswer(previewAnswer,preview.answer);
 return <section className="lesson-page"><a href={`#subject/${lesson.subject}`} className="back"><ArrowLeft size={18}/> Konulara dön</a><div className="lesson-heading"><span className={`lesson-icon ${color}`}>{lesson.icon}</span><div><p className="eyebrow">{lesson.theme}</p><h1>{lesson.title}</h1></div></div><ol className="learning-path" aria-label="Öğrenme adımları" style={{'--step':stage} as CSSProperties}>{stages.map((s,i)=><li key={s} className={i===stage?'current':i<stage?'passed':''} aria-current={i===stage?'step':undefined}><span>{i<stage?<Check size={15}/>:i+1}</span><small>{s}</small></li>)}</ol><div className="lesson-card"><div className="stage-title"><h2 tabIndex={-1} ref={heading}>{stages[stage]} {stage===4&&<small>· {index-2} / 5</small>}</h2>{stage<5&&<button className="icon-button" aria-label="Yönergeyi sesli oku" onClick={()=>read(stage===0?lesson.learn[learnIndex]:q?.instruction??'')}><Volume2 size={22}/></button>}</div>{voiceMessage&&<p role="status" className="notice">{voiceMessage}</p>}
 {stage===0&&<><div className="learn-scene"><Art name="piko-wave" size={150} className="learn-piko" sizes="(max-width:560px) 104px,156px" eager/><div className="learn-bubble" key={learnIndex}><p>{lesson.learn[learnIndex]}</p><span className="learn-dots">{lesson.learn.map((_,i)=><i key={i} className={i===learnIndex?"on":""}/>)}<small>{learnIndex+1} / {lesson.learn.length}</small></span></div></div>{lesson.vocabulary&&<div className="vocabulary">{lesson.vocabulary.map(v=><button key={v.word} onClick={()=>read(v.word,'en-GB')}><span>{v.picture}</span><b lang="en">{v.word}</b><small>{v.meaning}</small><Volume2 size={16}/></button>)}</div>}{lesson.kind==='baseTenBlocks'&&<BundlingDemo/>}{lesson.kind==='clock'&&<ClockTool q={makeQuestion(lesson,0,1,24)} onAnswer={()=>{}} disabled={false} sound={progress.sound} explore/>} {preview&&<div className="learn-manipulative"><p><b>{preview.instruction}</b></p><GeometryLab q={preview} onAnswer={v=>{setPreviewAnswer(v);const right=checkAnswer(v,preview.answer);if(right||v&&preview.options)sfx(progress.sound,right?'correct':'wrong')}} disabled={false} sound={progress.sound}/>{previewAnswer&&(previewCorrect||preview.options)&&<p role="status" className="notice discovery-feedback">{previewCorrect?`Evet! ${preview.explanation}`:`Bir daha inceleyelim. ${preview.hints[0]}`}</p>}</div>}<div className="stage-actions">{learnIndex>0&&<button onClick={()=>setLearnIndex(learnIndex-1)}>Önceki</button>}{learnIndex<lesson.learn.length-1?<button className="primary" onClick={()=>setLearnIndex(learnIndex+1)}>Devam <ArrowRight size={18}/></button>:<button className="primary" onClick={()=>load(0,1)}>Birlikte yapalım <ArrowRight size={18}/></button>}</div></>}
 {stage>0&&stage<5&&q&&<><p className="question-instruction">{q.instruction}</p>{lesson.story&&<details className="story-box" open={stage===1}><summary>Hikâyeyi hatırla 📖</summary><p>{lesson.story}</p><button onClick={()=>read(lesson.story!)}><Volume2 size={18}/> Hikâyeyi dinle</button></details>}<Activity key={q.id} q={q} onAnswer={choose} disabled={status==='correct'||status==='revealed'} sound={progress.sound} reveal={status==='revealed'} wrong={wrong}/>{q.selfReport&&<p className="self-report-note">Bu bir keşif görevi. Bitirdiğini sen söylersin; otomatik not verilmez.</p>}<div className={`feedback ${status}`} aria-live="polite">{status==='correct'?<><Art name="piko-cheer" size={72} className="feedback-art"/><div><strong>{q.selfReport?'Keşfini tamamladın!':'Evet, buldun!'}</strong><p>{q.explanation}</p></div></>:status==='revealed'?<><Art name="piko-think" size={72} className="feedback-art"/><div><strong>Birlikte bakalım.</strong><p>{q.explanation}</p><p>Çözüm: {q.answer==='done'?'Görevini kendi hızında tamamla.':q.answer.split('|').join(' → ')}</p></div></>:hint>0?<><span className="hint-icon"><Lightbulb size={24}/></span><div><strong>{status==='retry'?'Bir daha düşünelim.':'Küçük bir ipucu'}</strong><p>{q.hints[Math.min(hint-1,q.hints.length-1)]}</p></div></>:null}</div><div className="stage-actions" ref={actions}>{status==='correct'||status==='revealed'?<button className="primary" onClick={next}>{stage===4&&index===7?'Keşfimi tamamla':'Devam edelim'} <ArrowRight size={18}/></button>:<><button onClick={()=>setHint(Math.min(2,hint+1))}><Lightbulb size={18}/> İpucu</button>{!instant(q)&&<button className="primary" disabled={!answer||wrong.includes(answer)} onClick={()=>submit()}>{q.selfReport?'Görevimi tamamladım':'Kontrol et'} <Check size={18}/></button>}</>}</div></>}
 {stage===5&&<div className="result"><div className="confetti" aria-hidden="true">{confetti}</div><div className="result-sun"><Art name="piko-cheer" size={190} eager/></div><p className="eyebrow">BİR KEŞİF DAHA TAMAMLANDI</p><h2>Emeğine sağlık, Lara!</h2><p>{lesson.title} yolculuğunu tamamladın.</p>{results.length>0&&results.every(x=>x.observed)?<p>Keşif görevlerini tamamladın. Çalışmanı bir yetişkinle paylaşabilirsin; bu görevlerde otomatik not verilmez.</p>:results.some(x=>x.correct)?<p>Mini testte {quizCorrect} soruyu ilk denemede, ipucusuz çözdün.</p>:<p>Birlikte denemek ve yeni şeyler keşfetmek de öğrenmenin bir parçası.</p>}<div className="skill-feedback">{[...new Set(results.map(x=>x.skill))].map(skill=>{const correct=results.filter(r=>r.skill===skill&&r.correct).length;const skillResults=results.filter(r=>r.skill===skill);const count=skillResults.filter(r=>!r.observed).length;const name=curriculum.find(c=>c.learningOutcomeCode===skill)?.learningOutcome??lesson.title;return <p key={skill}>{count===0?'🌼 Keşfini tamamladın.':correct/count>=.7?'⭐ Güzel ilerledin.':'🌱 Biraz daha pratik yapabiliriz.'} {name}</p>})}</div><p className="muted">{mastered>0?'Öğrendiklerin küçük adımlarla büyüyor.':'Her yeni deneme, yeni bir adım.'} İlerlemen bu cihazda saklanır.</p><div className="stage-actions"><a className="primary" href="#home">Öğrenme dünyama dön <ArrowRight size={18}/></a><button onClick={()=>{setSeed(newSeed());setQuizCorrect(0);setResults([]);setPreviewAnswer('');setLearnIndex(0);setStage(0)}}><RotateCcw size={18}/> Yeniden keşfet</button></div></div>}
 </div><p className="lesson-foot">Acele etmen gerekmiyor. İstersen ara verip yeniden başlayabilirsin. 🌿</p></section>
}
