'use client';
import {useState} from 'react';
import {Download,Upload,LockKeyhole,ArrowLeft,ExternalLink,ShieldCheck} from 'lucide-react';
import type {Progress} from '@/lib/types';
import {exportProgress,parseBackup,level} from '@/lib/progress';
import {subjects} from '@/content/subjects';
import {lessons} from '@/content';
import curriculum from '@/curriculum/grade-2.json';
const PIN_KEY='lara-parent-pin-v1';
async function hash(pin:string,salt:string){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(`${salt}:${pin}`)))].map(x=>x.toString(16).padStart(2,'0')).join('')}
export default function Parents({progress,update}:{progress:Progress;update:(p:Progress)=>void}){
 const [pin,setPin]=useState(''),[confirmPin,setConfirmPin]=useState(''),[unlocked,setUnlocked]=useState(false),[stored,setStored]=useState(()=>{try{return localStorage.getItem(PIN_KEY)}catch{return null}}),[error,setError]=useState(''),[tab,setTab]=useState('progress'),[pending,setPending]=useState<Progress|null>(null),[failures,setFailures]=useState(0),[blockedUntil,setBlockedUntil]=useState(0);
 async function unlock(e:React.FormEvent){e.preventDefault();setError('');if(Date.now()<blockedUntil){setError('Biraz bekleyip tekrar deneyin.');return}if(!/^\d{4,8}$/.test(pin)){setError('4–8 rakamdan oluşan bir PIN girin.');return}try{if(stored){const {salt,digest}=JSON.parse(stored);if(await hash(pin,salt)!==digest){setFailures(f=>f+1);if(failures>=4)setBlockedUntil(Date.now()+30000);setError('PIN eşleşmedi. Yeniden deneyin.');return}}else{if(pin!==confirmPin){setError('İki PIN aynı olmalı.');return}const salt=crypto.randomUUID(),value=JSON.stringify({salt,digest:await hash(pin,salt)});localStorage.setItem(PIN_KEY,value);setStored(value)}setUnlocked(true);setPin('');setConfirmPin('')}catch{setError('PIN bu tarayıcıya kaydedilemedi. Depolama iznini kontrol edin.')}}
 function backup(){const url=URL.createObjectURL(new Blob([exportProgress(progress)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`lara-ilerleme-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 async function restore(file?:File){if(!file)return;try{if(file.size>2500000)throw new Error('Yedek dosyası çok büyük.');setPending(parseBackup(await file.text()));setError('')}catch(e){setError(e instanceof Error?e.message:'Dosya okunamadı.')}}
 if(!unlocked)return <section className="parent-gate"><a className="back" href="#home"><ArrowLeft size={18}/> Lara’nın dünyasına dön</a><div className="gate-card"><LockKeyhole size={38}/><h1>Ebeveyn Alanı</h1><p>{stored?'Devam etmek için ebeveyn PIN’inizi girin.':'İlk kullanımda ebeveyn olarak bu cihaz için bir PIN oluşturun.'}</p><form onSubmit={unlock}><label>{stored?'Ebeveyn PIN’i':'Yeni PIN'}<input autoComplete={stored?'current-password':'new-password'} type="password" inputMode="numeric" pattern="[0-9]{4,8}" maxLength={8} value={pin} onChange={e=>setPin(e.target.value)} required/></label>{!stored&&<label>PIN’i tekrar girin<input type="password" autoComplete="new-password" inputMode="numeric" maxLength={8} value={confirmPin} onChange={e=>setConfirmPin(e.target.value)} required/></label>}<button className="primary" type="submit">{stored?'Alanı aç':'PIN oluştur ve aç'}</button></form>{error&&<p role="alert">{error}</p>}<p className="fine-print">Bu PIN yanlışlıkla girişi önleyen bir cihaz kilididir. Hesap veya sunucu kimlik doğrulaması değildir. PIN unutulursa tarayıcı geliştirici araçlarında yalnızca <code>{PIN_KEY}</code> kaydı silinebilir; ilerleme kaydı korunmalıdır.</p></div></section>;
 const assessed=progress.attempts.filter(a=>!a.selfReport),correct=assessed.filter(a=>a.correct&&!a.assisted).length;
 return <section><div className="section-title"><div><p className="eyebrow">KÜÇÜK ADIMLARI BİRLİKTE İZLEYELİM</p><h1>Ebeveyn Alanı</h1></div><button onClick={()=>setUnlocked(false)}><LockKeyhole size={18}/> Kilitle</button></div><div className="tabs" role="group" aria-label="Ebeveyn bölümleri">{[['progress','Gelişim'],['sources','Müfredat Kaynakları'],['backup','Yedek ve gizlilik']].map(([key,label])=><button key={key} className={tab===key?'active':''} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</div>{tab==='progress'&&<><div className="stats-grid"><div><strong>{Object.keys(progress.completed).length}</strong><span>Tamamlanan konu</span></div><div><strong>{progress.attempts.length}</strong><span>Kaydedilen etkinlik</span></div><div><strong>{correct} / {assessed.length}</strong><span>İlk denemede, ipucusuz</span></div><div><strong>{progress.attempts.length?new Date(progress.attempts.at(-1)!.at).toLocaleDateString('tr-TR'):'Henüz yok'}</strong><span>Son çalışma</span></div></div><p className="notice">Bir konuyu tamamlamak, tüm öğrenme çıktısını kazanmak anlamına gelmez. Aşağıdaki oran, kayıtlı çıktılar içinde en az 5 bağımsız değerlendirmesi ve en az 70 yeterlilik puanı olanları gösterir. Açık uçlu anlatım, sanat ve hareket görevleri öz bildirimdir; otomatik yeterlilik sayılmaz.</p><div className="parent-subjects">{subjects.map(s=>{const outcomes=curriculum.filter(o=>o.subject===s.id),auto=outcomes.filter(o=>o.assessment==='automatic');const earned=auto.filter(o=>(progress.skills[o.learningOutcomeCode]?.score??0)>=70&&(progress.skills[o.learningOutcomeCode]?.attempts??0)>=5).length;const percent=outcomes.length?Math.round(earned/outcomes.length*100):0;const active=lessons.filter(l=>l.subject===s.id&&progress.completed[l.id]).length;return <div className="parent-subject" key={s.id}><div><b>{s.icon} {s.name}</b><span>%{percent}</span></div><progress value={percent} max={100} aria-label={`${s.name} kayıtlı çıktı ilerlemesi`}/><small>{earned} / {outcomes.length} kayıtlı çıktı · {active} konu tamamlandı</small><small>Uygulama kapsamı: {lessons.filter(l=>l.subject===s.id).length} ders. Tüm süreç bileşenlerinin değerlendirmesi değildir.</small></div>})}</div><h2>Beceri gözlemleri</h2><div className="skill-list">{Object.entries(progress.skills).length===0?<p>İlk keşiften sonra beceriler burada görünür.</p>:Object.entries(progress.skills).map(([code,s])=><div key={code}><div><b>{curriculum.find(c=>c.learningOutcomeCode===code)?.learningOutcome??code}</b><small>{code} · {s.attempts} değerlendirme</small></div><span className="pill">{s.attempts?level(s.score):'Yetişkin gözlemi'}</span></div>)}</div><h2>Yakın zamanda çalışılanlar</h2><ul className="history-list">{Object.entries(progress.completed).sort((a,b)=>b[1].at.localeCompare(a[1].at)).slice(0,12).map(([id,v])=><li key={id}>{lessons.find(l=>l.id===id)?.title??id}<span>{new Date(v.at).toLocaleDateString('tr-TR')}</span></li>)}</ul></>}
 {tab==='sources'&&<><p>2. sınıf · 2026–2027. Kaynak kontrolü: 24 Eylül 2026. Öğrenme çıktıları kısa özgün özetlerle listelenir. MEB bağlantıları ebeveyn tarafından yeni sekmede açılır.</p><p className="notice">Yedi dersin 39 tema / öğrenme alanı doğrudan MEB portalından kontrol edilmiştir. 241 farklı çıktı kayıtlıdır: Matematik 25, Türkçe 20, Hayat Bilgisi 23, İngilizce 138, Görsel Sanatlar 11, Müzik 12, Beden Eğitimi ve Oyun 12. Kayıtlı müfredat ile etkinlik kapsamı ayrı izlenir; her çıktının tüm süreç bileşenleri otomatik ölçülmez.</p>{subjects.map(s=><article className="source-card" key={s.id}><h2>{s.icon} {s.name}</h2><p>2. sınıf · 2026–2027 · MEB Türkiye Yüzyılı Maarif Modeli</p><a href={`https://tymm.meb.gov.tr/ogretim-programlari/${s.slug}/3`} target="_blank" rel="noreferrer">Resmî program ve temalar <ExternalLink size={16}/></a><p className="fine-print">Son kontrol: 24.09.2026 · {s.themes.length} tema / öğrenme alanı</p><details><summary>Temalar ve kayıtlı öğrenme çıktıları</summary><p>{s.themes.join(' · ')}</p>{curriculum.filter(o=>o.subject===s.id).map(o=><div className="outcome-row" key={o.learningOutcomeCode}><a target="_blank" rel="noreferrer" href={o.sourceUrl}>{o.learningOutcomeCode}</a><span>{o.learningOutcome}</span><small>{lessons.some(l=>l.outcomes.includes(o.learningOutcomeCode))?(o.assessment==='observation'?'Etkinlik var · yetişkin gözlemi':'Etkinlik var · dijital pratik'):'Programda kayıtlı · etkinlik kapsamı dışında'}</small></div>)}</details></article>)}</>}
 {tab==='backup'&&<div className="backup-panel"><ShieldCheck size={38}/><h2>Öğrenme verileri bu cihazda</h2><p>Hesap, reklam, analiz aracı veya sosyal medya takibi yok. Soyadı, okul, konum ve iletişim bilgisi istenmez. Sesli okuma yalnızca cihazdaki yerel sesler ile yapılır.</p><p>Tarayıcı verileri silinirse ilerleme kaybolur. Başka cihaza geçmeden veya tarayıcıyı temizlemeden yedek indirin. Son 5.000 etkinlik saklanır; beceri toplamları korunur. PIN yedeğe dahil değildir.</p><div className="tool-actions"><button className="primary" onClick={backup}><Download size={18}/> İlerlemeyi Yedekle</button><label className="button file-input"><Upload size={18}/> Yedeği Geri Yükle<input type="file" accept="application/json,.json" onChange={e=>{void restore(e.target.files?.[0]);e.target.value=''}}/></label></div>{error&&<p role="alert">{error}</p>}{pending&&<div className="restore-preview"><h3>Yedek kontrol edildi</h3><p>{Object.keys(pending.completed).length} tamamlanan konu ve {pending.attempts.length} etkinlik var. Geri yükleme mevcut ilerlemenin yerine geçer.</p><div className="tool-actions"><button onClick={()=>{backup();update(pending);setPending(null);setError('Önceki ilerleme yedeklendi, yeni yedek geri yüklendi.')}}>Önce yedekle, sonra geri yükle</button><button onClick={()=>setPending(null)}>Vazgeç</button></div></div>}<h3>Uygulamayı ana ekrana ekleme</h3><p>Android’de tarayıcı menüsünden “Uygulamayı yükle” veya “Ana ekrana ekle”; iPad ve iPhone’da Safari’nin Paylaş menüsünden “Ana Ekrana Ekle”yi seçin. İlk açılışta çevrim dışı paket hazır olana kadar interneti açık tutun.</p><h3>Gizlilik sınırı</h3><p>İlerleme sunucuya gönderilmez. Siteye bağlanmak için sunucu IP adresi gibi olağan bağlantı bilgilerini işler; uygulama düzeyinde ziyaretçi günlüğü tutulmaz. Tarayıcı, cihaz veya ağ hizmetleri kendi politikalarına tabidir.</p></div>}</section>
}
