'use client';
import {useEffect,useState} from 'react';
import dynamic from 'next/dynamic';
import {BookOpen,Compass,Flower2,House,Volume2,VolumeX,LockKeyhole,ArrowRight,ArrowLeft,Star,Check,WifiOff,Download,Leaf} from 'lucide-react';
import {subjects} from '@/content/subjects';
import {lessons} from '@/content';
import type {Progress} from '@/lib/types';
import {dueSkills,emptyProgress,parseBackup,STORAGE_KEY} from '@/lib/progress';
import {stopSpeech} from '@/lib/audio';
import {Piko,WorldArt} from './Illustration';
const LessonPlayer=dynamic(()=>import('./LessonPlayer'),{loading:()=> <p role="status">Keşfin açılıyor…</p>});
const Parents=dynamic(()=>import('./Parents'),{loading:()=> <p role="status">Ebeveyn alanı açılıyor…</p>});
type InstallEvent=Event&{prompt:()=>Promise<void>};
export default function World(){
 const [route,setRoute]=useState('home'),[progress,setProgress]=useState<Progress>(emptyProgress),[loaded,setLoaded]=useState(false),[storageError,setStorageError]=useState(''),[offline,setOffline]=useState(false),[cached,setCached]=useState(false),[newWorker,setNewWorker]=useState<ServiceWorker|null>(null),[install,setInstall]=useState<InstallEvent|null>(null);
 useEffect(()=>{const readRoute=()=>{if(location.hash==='#main'){document.getElementById('main')?.focus();return}setRoute(location.hash.slice(1)||'home');stopSpeech();window.scrollTo({top:0,behavior:'instant'})};readRoute();window.addEventListener('hashchange',readRoute);try{const saved=localStorage.getItem(STORAGE_KEY);if(saved)setProgress(parseBackup(saved));}catch{setStorageError('Bu cihazdaki ilerleme okunamadı. Eski kayıt korunuyor. Ebeveyn alanından sağlam bir yedek yükleyebilirsin.')}setLoaded(true);const net=()=>setOffline(!navigator.onLine);net();window.addEventListener('online',net);window.addEventListener('offline',net);const onInstall=(e:Event)=>{e.preventDefault();setInstall(e as InstallEvent)};window.addEventListener('beforeinstallprompt',onInstall);
  if('serviceWorker'in navigator&&process.env.NODE_ENV==='production'){navigator.serviceWorker.register('/sw.js').then(reg=>{if(reg.active)setCached(true);if(reg.waiting)setNewWorker(reg.waiting);reg.addEventListener('updatefound',()=>{const w=reg.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed'){if(navigator.serviceWorker.controller)setNewWorker(w);else setCached(true)}})});navigator.serviceWorker.ready.then(()=>setCached(true))}).catch(()=>setCached(false))}
  const sync=(e:StorageEvent)=>{if(e.key===STORAGE_KEY&&e.newValue){try{setProgress(parseBackup(e.newValue))}catch{setStorageError('Diğer sekmedeki veri okunamadı.')}}};window.addEventListener('storage',sync);
  return()=>{window.removeEventListener('hashchange',readRoute);window.removeEventListener('online',net);window.removeEventListener('offline',net);window.removeEventListener('beforeinstallprompt',onInstall);window.removeEventListener('storage',sync)};
 },[]);
 function update(p:Progress){setProgress(p);try{if(storageError&&!route.startsWith('parents'))return;localStorage.setItem(STORAGE_KEY,JSON.stringify(p));setStorageError('')}catch{setStorageError('İlerleme bu cihaza kaydedilemiyor. Ebeveyn alanından yedek indirip tarayıcı depolamasını kontrol edin.')}}
 const [page,id]=route.split('/'),subject=subjects.find(s=>s.id===id),lesson=lessons.find(l=>l.id===id),completed=Object.keys(progress.completed).length,reviewCodes=dueSkills(progress),reviewLesson=lessons.find(l=>l.outcomes.some(c=>reviewCodes.includes(c))),lastLesson=lessons.find(l=>l.id===progress.lastLesson&&!progress.completed[l.id]),featured=reviewLesson??lastLesson??lessons[0];
 const badges=[{icon:'🌱',title:'İlk filiz',desc:'İlk konunu tamamla.',earned:completed>=1},{icon:'⭐',title:'Meraklı kâşif',desc:'10 soruyu ipucusuz çöz.',earned:progress.stars>=10},{icon:'🪐',title:'Sayı gezgini',desc:'5 matematik konusu tamamla.',earned:lessons.filter(l=>l.subject==='math'&&progress.completed[l.id]).length>=5},{icon:'🌈',title:'Renkli keşifler',desc:'3 farklı derste çalış.',earned:new Set(progress.attempts.map(a=>lessons.find(l=>l.id===a.lessonId)?.subject)).size>=3},{icon:'📚',title:'Hikâye dostu',desc:'Bir Türkçe temasındaki 3 dersi tamamla.',earned:subjects.find(s=>s.id==='tr')!.themes.some(t=>lessons.filter(l=>l.subject==='tr'&&l.theme===t).every(l=>progress.completed[l.id]))},{icon:'🌟',title:'Yüz küçük adım',desc:'100 değerlendirme etkinliği yap.',earned:progress.attempts.filter(a=>!a.selfReport).length>=100}];
 return <><a className="skip-link" href="#main">İçeriğe geç</a><aside className="sidebar"><a href="#home" className="brand"><span className="brand-mark"><BookOpen size={25}/><i>✦</i></span><span>Lara’nın<br/><b>Dersleri</b></span></a><div className="sidebar-label">KEŞİF ZAMANI</div><nav aria-label="Ana gezinti"><a aria-label="Benim dünyam" href="#home" className={page==='home'?'active':''}><House size={22}/><span>Benim dünyam</span></a><a aria-label="Derslerim" href="#subjects" className={page==='subjects'||page==='subject'||page==='lesson'?'active':''}><Compass size={22}/><span>Derslerim</span></a><a aria-label="Başarı bahçem" href="#garden" className={page==='garden'?'active':''}><Flower2 size={22}/><span>Başarı bahçem</span></a></nav><div className="sidebar-piko"><Piko size={100}/><p>Küçük adımlar,<br/><b>büyük keşifler!</b></p></div><a href="#parents" className="parent-link"><LockKeyhole size={17}/> Ebeveyn Alanı</a><p className="sidebar-foot">Lara için sevgiyle 🌱</p></aside><div className="app-shell"><header className="topbar"><span className="topbar-title">Benim öğrenme dünyam <span className="tiny-dot"/> <small>2. sınıf</small></span><div className="header-actions">{offline&&<span className="offline-label"><WifiOff size={16}/> Çevrim dışı</span>}<span className="star-count"><Star size={18} fill="currentColor"/> {progress.stars}<span> yıldız</span></span><button className="sound-toggle" aria-label={progress.sound?'Sesi kapat':'Sesi aç'} title={progress.sound?'Sesi kapat':'Sesi aç'} onClick={()=>{if(progress.sound)stopSpeech();update({...progress,sound:!progress.sound})}}>{progress.sound?<Volume2 size={21}/>:<VolumeX size={21}/>}</button><span className="avatar" aria-label="Lara">L</span></div></header><main id="main" tabIndex={-1}>{storageError&&<p className="notice error" role="alert">{storageError}</p>}{newWorker&&<div className="notice">Yeni keşifler hazır! İlerlemen kaydedildi. <button onClick={()=>{navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload(),{once:true});newWorker.postMessage({type:'ACTIVATE'})}}>Uygulamayı güncelle</button></div>}
 {(page==='home'||page==='subjects')&&<><div className="welcome"><div><p className="eyebrow">HER GÜN YENİ BİR KEŞİF</p><h1>Merhaba Lara <span className="hello-hand">👋</span></h1><p>Bugün ne öğrenmek istersin?</p></div><div className="grade-badge"><span>🌼</span><div>Merak etmekle başlar.<small>Kendi hızında, keyifle.</small></div></div></div>{page==='home'&&<div className="hero"><div className="hero-copy"><span className="pill"><Leaf size={15}/> {reviewLesson?'BİRAZ PEKİŞTİRELİM':lastLesson?'MACERANA DEVAM ET':'BUGÜNÜN KÜÇÜK MACERASI'}</span><h2>{reviewLesson?'Öğrendiklerini bir kez daha keşfet.':lastLesson?lastLesson.title:<>Sayı Gezegeni’ne<br/>bir yolculuk yapalım mı?</>}</h2><p>{reviewLesson?'Bugün biraz tekrar yapalım mı? Piko sana eşlik edecek.':lastLesson?'Kaldığın konuyu yeniden açıp keşfine devam edebilirsin.':'Onlukları birleştir, birlikleri say. Piko ile sayıların sırrını keşfet!'}</p><a className="primary" href={`#lesson/${featured.id}`}>Keşfe başla <ArrowRight size={18}/></a><span className="hero-time">✧ Yaklaşık {featured.minutes} dakikalık keşif</span></div><div className="hero-illustration"><WorldArt/><div className="hero-piko"><Piko size={125} wave/></div><span className="art-label">Birlikte keşfedelim!</span></div></div>}<div className="section-title"><div><h2>Öğrenme adaları</h2><p>Bir ada seç, maceran başlasın.</p></div><span className="muted island-count">7 küçük dünya</span></div><div className="subject-grid">{subjects.map((s,i)=>{const count=lessons.filter(l=>l.subject===s.id).length,done=lessons.filter(l=>l.subject===s.id&&progress.completed[l.id]).length;return <a href={`#subject/${s.id}`} className={`subject-card ${s.color}`} key={s.id}><div className="card-top"><span className="subject-illustration">{s.icon}<i>{['✧','🍄','☁','✦','✿','♪','✧'][i]}</i></span><span className="card-arrow"><ArrowRight size={19}/></span></div><small>{s.world}</small><h3>{s.name}</h3><p>{s.description}</p><div className="card-bottom"><span>{count} keşif</span><span>{done?`${done} tamamlandı`:'Seni bekliyor'} <span aria-hidden="true">✦</span></span></div></a>})}</div><div className="home-bottom"><div className="growth-card"><div className="growth-icon">🌱</div><div><h3>Her keşifte biraz daha büyürsün.</h3><p>{completed?`${completed} konu tamamladın. Bahçendeki yeni filizlere bak!`:'İlk keşfinle başarı bahçene bir filiz ekle.'}</p><a href="#garden">Bahçeme git <ArrowRight size={16}/></a></div></div><a className="movement-card" href="#lesson/move-jump"><span>🐇</span><div><small>KÜÇÜK BİR MOLA</small><h3>Biraz hareket edelim!</h3><p>Esne, zıpla, yeniden gülümse.</p></div><ArrowRight size={22}/></a></div></>}
 {page==='subject'&&subject&&<><a className="back" href="#subjects"><ArrowLeft size={18}/> Adalara dön</a><div className={`subject-banner ${subject.color}`}><div><p className="eyebrow">{subject.world}</p><h1>{subject.name}</h1><p>{subject.description} Her keşif küçük bir adımla başlar.</p></div><span>{subject.icon}</span></div>{subject.themes.map(theme=>{const list=lessons.filter(l=>l.subject===subject.id&&l.theme===theme);if(!list.length)return null;return <div className="theme-section" key={theme}><h2>{theme}</h2><div className="lesson-grid">{list.map(l=><a href={`#lesson/${l.id}`} className="lesson-tile" key={l.id}><span>{l.icon}</span><div><h3>{l.title}</h3><p>{l.minutes} dk · Keşif ve oyun</p></div>{progress.completed[l.id]?<Check size={23} className="complete-check"/>:<ArrowRight size={21}/>}</a>)}</div></div>})}</>}
 {page==='lesson'&&lesson&&loaded&&<LessonPlayer key={lesson.id} lesson={lesson} progress={progress} update={update}/>}
 {page==='garden'&&<><div className="welcome"><div><p className="eyebrow">EMEĞİNLE BÜYÜYEN BİR BAHÇE</p><h1>Başarı bahçem 🌱</h1><p>Her deneme bir adım. Burada yarış yok.</p></div><Piko size={110}/></div><div className="garden-scene">{completed===0?<p>İlk keşfinden sonra buraya bir çiçek ekilecek.</p>:Array.from({length:Math.min(completed,30)},(_,i)=><span key={i} style={{animationDelay:`${i*.06}s`}}>{['🌼','🌷','🌱','🌻'][i%4]}</span>)}</div><div className="badge-grid">{badges.map(b=><div key={b.title} className={`badge-card ${b.earned?'earned':''}`}><span>{b.icon}</span><h3>{b.title}</h3><p>{b.desc}</p><small>{b.earned?'✓ Bahçene eklendi':'Kendi hızında keşfet'}</small></div>)}</div><a className="primary" href="#subjects">Yeni bir ada keşfet <ArrowRight size={18}/></a></>}
 {page==='parents'&&loaded&&<Parents progress={progress} update={update}/>}
 {(!['home','subjects','subject','lesson','garden','parents'].includes(page)||(page==='subject'&&!subject)||(page==='lesson'&&!lesson))&&<div className="gate-card"><Piko/><h1>Bu yolu bulamadım.</h1><p>Öğrenme adalarından birini seçelim.</p><a className="primary" href="#home">Dünyama dön</a></div>}
 <footer className="app-footer"><span><Leaf size={15}/> Merakla öğren, keyifle büyü.</span><span>{cached?'Çevrim dışı keşifler hazır ✓':'İlerleme bu cihazda saklanır'}</span>{install&&<button onClick={()=>{void install.prompt();setInstall(null)}}><Download size={16}/> Ana ekrana ekle</button>}</footer></main></div><nav className="mobile-nav" aria-label="Mobil gezinti"><a href="#home" className={page==='home'?'active':''}><House size={21}/><span>Dünyam</span></a><a href="#subjects" className={['subjects','subject','lesson'].includes(page)?'active':''}><Compass size={21}/><span>Derslerim</span></a><a href="#garden" className={page==='garden'?'active':''}><Flower2 size={21}/><span>Bahçem</span></a><a href="#parents" className={page==='parents'?'active':''}><LockKeyhole size={21}/><span>Ebeveyn</span></a></nav></>
}
