'use client';
import {useEffect,useState,type CSSProperties} from 'react';
import dynamic from 'next/dynamic';
import {Compass,Flower2,House,Volume2,VolumeX,LockKeyhole,ArrowRight,ArrowLeft,Star,Check,WifiOff,Download,Leaf,Gamepad2,Clock3} from 'lucide-react';
import {subjects} from '@/content/subjects';
import {lessons} from '@/content';
import {games} from '@/content/games';
import {profile} from '@/content/profile';
import type {Progress} from '@/lib/types';
import {dueSkills,emptyProgress,parseBackup,STORAGE_KEY} from '@/lib/progress';
import {stopSpeech} from '@/lib/audio';
import {Art} from './Illustration';
import GameCard from './GameCard';
const LessonPlayer=dynamic(()=>import('./LessonPlayer'),{loading:()=> <p role="status" className="loading-note">Keşfin açılıyor…</p>});
const GamePlayer=dynamic(()=>import('./GamePlayer'),{loading:()=> <p role="status" className="loading-note">Oyun açılıyor…</p>});
const Parents=dynamic(()=>import('./Parents'),{loading:()=> <p role="status" className="loading-note">Ebeveyn alanı açılıyor…</p>});
type InstallEvent=Event&{prompt:()=>Promise<void>};
const pages=['home','games','game','subjects','subject','lesson','garden','parents'];
export default function World(){
 const [route,setRoute]=useState('home'),[progress,setProgress]=useState<Progress>(emptyProgress),[loaded,setLoaded]=useState(false),[storageError,setStorageError]=useState(''),[offline,setOffline]=useState(false),[cached,setCached]=useState(false),[newWorker,setNewWorker]=useState<ServiceWorker|null>(null),[install,setInstall]=useState<InstallEvent|null>(null);
 useEffect(()=>{const readRoute=()=>{if(location.hash==='#main'){document.getElementById('main')?.focus();return}setRoute(location.hash.slice(1)||'home');stopSpeech();window.scrollTo({top:0,behavior:'instant'})};readRoute();window.addEventListener('hashchange',readRoute);try{const saved=localStorage.getItem(STORAGE_KEY);if(saved)setProgress(parseBackup(saved));}catch{setStorageError('Bu cihazdaki ilerleme okunamadı. Eski kayıt korunuyor. Ebeveyn alanından sağlam bir yedek yükleyebilirsin.')}setLoaded(true);const net=()=>setOffline(!navigator.onLine);net();window.addEventListener('online',net);window.addEventListener('offline',net);const onInstall=(e:Event)=>{e.preventDefault();setInstall(e as InstallEvent)};window.addEventListener('beforeinstallprompt',onInstall);
  if('serviceWorker'in navigator&&process.env.NODE_ENV==='production'){navigator.serviceWorker.register('/sw.js').then(reg=>{if(reg.active)setCached(true);if(reg.waiting)setNewWorker(reg.waiting);reg.addEventListener('updatefound',()=>{const w=reg.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed'){if(navigator.serviceWorker.controller)setNewWorker(w);else setCached(true)}})});navigator.serviceWorker.ready.then(()=>setCached(true))}).catch(()=>setCached(false))}
  const sync=(e:StorageEvent)=>{if(e.key===STORAGE_KEY&&e.newValue){try{setProgress(parseBackup(e.newValue))}catch{setStorageError('Diğer sekmedeki veri okunamadı.')}}};window.addEventListener('storage',sync);
  return()=>{window.removeEventListener('hashchange',readRoute);window.removeEventListener('online',net);window.removeEventListener('offline',net);window.removeEventListener('beforeinstallprompt',onInstall);window.removeEventListener('storage',sync)};
 },[]);
 function update(p:Progress){setProgress(p);try{if(storageError&&!route.startsWith('parents'))return;localStorage.setItem(STORAGE_KEY,JSON.stringify(p));setStorageError('')}catch{setStorageError('İlerleme bu cihaza kaydedilemiyor. Ebeveyn alanından yedek indirip tarayıcı depolamasını kontrol edin.')}}
 const [page,id]=route.split('/'),subject=subjects.find(s=>s.id===id),lesson=lessons.find(l=>l.id===id),game=games.find(g=>g.id===id),completed=Object.keys(progress.completed).length,reviewCodes=dueSkills(progress),reviewLesson=reviewCodes.map(c=>lessons.find(l=>l.outcomes.includes(c))).find(Boolean),lastLesson=lessons.find(l=>l.id===progress.lastLesson&&!progress.completed[l.id]),featured=reviewLesson??lastLesson??lessons[0],inLessons=['subjects','subject','lesson'].includes(page),inGames=page==='games'||page==='game';
 const badges=[{art:'badge-sprout',title:'İlk filiz',desc:'İlk konunu tamamla.',earned:completed>=1},{art:'badge-explorer',title:'Meraklı kâşif',desc:'10 soruyu ipucusuz çöz.',earned:progress.stars>=10},{art:'badge-planet',title:'Sayı gezgini',desc:'5 matematik konusu tamamla.',earned:lessons.filter(l=>l.subject==='math'&&progress.completed[l.id]).length>=5},{art:'badge-rainbow',title:'Renkli keşifler',desc:'3 farklı derste çalış.',earned:new Set(progress.attempts.map(a=>lessons.find(l=>l.id===a.lessonId)?.subject)).size>=3},{art:'badge-books',title:'Hikâye dostu',desc:'Bir Türkçe temasındaki 3 dersi tamamla.',earned:subjects.find(s=>s.id==='tr')!.themes.some(t=>lessons.filter(l=>l.subject==='tr'&&l.theme===t).every(l=>progress.completed[l.id]))},{art:'badge-star',title:'Yüz küçük adım',desc:'100 değerlendirme etkinliği yap.',earned:progress.attempts.filter(a=>!a.selfReport).length>=100},{art:'badge-game',title:'Oyun kâşifi',desc:'Oyun köşesindeki her oyundan bir tur bitir.',earned:games.every(g=>progress.games?.[g.id])}],earnedBadges=badges.filter(b=>b.earned).length,featuredSubject=subjects.find(s=>s.id===featured.subject)!;
 const meter=(done:number,count:number)=>({'--p':`${Math.round(done/Math.max(count,1)*100)}%`}) as CSSProperties;
 const subjectGrid=<div className="subject-grid">{subjects.map((s,i)=>{const count=lessons.filter(l=>l.subject===s.id).length,done=lessons.filter(l=>l.subject===s.id&&progress.completed[l.id]).length;return <a href={`#subject/${s.id}`} className={`subject-card ${s.color}`} key={s.id}><span className="island-wrap"><Art name={`island-${s.id}`} size={i?220:300} className="island" sizes={i?'(max-width:560px) 120px,180px':'(max-width:560px) 132px,250px'}/></span><div className="subject-copy"><small>{s.world}</small><h3>{s.name}</h3><p>{s.description}</p><span className="meter" style={meter(done,count)}/></div><div className="card-bottom"><span>{count} keşif</span><span>{done?`${done} tamamlandı`:'Seni bekliyor'} <ArrowRight size={16}/></span></div></a>})}</div>;
 const gameGrid=<div className="game-grid">{games.map(g=><GameCard key={g.id} game={g} record={progress.games?.[g.id]}/>)}</div>;
 const navIcon=(icon:React.ReactNode)=><span className="nav-icon" aria-hidden="true">{icon}</span>;
 return <><a className="skip-link" href="#main">İçeriğe geç</a>
 <aside className="sidebar"><a href="#home" className="brand" aria-label="Lara’nın Dünyası"><span className="brand-mark"><Art name="piko-head" size={52} eager/></span><span>Lara’nın<br/><b>Dünyası</b></span></a><div className="sidebar-label">KEŞİF ZAMANI</div><nav aria-label="Ana gezinti"><a aria-label="Benim dünyam" href="#home" className={page==='home'?'active':''}>{navIcon(<House size={20}/>)}<span>Benim dünyam</span></a><a aria-label="Derslerim" href="#subjects" className={inLessons?'active':''}>{navIcon(<Compass size={20}/>)}<span>Derslerim</span></a><a aria-label="Başarı bahçem" href="#garden" className={page==='garden'?'active':''}>{navIcon(<Flower2 size={20}/>)}<span>Başarı bahçem</span></a><a aria-label="Oyun molası" href="#games" className={inGames?'active':''}>{navIcon(<Gamepad2 size={20}/>)}<span>Oyun molası</span></a></nav><div className="sidebar-piko"><Art name="piko-read" size={132}/><p>Küçük adımlar,<br/><b>büyük keşifler!</b></p></div><a href="#parents" className="parent-link"><LockKeyhole size={17}/> Ebeveyn Alanı</a><p className="sidebar-foot">Lara için sevgiyle 🌱</p></aside>
 <div className="app-shell"><header className="topbar"><span className="topbar-title">Benim öğrenme dünyam <span className="tiny-dot"/> <small>2. sınıf</small></span><div className="header-actions">{offline&&<span className="offline-label"><WifiOff size={16}/> Çevrim dışı</span>}<span className="star-count"><Star size={18} fill="currentColor"/> <b key={progress.stars}>{progress.stars}</b><span> yıldız</span></span><button className="sound-toggle" aria-label={progress.sound?'Sesi kapat':'Sesi aç'} title={progress.sound?'Sesi kapat':'Sesi aç'} onClick={()=>{if(progress.sound)stopSpeech();update({...progress,sound:!progress.sound})}}>{progress.sound?<Volume2 size={21}/>:<VolumeX size={21}/>}</button><span className="avatar" aria-label={profile.name}>{profile.avatar}</span></div></header><main id="main" tabIndex={-1}>{storageError&&<p className="notice error" role="alert">{storageError}</p>}{newWorker&&<div className="notice">Yeni keşifler hazır! İlerlemen kaydedildi. <button onClick={()=>{navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload(),{once:true});newWorker.postMessage({type:'ACTIVATE'})}}>Uygulamayı güncelle</button></div>}<div className="view" key={route}>
 {page==='home'&&<>
  <section className="hero" aria-labelledby="profile-title"><img className="hero-scene" src="/art/hero-world.webp" srcSet="/art/hero-world-768.webp 768w,/art/hero-world-960.webp 960w,/art/hero-world.webp 1536w" sizes="(max-width:560px) 100vw,(max-width:1100px) 60vw,780px" width={1536} height={1024} alt="" fetchPriority="high"/><div className="hero-copy"><p className="eyebrow">{profile.possessive.toLocaleUpperCase('tr-TR')} DÜNYASI</p><h1 id="profile-title">Merhaba, ben {profile.name}! <span className="hello-hand" aria-hidden="true">👋</span></h1><p className="profile-about">{profile.about}</p><p className="hero-intro">{profile.intro}</p>{profile.favorites.length>0&&<ul className="favorites">{profile.favorites.map(f=><li key={f.label}><span aria-hidden="true">{f.icon}</span><small>{f.label}:</small> <b>{f.value}</b></li>)}</ul>}<div className="profile-actions"><a className="primary" href="#subjects"><Compass size={18}/> Derslerim</a>{(completed>0||progress.stars>0)&&<ul className="hero-stats"><li><b>{completed}</b> keşif</li><li><b>{progress.stars}</b> yıldız</li><li><b>{earnedBadges}</b> rozet</li></ul>}</div></div><Art name="piko-wave" size={260} className="hero-piko" sizes="(max-width:560px) 108px,172px" eager/></section>
  <section className={`today-card ${featuredSubject.color}`} aria-labelledby="today-title"><span className="today-art"><Art name={`island-${featuredSubject.id}`} size={220} sizes="(max-width:560px) 150px,196px"/></span><div className="today-copy"><span className="pill"><Leaf size={15}/> {reviewLesson?'BİRAZ PEKİŞTİRELİM':lastLesson?'MACERANA DEVAM ET':'BUGÜNÜN KÜÇÜK MACERASI'}</span><h2 id="today-title">{reviewLesson?'Öğrendiklerini bir kez daha keşfet.':lastLesson?lastLesson.title:<>Sayı Gezegeni’ne bir yolculuk yapalım mı?</>}</h2><p>{reviewLesson?'Bugün biraz tekrar yapalım mı? Piko sana eşlik edecek.':lastLesson?'Kaldığın konuyu yeniden açıp keşfine devam edebilirsin.':'Onlukları birleştir, birlikleri say. Piko ile sayıların sırrını keşfet!'}</p><div className="today-actions"><a className="primary" href={`#lesson/${featured.id}`}>Keşfe başla <ArrowRight size={18}/></a><span className="hero-time"><Clock3 size={15}/> Yaklaşık {featured.minutes} dakikalık keşif</span></div></div></section>
  <div className="section-title"><div><h2>Öğrenme adaları</h2><p>Bir ada seç, maceran başlasın.</p></div><span className="muted island-count">7 küçük dünya</span></div>{subjectGrid}
  {profile.drawings.length>0&&<><div className="section-title"><div><h2>Benim resimlerim</h2><p>Renk Atölyesi’nde yaptıklarımdan seçtiklerim.</p></div></div><div className="gallery">{profile.drawings.map(d=><figure key={d.src}><img src={d.src} alt={d.title} loading="lazy"/><figcaption>{d.title}</figcaption></figure>)}</div></>}
  <div className="home-bottom"><div className="growth-card"><Art name="flower-sprout" size={96} className="card-art"/><div><h3>Her keşifte biraz daha büyürsün.</h3><p>{completed?`${completed} konu tamamladın. Bahçendeki yeni filizlere bak!`:'İlk keşfinle başarı bahçene bir filiz ekle.'}</p><a href="#garden">Bahçeme git <ArrowRight size={16}/></a></div></div><a className="movement-card" href="#lesson/move-jump"><Art name="piko-cheer" size={96} className="card-art"/><div><small>KÜÇÜK BİR MOLA</small><h3>Biraz hareket edelim!</h3><p>Esne, zıpla, yeniden gülümse.</p></div><ArrowRight size={22}/></a><a className="movement-card play-card" href="#games"><Art name="game-balloons" size={96} className="card-art"/><div><small>OYUN MOLASI</small><h3>Biraz oyun oynayalım mı?</h3><p>Eşini bul, balon patlat, Piko’yu eve götür.</p></div><ArrowRight size={22}/></a></div>
 </>}
 {page==='games'&&<><div className="welcome"><div><p className="eyebrow">DERSLER ARASINDA KÜÇÜK BİR MOLA</p><h1>Oyun molası 🎮</h1><p>Dilediğin oyunu seç. Derslerine istediğin zaman dönebilirsin.</p></div><Art name="piko-cheer" size={150} className="welcome-art" eager/></div>{gameGrid}<a className="primary" href="#subjects">Derslerime dön <ArrowRight size={18}/></a></>}
 {page==='game'&&game&&loaded&&<GamePlayer key={game.id} id={game.id} progress={progress} update={update}/>}
 {page==='subjects'&&<><div className="welcome"><div><p className="eyebrow">HER GÜN YENİ BİR KEŞİF</p><h1>Derslerim 📚</h1><p>Bir ada seç, maceran başlasın. Kendi hızında, keyifle.</p></div><Art name="piko-read" size={150} className="welcome-art" eager/></div>{subjectGrid}</>}
 {page==='subject'&&subject&&(()=>{const all=lessons.filter(l=>l.subject===subject.id),done=all.filter(l=>progress.completed[l.id]).length;return <><a className="back" href="#subjects"><ArrowLeft size={18}/> Adalara dön</a><div className={`subject-banner ${subject.color}`}><div><p className="eyebrow">{subject.world}</p><h1>{subject.name}</h1><p>{subject.description} Her keşif küçük bir adımla başlar.</p><div className="banner-progress"><span className="meter" style={meter(done,all.length)}/><small>{done} / {all.length} keşif tamamlandı</small></div></div><Art name={`island-${subject.id}`} size={260} className="banner-island" sizes="(max-width:560px) 150px,250px" eager/></div>{subject.themes.map(theme=>{const list=all.filter(l=>l.theme===theme);if(!list.length)return null;return <div className="theme-section" key={theme}><h2>{theme}</h2><div className="lesson-grid">{list.map(l=><a href={`#lesson/${l.id}`} className={`lesson-tile ${subject.color}${progress.completed[l.id]?' is-done':''}`} key={l.id}><span>{l.icon}</span><div><h3>{l.title}</h3><p>{l.minutes} dk · Keşif ve oyun</p></div>{progress.completed[l.id]?<Check size={23} className="complete-check"/>:<ArrowRight size={21}/>}</a>)}</div></div>})}</>})()}
 {page==='lesson'&&lesson&&loaded&&<LessonPlayer key={lesson.id} lesson={lesson} progress={progress} update={update}/>}
 {page==='garden'&&<><div className="welcome"><div><p className="eyebrow">EMEĞİNLE BÜYÜYEN BİR BAHÇE</p><h1>Başarı bahçem 🌱</h1><p>Her deneme bir adım. Burada yarış yok.</p></div><Art name="piko-wave" size={150} className="welcome-art" eager/></div><div className="garden-scene"><img className="garden-backdrop" src="/art/garden-bed.webp" width={1400} height={705} alt="" decoding="async"/>{completed===0?<p className="garden-empty">İlk keşfinden sonra buraya bir çiçek ekilecek.</p>:<div className="garden-flowers">{Array.from({length:Math.min(completed,30)},(_,i)=><Art key={i} name={`flower-${['daisy','tulip','sprout','sunflower'][i%4]}`} size={88} style={{animationDelay:`${i*.06}s`}}/>)}</div>}</div><div className="badge-grid">{badges.map(b=><div key={b.title} className={`badge-card ${b.earned?'earned':''}`}><Art name={b.art} size={120} className="badge-art"/><h3>{b.title}</h3><p>{b.desc}</p><small>{b.earned?'✓ Bahçene eklendi':'Kendi hızında keşfet'}</small></div>)}</div><a className="primary" href="#subjects">Yeni bir ada keşfet <ArrowRight size={18}/></a></>}
 {page==='parents'&&loaded&&<Parents progress={progress} update={update}/>}
 {(!pages.includes(page)||(page==='subject'&&!subject)||(page==='lesson'&&!lesson)||(page==='game'&&!game))&&<div className="gate-card"><Art name="piko-think" size={150}/><h1>Bu yolu bulamadım.</h1><p>Öğrenme adalarından birini seçelim.</p><a className="primary" href="#home">Dünyama dön</a></div>}
 </div><footer className="app-footer"><span><Leaf size={15}/> Merakla öğren, keyifle büyü.</span><span>{cached?'Çevrim dışı keşifler hazır ✓':'İlerleme bu cihazda saklanır'}</span>{install&&<button onClick={()=>{void install.prompt();setInstall(null)}}><Download size={16}/> Ana ekrana ekle</button>}</footer></main></div>
 <nav className="mobile-nav" aria-label="Mobil gezinti"><a href="#home" className={page==='home'?'active':''}><House size={21}/><span>Dünyam</span></a><a href="#subjects" className={inLessons?'active':''}><Compass size={21}/><span>Dersler</span></a><a href="#garden" className={page==='garden'?'active':''}><Flower2 size={21}/><span>Bahçem</span></a><a href="#games" className={inGames?'active':''}><Gamepad2 size={21}/><span>Oyunlar</span></a><a href="#parents" className={page==='parents'?'active':''}><LockKeyhole size={21}/><span>Ebeveyn</span></a></nav></>
}
