import type {Lesson} from '@/lib/types';
const groups=[
 ['School Life','Hello, Piko!','👋',[['hello','👋','merhaba'],['teacher','🧑‍🏫','öğretmen'],['school','🏫','okul'],['student','🧒','öğrenci'],['goodbye','🙋','hoşça kal'],['friend','🧑‍🤝‍🧑','arkadaş'],['bag','🎒','çanta'],['bus','🚌','otobüs']]],
 ['Classroom Life','Renkli sınıfım','🎒',[['book','📖','kitap'],['pencil','✏️','kalem'],['chair','🪑','sandalye'],['red','🔴','kırmızı'],['blue','🔵','mavi'],['ruler','📏','cetvel'],['green','🟢','yeşil'],['yellow','🟡','sarı']]],
 ['Personal Life','Kendimi tanıtıyorum','😊',[['head','🙂','baş'],['shirt','👕','gömlek'],['eye','👁️','göz'],['hand','✋','el'],['ear','👂','kulak'],['nose','👃','burun'],['foot','🦶','ayak'],['shoes','👟','ayakkabı']]],
 ['Family Life','Benim ailem','🏡',[['mother','👩','anne'],['father','👨','baba'],['sister','👧','kız kardeş'],['brother','👦','erkek kardeş'],['grandmother','👵','büyükanne'],['grandfather','👴','büyükbaba'],['baby','👶','bebek'],['family','👪','aile']]],
 ['Homes & Houses & Neighbourhoods','Evde keşif','🛋️',[['bed','🛏️','yatak'],['door','🚪','kapı'],['house','🏠','ev'],['window','🪟','pencere'],['cat','🐈','kedi'],['dog','🐕','köpek'],['sofa','🛋️','kanepe'],['bath','🛁','küvet']]],
 ['Life in the City & the World','Piknik sepetim','🧺',[['apple','🍎','elma'],['bread','🍞','ekmek'],['milk','🥛','süt'],['egg','🥚','yumurta'],['cheese','🧀','peynir'],['banana','🍌','muz'],['water','💧','su'],['cake','🍰','pasta']]]
] as const;
/** Kil görseli olan kelimeler (public/art/en). İnsan ve vücut kelimeleri görsel kuralı gereği emoji kalır; “hello” için el sallayan Piko kullanılır. */
const pictured=new Set(['school','bag','bus','book','chair','red','blue','ruler','green','yellow','shirt','shoes','bed','door','house','window','cat','dog','sofa','bath','apple','bread','milk','egg','cheese','banana','water','cake']),special:Record<string,string>={hello:'piko-wave',pencil:'q/pencil'};
export const englishLessons:Lesson[]=groups.map(([theme,title,icon,vocab],i)=>({id:`english-${i}`,subject:'english',theme,title,subtitle:'Dinle, eşleştir, sesli söyle.',icon,minutes:6,outcomes:[`ENG.2.${i+1}.V1`,`ENG.2.${i+1}.R3`],kind:'matching',generator:'vocab',learn:['Önce resme bak. Kelimeyi dinlemek için ses düğmesine dokun.','Kelimeyi sesli tekrar et. Sonra resimle eşleştir.'],vocabulary:vocab.map(([word,picture,meaning])=>{const art=special[word]??(pictured.has(word)?`en/${word}`:undefined);return art?{word,picture,meaning,art}:{word,picture,meaning}})}));
