import type {Lesson,Question} from './types';
import {stories} from '@/content/tr/lessons';
import {storyWorkshops} from '@/content/tr/workshops';
import {compositionPlans} from './manipulatives';
import {pick,rng,shuffle} from './random';
import {numberWord,withSuffix} from './turkish';
export {rng,shuffle};
/** [yönerge, cevap, yanlış seçenekler, açıklama, görsel] */
type Fact=[instruction:string,answer:string,wrong:string[],explanation:string,visual?:string];
const addStories=[(a:number,b:number)=>`Sepette ${a} elma var. ${b} elma daha koyduk. Kaç elma oldu?`,(a:number,b:number)=>`Lara önce ${a} sayfa, sonra ${b} sayfa kitap okudu. Toplam kaç sayfa okudu?`,(a:number,b:number)=>`Kutuda ${a} boncuk vardı. Ece ${b} boncuk ekledi. Kutuda kaç boncuk oldu?`,(a:number,b:number)=>`Otobüste ${a} yolcu vardı. Durakta ${b} yolcu bindi. Otobüste kaç yolcu oldu?`];
const takeStories=[(a:number,b:number)=>`Dalda ${a} kuş vardı. ${b} kuş uçtu. Dalda kaç kuş kaldı?`,(a:number,b:number)=>`Lara’nın ${a} balonu vardı. ${b} balon patladı. Kaç balonu kaldı?`,(a:number,b:number)=>`Tabakta ${a} kurabiye vardı. ${b} kurabiye yendi. Tabakta kaç kurabiye kaldı?`,(a:number,b:number)=>`Otoparkta ${a} araba vardı. ${b} araba çıktı. Otoparkta kaç araba kaldı?`,(a:number,b:number)=>`Kutuda ${a} kalem vardı. Ece ${b} kalem aldı. Kutuda kaç kalem kaldı?`];
/** Eş gruplar: kap, tamlayan ve yönelme ekli hâli, simge, nesne. */
const groupThings=[['tabak','tabağın','tabağa','🍓','çilek'],['sepet','sepetin','sepete','🍎','elma'],['vazo','vazonun','vazoya','🌷','lale'],['kutu','kutunun','kutuya','🖍️','boya kalemi'],['kavanoz','kavanozun','kavanoza','🍪','kurabiye'],['akvaryum','akvaryumun','akvaryuma','🐟','balık'],['kalemlik','kalemliğin','kalemliğe','✏️','kalem'],['yuva','yuvanın','yuvaya','🥚','yumurta'],['raf','rafın','rafa','📚','kitap'],['saksı','saksının','saksıya','🌻','ayçiçeği']] as const;
const countables=[['🍒','kiraz'],['🍓','çilek'],['🌼','papatya'],['⭐','yıldız'],['🐞','uğur böceği'],['🎈','balon'],['🐟','balık'],['🍪','kurabiye']] as const;
const shapeSets=[['🔺','🔵','🟩'],['🍎','🍐','🍊'],['🌸','🍀','🌼'],['☀️','🌙','⭐'],['🐞','🐝','🦋'],['🟥','🟨','🟦']],patternUnits=[[0,1],[0,0,1],[0,1,1],[0,1,2]];
/** [yönerge, boyanacak çeyrek sayısı, açıklama] */
const fractionTools:[string,number,string][]=[['Bir bütün oluşturmak için dört eş parçadan kaçını seçmelisin?',4,'Bir bütün dört çeyrektir. Dört parçanın hepsini seçeriz.'],['Bir yarım oluşturmak için dört eş parçadan kaçını seçmelisin?',2,'Bir yarım iki çeyrektir.'],['Bir çeyrek oluşturmak için dört eş parçadan kaçını seçmelisin?',1,'Dört eş parçanın her biri bir çeyrektir.'],['Pizzanın yarısını boya.',2,'Dört eş dilimin ikisi pizzanın yarısıdır.'],['Pastanın çeyreğini boya.',1,'Dört eş dilimden biri pastanın çeyreğidir.'],['İki yarım bir bütün eder. Bütün turtayı boya.',4,'İki yarım, yani dört çeyrek, bütün turtayı oluşturur.']];
const fractionFacts:Fact[]=[['Bir bütünde kaç yarım vardır?','2',['4','1'],'İki yarım bir bütün eder.'],['Bir bütünde kaç çeyrek vardır?','4',['2','3'],'Dört çeyrek bir bütün eder.'],['İki çeyrek neye eşittir?','Bir yarım',['Bir bütün','Bir çeyrek'],'İki çeyrek bir yarım eder.'],['Dört çeyrek neye eşittir?','Bir bütün',['Bir yarım','İki çeyrek'],'Dört çeyrek bir bütün eder.'],['Ece bir elmayı iki eş parçaya böldü. Her parçaya ne denir?','Yarım',['Çeyrek','Bütün'],'Bir bütün iki eş parçaya bölününce her parça yarımdır.','🍎'],['Bir pizza dört eş dilime bölündü. Bir dilime ne denir?','Çeyrek',['Yarım','Bütün'],'Dört eş parçanın her biri çeyrektir.','🍕'],['Hangisi daha büyük: bir yarım mı, bir çeyrek mi?','Bir yarım',['Bir çeyrek'],'Bir yarım iki çeyrek eder; bu yüzden bir çeyrekten büyüktür.'],['Bir simit eş olmayan iki parçaya bölündü. Parçalara yarım der miyiz?','Hayır, parçalar eş olmalı.',['Evet, her zaman.'],'Yarım diyebilmek için iki parçanın eş, yani aynı büyüklükte olması gerekir.','🥯']];
const moneyAsks=[(v:number)=>`${v} kuruşu kumbaraya koy.`,(v:number)=>`Lara kumbarasına ${v} kuruş atmak istiyor. Paraları kumbaraya koy.`,(v:number)=>`Kumbarada ${v} kuruş biriksin. Paraları kumbaraya at.`];
const moneyFacts:Fact[]=[['İki tane 50 kuruş kaç kuruş eder?','100',['50','150'],'50 + 50 = 100. İki tane 50 kuruş, 100 kuruş eder.'],['1 lira kaç kuruştur?','100',['10','50'],'100 kuruş 1 lira eder.'],['Dört tane 25 kuruş kaç lira eder?','1 lira',['4 lira','25 lira'],'25 + 25 + 25 + 25 = 100 kuruş, yani 1 lira.'],['Hangisi daha çok para: 3 tane 25 kuruş mu, 1 tane 50 kuruş mu?','3 tane 25 kuruş',['1 tane 50 kuruş'],'3 tane 25 kuruş 75 kuruş eder. 75 kuruş, 50 kuruştan fazladır.'],['Elindeki paraların sayısı çoksa her zaman daha çok paran mı vardır?','Hayır, paraların değerine bakarız.',['Evet, her zaman.'],'Sayı ile değer aynı şey değildir. Bir tane 1 lira, üç tane 25 kuruştan fazladır.'],['Ece’nin 2 tane 50 kuruşu, Can’ın 1 lirası var. Hangisinin parası daha çok?','İkisininki eşit.',['Ece’nin','Can’ın'],'2 tane 50 kuruş 100 kuruş, yani 1 lira eder. İkisinin parası eşittir.'],['75 kuruşu hangi paralarla oluştururuz?','50 kuruş ve 25 kuruş',['İki tane 50 kuruş','Üç tane 50 kuruş'],'50 + 25 = 75.'],['150 kuruş kaç lira kaç kuruştur?','1 lira 50 kuruş',['15 lira','5 lira 10 kuruş'],'100 kuruş 1 lira eder. 150 kuruş, 1 lira ile 50 kuruştur.']];
const clockAsks=[(t:string)=>`Saati ${t} yap.`,(t:string)=>`Saat ${t} olsun. Akrebi ve yelkovanı yerleştir.`,(t:string)=>`Piko’nun kitap saati ${t}. Saati kur.`,(t:string)=>`Oyun saati geldi: ${t}. Saati göster.`];
const days=['Pazartesi','Salı','Çarşamba','Perşembe','Cuma','Cumartesi','Pazar'],dayFrom=['Pazartesiden','Salıdan','Çarşambadan','Perşembeden','Cumadan','Cumartesiden','Pazardan'],months=['Ocak','Şubat','Mart','Nisan','Mayıs','Haziran','Temmuz','Ağustos','Eylül','Ekim','Kasım','Aralık'],seasons=['İlkbahar','Yaz','Sonbahar','Kış'],seasonFrom=['İlkbahardan','Yazdan','Sonbahardan','Kıştan'];
const calendarFacts:Fact[]=[['Bir hafta kaç gündür?','7',['5','12'],'Pazartesiden Pazara kadar 7 gün vardır.'],['Bir yılda kaç ay vardır?','12',['7','4'],'Bir yıl, Ocaktan Aralığa 12 aydır.'],['Bir yılda kaç mevsim vardır?','4',['12','7'],'İlkbahar, yaz, sonbahar ve kış: 4 mevsim.'],['Yılın ilk ayı hangisidir?','Ocak',['Aralık','Mart'],'Yıl Ocak ayıyla başlar.'],['Yılın son ayı hangisidir?','Aralık',['Ocak','Haziran'],'Yıl Aralık ayıyla biter.'],['Hangi mevsimden sonra kış gelir?','Sonbahar',['Yaz','İlkbahar'],'Mevsimler sırayla ilkbahar, yaz, sonbahar ve kıştır.']];
/** Sıralama görevleri yıl ve hafta sınırını aşmaz; mevsimde başlangıç yönergede söylenir. */
const calendarOrders:[string,number][]=[...[0,1,2,3,4].map(i=>['days',i] as [string,number]),...[0,1,2,3,4,5,6,7,8,9].map(i=>['months',i] as [string,number]),...[0,1,2,3].map(i=>['seasons',i] as [string,number])],calendarTasks:[string,number][]=[...calendarOrders,...days.map((_,i)=>['after',i] as [string,number]),...days.map((_,i)=>['before',i] as [string,number]),...calendarFacts.map((_,i)=>['fact',i] as [string,number])];
const rulerAsks=['Önce kalemin uzunluğunu tahmin et. Sonra cetvelle kontrol et: kalem kaç santimetre?','Kalemin boyunu cetvelle ölç. Kalem kaç santimetre?','Tahminini söyle, sonra cetveli göster. Kalem kaç santimetre?','Lara’nın kalemi kaç santimetre? Önce tahmin et, sonra ölç.','Ece’nin boya kalemi kaç santimetre? Cetveli sıfıra hizalayarak ölç.','Piko’nun kalemi ne kadar uzun? Tahminini cetvelle karşılaştır.','Bu kalem kaç santimetre? Önce gözünle tahmin et.','Kalemi ucundan sonuna kadar ölç. Kaç santimetre?'];
const unitFacts:Fact[]=[['Lara masayı 6 karış, babası 4 karış ölçtü. Neden farklı sayılar buldular?','Karışları farklı büyüklükte.',['Masa küçüldü.','Karışla hiç ölçülmez.'],'Herkesin karışı farklı büyüklüktedir. Bu yüzden sonuçlar değişir.','✋'],['Herkesin aynı sonucu bulması için neyle ölçmeliyiz?','Cetvel gibi ortak bir birimle',['Herkes kendi karışıyla','Göz kararıyla'],'Cetveldeki santimetreler herkes için aynıdır.','📏'],['Aynı kitabı ataşla ve kalemle ölçüyoruz. Hangisiyle daha büyük bir sayı buluruz?','Ataşla, çünkü ataş daha kısa.',['Kalemle, çünkü kalem daha uzun.','İkisi hep aynı sayıyı verir.'],'Kısa bir birimle ölçünce onu daha çok kez yan yana koyarız.','📎'],['Sınıfın uzunluğunu adımlarla ölçtük. Öğretmenin adımı ile senin adımın aynı mı?','Hayır, adımlarımız farklı uzunlukta.',['Evet, herkesin adımı aynıdır.'],'Adımlar kişiden kişiye değişir; bu yüzden ortak bir birim gerekir.','👣'],['Cetvelle ölçmeye hangi çizgiden başlarız?','Sıfır çizgisinden',['1 çizgisinden','Cetvelin ortasından'],'Ölçmeye 0 çizgisinden başlarsak doğru sonucu buluruz.'],['Arkadaşın “Kalemim 7 santimetre.” dedi. Sen de cetvelle ölçersen kaç santimetre bulursun?','7 santimetre',['Elime göre değişir.','14 santimetre'],'Santimetre ortak bir birimdir; herkes aynı sonucu bulur.','✏️']];
const massFacts:Fact[]=[['Terazinin bir kefesinde karpuz, diğerinde elma var. Hangi kefe aşağı iner?','Karpuzun olduğu kefe',['Elmanın olduğu kefe','İkisi dengede kalır.'],'Karpuz elmadan ağırdır. Ağır olan taraf aşağı iner.','⚖️'],['Hangisi daha hafiftir: bir tüy mü, bir kitap mı?','Tüy',['Kitap'],'Tüy çok hafiftir; kitap ondan ağırdır.','🪶'],['Aynı büyüklükte iki kutudan biri boş, biri oyuncak dolu. Hangisi daha ağırdır?','Oyuncak dolu kutu',['Boş kutu','İkisi de aynı'],'Kutular aynı büyüklükte olsa da içi dolu olan daha ağırdır.','📦'],['Büyük bir balon mu, küçük bir taş mı daha ağırdır?','Küçük taş',['Büyük balon'],'Büyük görünen her şey ağır değildir. Balonun içinde hava vardır.','🎈'],['Çantanın ağırlığını tahmin ettin. Tahminini nasıl kontrol edersin?','Tartıyla tartarım.',['Rengine bakarım.','Boyunu ölçerim.'],'Ağırlığı tartıyla ölçer, tahminimizle karşılaştırırız.','🎒'],['Kalemin uzunluğunu tahmin ettin. Tahminini nasıl kontrol edersin?','Cetvelle ölçerim.',['Kalemi tartarım.','Rengine bakarım.'],'Uzunluğu cetvelle ölçer, tahminimizle karşılaştırırız.','✏️']];
const solidNames=['Küre','Küp','Silindir','Dikdörtgenler prizması'],solidDrawings=[['sphere','Küre','Top gibi yuvarlaktır; düz yüzü ve köşesi yoktur.'],['cube','Küp','Altı kare yüzü vardır. Yüzler aynı büyüklüktedir.'],['cylinder','Silindir','Altında ve üstünde daire biçimli iki düz yüz, yanında eğri bir yüzey vardır.'],['prism','Dikdörtgenler prizması','Bir kitap kutusu gibi görünür. Yüzleri dikdörtgen biçimindedir.']] as const;
const solidObjects=[['⚽','Futbol topu','Küre','Futbol topu her yönden yuvarlaktır; küreye benzer.'],['🍊','Portakal','Küre','Portakal yuvarlaktır; küreye benzer.'],['🏀','Basketbol topu','Küre','Basketbol topunun düz yüzü ve köşesi yoktur.'],['🎲','Oyun zarı','Küp','Zarın altı eş kare yüzü vardır; küpe benzer.'],['🧊','Buz küpü','Küp','Buz küpünün yüzleri eş karelerdir.'],['🥫','Konserve kutusu','Silindir','Altta ve üstte daire biçimli iki düz yüzü, yanında eğri bir yüzeyi vardır.'],['🔋','Pil','Silindir','Pilin iki ucu daire biçimli düz yüzdür; yanı eğri bir yüzeydir.'],['🕯️','Mum','Silindir','Mumun altı ve üstü daire biçimli, yanı eğri bir yüzeydir.'],['📦','Koli','Dikdörtgenler prizması','Kolinin yüzleri dikdörtgen biçimindedir.'],['🧱','Tuğla','Dikdörtgenler prizması','Tuğlanın yüzleri dikdörtgen biçimindedir.'],['🧃','Meyve suyu kutusu','Dikdörtgenler prizması','Meyve suyu kutusunun yüzleri dikdörtgen biçimindedir.']] as const;
const solidFacts:Fact[]=[['Hangi cismin düz yüzü ve köşesi yoktur?','Küre',solidNames,'Kürenin her yeri yuvarlaktır; düz yüzü ve köşesi yoktur.'],['Hangi cismin altı eş kare yüzü vardır?','Küp',solidNames,'Küpün altı yüzü de aynı büyüklükte karedir.'],['Hangi cisim hem yuvarlanabilir hem de dik durabilir?','Silindir',solidNames,'Silindir yan yatınca yuvarlanır, düz yüzünün üstünde dik durur.'],['Ayakkabı kutusu hangi geometrik cisme benzer?','Dikdörtgenler prizması',solidNames,'Ayakkabı kutusunun yüzleri dikdörtgen biçimindedir.']];
const flatShapes=[['square','karenin','Kare',4],['triangle','üçgenin','Üçgen',3],['rectangle','dikdörtgenin','Dikdörtgen',4],['circle','dairenin','Daire',0]] as const;
const buildFacts:Fact[]=[['Hangisi düz bir yüzü olmadığı için üst üste dizilemez?','Küre',['Küp','Silindir'],'Kürenin düz yüzü yoktur; üstüne bir şey koyunca yuvarlanır.'],['Silindiri yan yatırırsan ne olabilir?','Yuvarlanabilir.',['Küpe dönüşür.','Köşeleri çoğalır.'],'Silindirin yanı eğri bir yüzeydir. Yan yatınca yuvarlanabilir.'],['Bir kulenin en altına hangisini koyarsak kule daha sağlam durur?','Küp',['Küre'],'Küpün düz ve geniş yüzü üstündeki cisimleri taşır. Küre ise yuvarlanır.'],['Ece 3 küpü üst üste, 2 küpü de yan yana dizdi. Kaç küp kullandı?','5',['3','6'],'3 + 2 = 5. Ece 5 küp kullandı.']];
const shapeFacts:Fact[]=[['Bir evin çatısını yapmak için hangi şekli kullanırız?','Üçgen',['Daire','Kare'],'Üçgenin sivri ucu çatıya benzer.'],['Bir arabanın tekerlekleri hangi şekle benzer?','Daire',['Kare','Üçgen'],'Tekerlekler yuvarlaktır; daireye benzer.'],['İki eş kareyi yan yana koyunca hangi şekil oluşur?','Dikdörtgen',['Üçgen','Daire'],'İki eş kare yan yana gelince bir dikdörtgen oluşur.'],['Şekiller birleşip bir model oluşturunca her parçanın biçimi ne olur?','Aynı kalır.',['Hepsi daireye dönüşür.','Kaybolur.'],'Parçalar yeni bir model oluşturur ama her parçanın biçimi aynı kalır.'],['Güneşi çizmek için hangi şekil en uygundur?','Daire',['Üçgen','Dikdörtgen'],'Güneş yuvarlak görünür; onu daireyle çizeriz.'],['Bir kareyi köşeden köşeye kesersen hangi şekiller oluşur?','İki üçgen',['İki daire','İki kare'],'Kareyi köşeden köşeye kesince iki üçgen oluşur.'],['Dört eş kareyi ikişer ikişer yan yana ve alt alta koyunca ne oluşur?','Daha büyük bir kare',['Bir üçgen','Bir daire'],'İki sıra, ikişer kare yan yana gelince daha büyük bir kare oluşur.']];
/** [kap, sıvı, ölçek, ölçeğin belirtme hâli (çoğul), simge] */
const liquidSets=[['sürahi','su','bardak','bardakları','🥛'],['şişe','su','bardak','bardakları','🥛'],['matara','su','bardak','bardakları','🥛'],['termos','çay','fincan','fincanları','☕'],['çaydanlık','çay','çay bardağı','çay bardaklarını','🍵'],['kavanoz','limonata','bardak','bardakları','🥛']] as const;
const liquidFacts:Fact[]=[['Aynı sürahiyi küçük bardakla 6, büyük bardakla 3 kez doldurduk. Neden farklı sayılar bulduk?','Bardakların büyüklüğü farklı.',['Su azaldı.','Yanlış saydık.'],'Büyük bardak daha çok su alır. Bu yüzden daha az bardak yeter.'],['Hangisi daha çok su alır: bir kova mı, bir çay bardağı mı?','Kova',['Çay bardağı'],'Kova çok daha büyük bir kaptır; daha çok su alır.','🪣'],['Sürahi 4 bardak, şişe 2 bardak su alıyor. Hangisi daha çok su alır?','Sürahi',['Şişe'],'4 bardak, 2 bardaktan fazladır. Sürahi daha çok su alır.'],['Sıvıları karşılaştırırken neden aynı büyüklükte bardaklar kullanırız?','Sonuçları karşılaştırabilmek için',['Bardaklar güzel görünsün diye','Su soğusun diye'],'Aynı bardakla ölçünce hangi kabın daha çok aldığını doğru karşılaştırırız.'],['Bir kovayı çay bardağıyla mı, sürahiyle mi daha çok kez doldururuz?','Çay bardağıyla',['Sürahiyle'],'Çay bardağı küçüktür; kovayı doldurmak için onu daha çok kez kullanırız.','🪣'],['Hangisi daha çok su alır: bir yemek kaşığı mı, bir su bardağı mı?','Su bardağı',['Yemek kaşığı'],'Su bardağı kaşıktan büyüktür; daha çok su alır.','🥄']];
const symmetryFacts:Fact[]=[['Simetrik bir şekli ortasından katlarsak ne olur?','İki yarısı üst üste gelir.',['Şekil kaybolur.','Yarılar farklı kalır.'],'Simetrik şekillerde iki taraf birbirinin aynadaki görüntüsüdür; katlayınca üst üste gelir.'],['Kelebeğin iki kanadı birbirine göre nasıldır?','Aynadaki görüntüsü gibi',['Biri büyük, biri küçük','Tamamen farklı'],'Kelebeğin kanatları simetriktir; biri diğerinin aynadaki görüntüsüdür.','🦋'],['Ayna çizgisine yakın bir kare, öbür tarafta nerede olur?','Yine çizgiye yakın',['Çizgiye uzak','Hiç görünmez'],'Yansımada her kare ayna çizgisine aynı uzaklıkta kalır.']];
const surveys=[['En sevdiğin meyve hangisi?',['🍎','Elma'],['🍐','Armut']],['Hangi hayvanı daha çok seviyorsun?',['🐱','Kedi'],['🐶','Köpek']],['Hangi mevsimi daha çok seviyorsun?',['☀️','Yaz'],['❄️','Kış']],['Hangi çiçeği daha güzel buluyorsun?',['🌷','Lale'],['🌹','Gül']],['Hangi taşıtla yolculuk etmek istersin?',['🚂','Tren'],['✈️','Uçak']],['Hangi oyuncakla oynamayı seversin?',['⚽','Top'],['🪁','Uçurtma']]] as const;
/** Hikâye sorularında metinde hiç geçmeyen, açıkça yanlış seçenekler. */
const decoys={place:['Spor salonunda','Marketin önünde','Hastanede','Havuzda','Sinemada','Deniz kıyısında','Hayvanat bahçesinde','Pazar yerinde'],title:['Kaybolan Anahtar','Kış Tatili','Ormandaki Kedi','Denizdeki Balon','Karlı Dağ','Uyuyan Ayı','Sihirli Fener','Kayıp Eldiven'],meaning:['Bir şeyi saklayıp unutmak','Bir yerden başka yere gitmek','Çok hızlı koşmak','Yüksek sesle bağırmak','Soğuk bir kış günü','Büyük bir taş'],cause:['Okula geç kalmamak için','Hediye almak için','Uyumak için','Televizyon izlemek için','Kar topu oynamak için','Alışverişe gitmek için'],fact:['Çocuklar dondurma aldı.','O gün kar yağıyordu.','Lara bisiklet sürdü.','Çocuklar denize girdi.','Herkes sinemaya gitti.','Ece bir kedi buldu.'],ending:['uçurtma.','masada.','mavi.','pencereden.','ağaçlar.','sabah.','kalemler.','bahçede.']};
const reflections={drawing:['Resminde hangi şekilleri kullandığını anlat.','Seçtiğin iki rengin adını söyle.','Resminde en sevdiğin yeri göster ve anlat.','Bir dahaki denemede neyi farklı yapmak istersin?','Resmini bir yetişkine anlat. Birlikte resmin hakkında konuşun.','Resmindeki renklerden hangisi en çok dikkat çekiyor? Neden?','Resmine bir ad ver. Bu adı neden seçtiğini söyle.','Resminde hangi çizgileri kullandın: düz mü, dalgalı mı, kıvrımlı mı?'],physicalTask:['Hareket ettiğin alan güvenli miydi? Nasıl kontrol ettin?','Hareketten sonra nefesinde bir değişiklik fark ettin mi?','En rahat yaptığın hareket hangisiydi?','Dinlenmeye ihtiyaç duyduğunda ne yaptın?','Bir sonraki hareket molanda ne yapmak istersin?','Hareket ederken bedeninin hangi bölümlerini kullandın?','Hareketten önce ve sonra kendini nasıl hissettin?','Bu hareketi bir arkadaşına nasıl anlatırsın?'],speaking:['Anlatmaya başlamadan önce ne düşündüğünü söyle.','Sözcüklerini anlaşılır söyleyebildin mi? Kendini dinle.','Anlatımında önce ve sonra olanları sırayla söyle.','Bir dahaki denemende neyi geliştirmek istersin?','Bir yetişkinle paylaş: Çalışmanın en sevdiğin kısmı neydi?','Anlatırken sesin, dinleyenin rahatça duyacağı kadar yüksek miydi?','Hikâyedeki bir kişiyi seç. O kişinin ne hissettiğini anlat.','Anlatımında yeni öğrendiğin bir sözcüğü kullandın mı? Hangisi?'],song:['Şarkıyı söylerken nefesini nasıl kullandın? Zorlandığın bir yer oldu mu?','Şarkının en sevdiğin sözü hangisiydi?','Filizin büyümesini hangi hareketlerle gösterdin?','Şarkıyı yavaş mı, hızlı mı söylemek daha hoşuna gitti?','Şarkıyı bir yetişkinle birlikte söyle. Birlikte söylemek nasıldı?','Şarkıya yeni bir söz eklemek istesen ne eklerdin?','Şarkı söylerken bedenin rahat mıydı? Omuzlarını gevşettin mi?']};
/** İnce/kalın ses çiftleri (Hz) ile tempo çiftleri (vuruş arası, ms); sorular [yönerge, ince/hızlı mı] biçiminde. */
const pitchPairs=[[175,698],[185,740],[196,784],[208,831],[220,660],[233,932],[247,740],[262,523],[294,880],[330,990]] as const,pitchAsks=[['İki sesi dinle. Hangisi daha ince?',true],['Kuş cıvıltısı gibi ince olan ses hangisi?',true],['Minik bir fare gibi ince olan ses hangisi?',true],['Zil sesi gibi ince olan ses hangisi?',true],['Ses merdiveninde daha yukarıdaki ses hangisi?',true],['İki sesi dinle. Hangisi daha kalın?',false],['Büyük bir davul gibi kalın olan ses hangisi?',false],['Ayı homurtusu gibi kalın olan ses hangisi?',false],['Fil gibi kalın olan ses hangisi?',false],['Ses merdiveninde daha aşağıdaki ses hangisi?',false]] as const;
const tempoPairs=[[300,700],[320,760],[340,780],[350,820],[360,860],[380,820],[400,880],[420,900],[450,950],[480,1000]] as const,tempoAsks=[['İki örneği dinle ya da ışıklarını izle. Hangisi daha hızlı?',true],['Tavşan hızlı koşar. Hangi örnek tavşan gibi hızlı?',true],['Hangi örnekte vuruşlar daha hızlı geliyor?',true],['Koşan bir at gibi hızlı olan örnek hangisi?',true],['Hangi örnekte ışıklar daha hızlı yanıp sönüyor?',true],['İki örneği dinle ya da ışıklarını izle. Hangisi daha yavaş?',false],['Kaplumbağa yavaş yürür. Hangi örnek kaplumbağa gibi yavaş?',false],['Hangi örnekte vuruşlar daha yavaş geliyor?',false],['Salyangoz gibi yavaş olan örnek hangisi?',false],['Hangi örnekte ışıklar daha yavaş yanıp sönüyor?',false]] as const;
/** Dört vuruşluk, en az iki alkışlı bütün ritimler. */
const rhythms=Array.from({length:16},(_,m)=>[3,2,1,0].map(b=>m>>b&1?'👏':'—')).filter(p=>p.filter(x=>x==='👏').length>=2);
/** Aynı turda tekrarı yakalayan kimlikler: üretici özler (key) verdiyse onlar, yoksa yönerge ve görsel. Sıralama kartları karışık gelir, sırası sayılmaz. */
export const questionKeys=(q:Question)=>q.key??[[q.type,q.instruction,q.visual,q.value,q.start,(q.type==='ordering'?[...q.items??[]].sort():q.items)?.join('|')].join('¦')];
/** Öğren ekranındaki keşif aracı sabit tohumla gelir; tur soruları onu tekrar etmez. */
export const previewQuestion=(l:Lesson)=>l.kind==='geometry'?makeQuestion(l,0,1,24):null;
/** Bir ders turunda, o turda gösterilen soruların (seen: questionKeys) hiçbirini tekrar etmeyen soruyu üretir. */
export function nextQuestion(l:Lesson,index:number,difficulty:1|2|3,seed:number,seen:readonly string[]){const repeats=(q:Question)=>questionKeys(q).some(k=>seen.includes(k));let q=makeQuestion(l,index,difficulty,seed);for(let attempt=1;attempt<100&&repeats(q);attempt++)q=makeQuestion(l,index,difficulty,seed,attempt);return q}
export function makeQuestion(l:Lesson,index:number,difficulty:1|2|3=1,seed=1,attempt=0):Question{
 const random=rng(seed+index*311+attempt*104729),int=(a:number,b:number)=>a+Math.floor(random()*(b-a+1)),one=<T,>(items:readonly T[])=>items[Math.floor(random()*items.length)];
 /** Tur destesi: aynı turda her index farklı öğe alır. Yeniden denemede sayılar her seferinde, deste dört denemede bir sıradaki öğeye geçer; yönerge biçimi (phrase) index’e bağlı kalır. İlk soru dersin ana aracıdır. */
 const draw=<T,>(items:readonly T[],salt=0)=>pick(items,index,seed+salt,Math.floor(attempt/4)),phrase=(items:readonly string[],salt:number)=>pick(items,index,seed+salt),pickTask=<T,>(first:T,tasks:readonly T[])=>index===0?first:draw(tasks,7);
 /** Sonlu görev destesi: ilk soru ana araçtan (first), sonrakiler dersin bütün görevlerinden (all). */
 const deal=(first:readonly (()=>Question)[],all:readonly (()=>Question)[])=>(index===0?draw(first,7):draw(all,8))();
 const q:Question={id:`${l.id}-${seed}-${index}`,type:l.kind,instruction:'',answer:'',hints:[l.learn[0],l.learn[l.learn.length-1]],explanation:'',skill:l.outcomes[0],difficulty};
 const set=(instruction:string,answer:string|number,explanation:string,options?:readonly string[])=>{q.instruction=instruction;q.answer=String(answer);q.explanation=explanation;if(options)q.options=shuffle([...new Set([q.answer,...options])],random);return q};
 const choices=(instruction:string,answer:string|number,explanation:string,options?:readonly string[])=>{q.type='choice';return set(instruction,answer,explanation,options??[String(Number(answer)+1),String(Math.max(0,Number(answer)-1))])};
 const fact=([instruction,answer,wrong,explanation,visual]:Fact)=>{if(visual)q.visual=visual;return choices(instruction,answer,explanation,wrong)};
 if(l.questions){const src=draw(l.questions);return {...src,id:q.id,options:src.options?shuffle(src.options,random):undefined};}
 if(l.subject==='math'){
 const a=int(1,difficulty===1?3:difficulty===2?6:9)*10+int(0,9),b=int(1,9),k=l.generator;
 if(k==='blocks'||k==='count'||k==='add'){
  const left=k==='add'?Math.min(a,79):a,n=k==='add'?left+b+10:a,desc=k==='add'?`${left} + ${b+10}`:`${n}`;q.value=n;q.key=[desc];
  if(k==='count'){const word=numberWord(n),flip=n%10&&n%10!==Math.floor(n/10)?n%10*10+Math.floor(n/10):n+1,near=n+10>99?n-10:n+10;
   if(index%3===2)return index%2?choices(`${n} sayısı nasıl okunur?`,word,`${n}: ${Math.floor(n/10)} onluk ${n%10} birlik. “${word}” diye okunur.`,[numberWord(flip),numberWord(near)]):choices(`“${word}” nasıl yazılır?`,n,`“${word}”: ${Math.floor(n/10)} onluk ${n%10} birlik, yani ${n}.`,[String(flip),String(near)]);
   q.type='baseTenBlocks';return set(`“${word}” sayısını bloklarla göster.`,n,`“${word}” ${Math.floor(n/10)} onluk ve ${n%10} birliktir: ${n}.`);}
  if(index%3===2){return choices(`${desc} ${k==='add'?'işleminin sonucunda':'sayısında'} kaç onluk var?`,Math.floor(n/10),`${n} içinde ${Math.floor(n/10)} onluk, ${n%10} birlik var.`,[String(Math.floor(n/10)+1),String(Math.max(0,Math.floor(n/10)-1))]);}
  q.type='baseTenBlocks';if(k==='add'&&index%3===1)return set(`${one(addStories)(left,b+10)} Bloklarla bul.`,n,`${left} + ${b+10} = ${n}. ${Math.floor(n/10)} onluk ve ${n%10} birlik, ${n} eder.`);
  return set(`${k==='add'?`${desc} işlemini yap.`:`${n} sayısını kur.`} Blokları çalışma alanına taşı.`,n,`${Math.floor(n/10)} onluk ve ${n%10} birlik, ${n} eder.`);
 }
 if(k==='order'){const t=pickTask('line',['line','sort','compare','neighbor'] as const);
  if(t==='line'){const start=int(0,8)*10,count=int(1,9),answer=start+count;q.start=start;q.step=1;q.value=count;return set(`${start} ile ${start+10} arasında ${answer} sayısına git.`,answer,`${start} + ${count} = ${answer}. Her zıplayış 1 adım.`);}
  q.hints=['Önce onluklara bak. Onluğu küçük olan sayı daha küçüktür.','Onluklar aynıysa birliklere bak.'];
  if(t==='sort'){const nums=new Set<number>();while(nums.size<(difficulty===1?3:4))nums.add(int(10,difficulty===1?50:99));const up=random()<.5,sorted=[...nums].sort((x,y)=>up?x-y:y-x).map(String);let items=shuffle(sorted,random);if(items.join()===sorted.join())items=[...items.slice(1),items[0]];q.type='ordering';q.items=items;q.key=[`sort${up}`];return set(`Sayıları ${up?'küçükten büyüğe':'büyükten küçüğe'} sırala.`,sorted.join('|'),sorted.join(up?' < ':' > '));}
  if(t==='compare'){const x=int(12,98),swap=x%10*10+Math.floor(x/10),y=swap>=10&&swap!==x?swap:x>50?x-int(1,9):x+int(1,9),big=random()<.5;return choices(`${x} ile ${y} sayılarından hangisi daha ${big?'büyük':'küçük'}?`,big?Math.max(x,y):Math.min(x,y),`${Math.max(x,y)} > ${Math.min(x,y)}. Önce onluklara, onluklar aynıysa birliklere bakarız.`,[String(x),String(y)]);}
  const n=int(11,98),after=random()<.5,answer=after?n+1:n-1;q.hints=['Sayı doğrusunu düşün: bir sağdaki sayı bir fazladır.','Bir soldaki sayı bir eksiktir.'];return choices(`${withSuffix(n,'den')} hemen ${after?'sonra':'önce'} hangi sayı gelir?`,answer,`Sayı doğrusunda bir adım ${after?'sağa':'sola'} gideriz: ${answer}.`,[String(after?n-1:n+1),String(answer+(after?10:-10))]);
 }
 if(k==='skip'){const t=pickTask('forward',['forward','backward','tens'] as const),step=one([2,3,4,5]);
  if(t==='tens'){const up=random()<.5,start=up?int(10,59):int(50,99),seq=[0,1,2].map(i=>start+(up?10:-10)*i),next=seq[2]+(up?10:-10);q.key=[`tens${up?'+':'−'}`];q.hints=['Onar sayarken onlar basamağı birer birer değişir.','Birler basamağı hiç değişmez.'];return choices(`10’ar ${up?'ileri':'geri'} sayıyoruz: ${seq.join(', ')}, … Sonra hangi sayı gelir?`,next,`${seq[2]} ${up?'+':'−'} 10 = ${next}. Onar sayarken birler basamağı aynı kalır.`,[String(next+(up?1:-1)),String(seq[2]+(up?1:-1)),String(next+(up?10:-10))]);}
  const back=t==='backward',count=back?int(2,Math.floor(10/step)):int(2,difficulty===1?4:5),start=back?step*count+int(0,difficulty===1?6:14):random()<.5?step*int(0,3):int(1,9),path=Array.from({length:count+1},(_,i)=>start+(back?-step:step)*i);q.start=start;q.step=back?-step:step;q.value=count;
  return set(`${withSuffix(start,'den')} başla. ${withSuffix(step,'er')} ${count} kez ${back?'geri':'ileri'} zıpla.`,path[count],`${path.join(', ')}. Her zıplayış ${step} adım.`);
 }
 if(k==='subtract'){const start=int(6,difficulty===1?15:difficulty===2?20:30),count=int(2,Math.min(start-1,difficulty===1?5:difficulty===2?7:9)),answer=start-count;q.start=start;q.step=-1;q.value=count;q.key=[`${start}-${count}`];
  return set(index%2?`${one(takeStories)(start,count)} Sayı doğrusunda geri zıplayarak bul.`:`${withSuffix(start,'den')} başla. 1’er ${count} kez geri zıpla.`,answer,`${start} − ${count} = ${answer}. ${count} adım geri gittik.`);
 }
 if(k==='mental'){const t=pickTask('ten',['ten','down','tens','estimate'] as const);
  if(t==='ten'||t==='down'){const x=int(5,9),y=int(11-x,9),sum=x+y,over=sum-10;q.key=[`${x}+${y}`];q.value=y;
   if(t==='ten'){q.start=x;q.step=1;q.hints=[`${withSuffix(x,'e')} önce ${10-x} ekle: 10.`,`10’a kalan ${over} adımı da ekle: ${sum}.`];return set(`${x} + ${y} kaç eder? Önce 10’a tamamla, sonra kalanı ekle. Piko’yu sonuca zıplat.`,sum,`${x} + ${10-x} = 10, 10 + ${over} = ${sum}. 10’a tamamlamak işi kolaylaştırır.`);}
   q.start=sum;q.step=-1;q.hints=[`${withSuffix(sum,'den')} önce ${over} adım geri git: 10.`,`Kalan ${10-x} adım daha geri git: ${x}.`];return set(`${sum} − ${y} kaç eder? Önce 10’a in, sonra kalanını çıkar. Piko’yu sonuca zıplat.`,x,`${sum} − ${over} = 10, 10 − ${10-x} = ${x}. Önce 10’a inmek işi kolaylaştırır.`);}
  if(t==='tens'){const x=int(1,8),y=int(1,9-x),add=random()<.5;q.key=[`tens:${x}:${y}`];return add?choices(`${x*10} + ${y*10} kaç eder? Onlukları düşün.`,(x+y)*10,`${x} onluk ile ${y} onluk ${x+y} onluk eder: ${(x+y)*10}.`,[String((x+y)*10+10),String((x+y)*10-10)]):choices(`${(x+y)*10} − ${y*10} kaç eder? Onlukları düşün.`,x*10,`${x+y} onluktan ${y} onluk çıkınca ${x} onluk kalır: ${x*10}.`,[String(x*10+10),String(y*10===x*10?x*10+20:y*10)]);}
  const round=(n:number)=>Math.round(n/10)*10;let x=0,y=0;do{x=int(11,48);y=int(11,48)}while(x%5===0||y%5===0||round(x)+round(y)>90);const est=round(x)+round(y);q.hints=[`Her sayıya en yakın onluğu bul: ${x} için ${round(x)}.`,'Yuvarladığın onlukları topla.'];
  return choices(`${x} + ${y} işleminin sonucu yaklaşık kaçtır? Sayıları en yakın onluğa yuvarla.`,`Yaklaşık ${est}`,`${x} yaklaşık ${round(x)}, ${y} yaklaşık ${round(y)}. ${round(x)} + ${round(y)} = ${est}. Gerçek sonuç ${x+y}${x+y===est?'; tahminimizle aynı':', tahminimize yakın'}.`,[`Yaklaşık ${est+20}`,`Yaklaşık ${est>=30?est-20:est+30}`]);
 }
 if(k==='inverse'){const x=int(5,20),y=int(1,9),z=x+y,t=pickTask('undo',['undo','check','missing'] as const);q.key=[`a${x}`,`b${z}`];
  if(t==='check')return choices(`${z} − ${y} = ${x}. Bunu toplamayla kontrol edelim: ${x} + ${y} kaç eder?`,z,`Çıkardığımız ${withSuffix(y,'i')} geri ekleyince başladığımız ${z} sayısına döneriz.`);
  if(t==='missing')return choices(`${x} + ? = ${z}. Soru işaretinin yerine hangi sayı gelmeli?`,y,`${z} − ${x} = ${y}. Toplama ile çıkarma birbirini kontrol eder.`);
  return choices(`${x} + ${y} = ${z}. Peki ${z} − ${y} kaç eder?`,x,`Topladığımız ${withSuffix(y,'i')} çıkarınca başlangıçtaki ${x} kalır.`);
 }
 if(k==='multiply'||k==='divide'||k==='multimental'){const [box,of,to,emoji,item]=draw(groupThings,3),groups=int(2,difficulty===1?4:5),each=k==='multimental'?one([2,3,4,5,10]):int(2,difficulty===3?6:5),total=groups*each,adds=Array(groups).fill(each).join(' + ');
  if(k==='divide'){q.key=[`${total}:${Math.min(groups,each)}`,box];
   if(pickTask('share',['share','group','share'] as const)==='group'){q.visual=`pile:${emoji}:${total}`;return choices(`${total} ${item}, her ${to} ${each} tane olacak şekilde yerleştirilecek. Kaç ${box} gerekir?`,groups,`${total} ${item} ${withSuffix(each,'er')} ayrılınca ${groups} grup olur: ${adds} = ${total}. Kısaca ${total} ÷ ${each} = ${groups}.`);}
   q.visual=`share:${emoji}:${total}:${groups}`;return choices(`${total} ${item} ${groups} ${to} eşit paylaştırılacak. Her ${to} kaç ${item} düşer?`,each,`${total} ${item} ${groups} ${to} birer birer dağıtılınca her birine ${each} tane düşer: ${adds} = ${total}. Kısaca ${total} ÷ ${groups} = ${each}.`);}
  if(k==='multiply'){q.visual=`groups:${emoji}:${groups}x${each}`;q.key=[`${groups}x${each}`,box];
   if(pickTask('total',['total','adds','total'] as const)==='adds')return choices(`${groups} ${of} her birinde ${each} ${item} var. Bunu hangi toplama işlemi anlatır?`,adds,`${groups} tane ${each}: ${adds} = ${total}. Kısaca ${groups} × ${each} diye yazılır.`,[`${groups} + ${each}`,Array(groups+1).fill(each).join(' + ')]);
   return choices(`${groups} ${of} her birinde ${each} ${item} var. Toplam kaç ${item}?`,total,`${adds} = ${total}. ${groups} tane ${each}, kısaca ${groups} × ${each} = ${total} diye yazılır.`);}
  const t=pickTask('skip',['skip','split','relate','skip'] as const);q.key=[`${Math.min(groups,each)}x${Math.max(groups,each)}`];
  if(t==='split')return choices(`${withSuffix(total,'i')} ${groups} eş gruba ayırırsan her grupta kaç olur?`,each,`${groups} tane ${each}, ${total} eder. Bu yüzden ${total} eş ${groups} gruba ayrılınca her grupta ${each} olur.`);
  if(t==='relate')return choices(`${groups} tane ${each}, ${total} eder. O hâlde ${total} içinde kaç tane ${each} vardır?`,groups,`${adds} = ${total}. ${total} içinde ${groups} tane ${each} vardır.`);
  return choices(`${groups} tane ${each} kaç eder? ${withSuffix(each,'er')} sayarak bul.`,total,`${Array.from({length:groups},(_,i)=>each*(i+1)).join(', ')} diye saydık. ${groups} × ${each} = ${total}.`);
 }
 if(k==='balance'){const t=pickTask('right',['right','left','check','right'] as const),x=int(2,9),y=int(1,9),sum=x+y;let c=int(1,sum-1);if(c===x)c=c>1?c-1:c+1;
  if(t==='check'){const truth=random()<.5,d=truth?sum-c:sum-c+(sum-c>2?one([-2,-1,1,2]):one([1,2]));return choices(`${x} + ${y} = ${c} + ${d} eşitliği doğru mu?`,truth?'Doğru':'Yanlış',`Solda ${sum}, sağda ${c+d} var. ${truth?'İki taraf eşit; eşitlik doğru.':'İki taraf eşit değil; eşitlik yanlış.'}`,['Doğru','Yanlış']);}
  if(t==='left')return choices(`? + ${y} = ${c} + ${sum-c}. Dengeyi tamamla.`,x,`Sağda ${c} + ${sum-c} = ${sum} var. ${withSuffix(y,'e')} ${x} eklenince solda da ${sum} olur.`);
  return choices(`${x} + ${y} = ${c} + ? Dengeyi tamamla.`,sum-c,`Solda ${sum} var. Sağda da ${sum} olması için ${withSuffix(c,'e')} ${sum-c} eklenir.`);
 }
 if(k==='pattern'){const t=pickTask('next',['next','missing','shape','shapeMissing'] as const);
  if(t==='shape'||t==='shapeMissing'){const symbols=draw(shapeSets,5),unit=one(patternUnits).map(i=>symbols[i]),length=unit.length*2+int(1,unit.length),seq=Array.from({length},(_,i)=>unit[i%unit.length]);q.hints=['Baştan başla: hangi şekiller aynı sırayla yeniden geliyor?','Tekrar eden birimi parmağınla göster, sonra devam ettir.'];
   if(t==='shape'){const next=unit[length%unit.length];return choices(`${seq.join(' ')} … Sıradaki hangisi?`,next,`Tekrar eden birim: ${unit.join(' ')}. Sıradaki ${next}.`,symbols);}
   const miss=int(unit.length,length-1);return choices(`${seq.map((s,i)=>i===miss?'__':s).join(' ')} Boşluğa hangisi gelmeli?`,seq[miss],`Tekrar eden birim: ${unit.join(' ')}. Boşluğa ${seq[miss]} gelir.`,symbols);}
  const step=one([2,3,4,5]),up=random()<.65,first=up?step*int(1,3):step*int(5,8),seq=Array.from({length:5},(_,i)=>first+(up?i:-i)*step),rule=`Her adımda ${step} ${up?'eklenir':'çıkarılır'}.`;q.hints=['Yan yana iki sayıya bak: her adımda kaç artıyor ya da azalıyor?',rule];q.key=[seq.join(',')];
  if(t==='next')return choices(`${seq.slice(0,4).join(', ')}, … Sıradaki sayı hangisi?`,seq[4],`${rule} ${seq[3]} ${up?'+':'−'} ${step} = ${seq[4]}.`,[String(seq[4]+(up?1:-1)),String(seq[4]+(up?step:-step)),String(seq[3])]);
  const miss=int(1,3);return choices(`${seq.map((n,i)=>i===miss?'__':n).join(', ')} Boşluğa hangi sayı gelmeli?`,seq[miss],`${rule} Boşluktaki sayı ${seq[miss]}.`,[String(seq[miss]+1),String(seq[miss]-1),String(seq[miss]+step)]);
 }
 if(k==='estimate'){const [emoji,name]=draw(countables,5),n=int(10,difficulty===1?30:difficulty===2?40:50);q.visual=`count:${emoji}:${n}`;q.key=[String(n),name];return choices(`Önce tahmin et, sonra beşer sayarak kontrol et. Kaç ${name} var?`,n,`${Math.floor(n/5)} tane beşli grup${n%5?` ve ${n%5} tane daha`:''} var. Toplam ${n} ${name}.`,[String(n+10),String(n-5)]);}
 if(k==='fractions'){const tools=fractionTools.map(([instruction,count,explanation])=>()=>{q.value=count;return set(instruction,count,explanation)});return deal(tools,[...tools,...fractionFacts.map(f=>()=>fact(f))]);}
 if(k==='money'){const coins=[50,75,100,125,150,175,200,225,250,300].map(value=>()=>{let parts=[...Array.from({length:Math.floor(value/100)},()=>100),...(value%100>=50?[50]:[]),...(value%50?[25]:[])];if(parts.length===1)parts=[parts[0]/2,parts[0]/2];q.value=value;q.key=[String(value)];return set(one(moneyAsks)(value),value,`Örneğin ${parts.join(' + ')} = ${value} kuruş. 100 kuruş = 1 TL.`)});
  return deal(coins,[...coins,...moneyFacts.map(f=>()=>fact(f))]);
 }
 if(k==='clock'){const h=int(1,11),m=one([0,30,15,45]),time=`${h}.${String(m).padStart(2,'0')}`;q.value=h*60+m;q.key=[time];return set(one(clockAsks)(time),q.value,`Akrep ${h}${m?' ile '+(h+1)+' arasında':''}, yelkovan ${m===0?'12':m/5} üzerinde olmalı.`);}
 if(k==='calendar'){const [kind,i]=index===0?draw(calendarOrders,11):draw(calendarTasks,12);
  if(kind==='fact')return fact(calendarFacts[i]);
  if(kind==='after'||kind==='before'){const after=kind==='after',d=(i+(after?1:6))%7;q.key=[kind];return choices(`${dayFrom[i]} ${after?'sonra':'önce'} hangi gün gelir?`,days[d],`Günlerin sırası: ${days.join(', ')}. ${dayFrom[i]} ${after?'sonra':'önce'} ${days[d]} gelir.`,[days[i],days[(i+(after?2:5))%7]]);}
  const arr=kind==='seasons'?[0,1,2,3].map(j=>seasons[(i+j)%4]):(kind==='days'?days:months).slice(i,i+3);let items=shuffle(arr,random);if(items.join()===arr.join())items=[...items.slice(1),items[0]];q.type='ordering';q.items=items;if(kind!=='seasons')q.key=[`${kind}${i%3}`];
  return set(kind==='days'?['Bu günleri oluş sırasına koy.','Günleri haftadaki sırasıyla diz.','Hangi gün önce gelir? Günleri sıraya koy.'][i%3]:kind==='months'?['Bu ayları yıl içindeki sırasına koy.','Ayları takvimdeki sırasıyla diz.','Hangi ay önce gelir? Ayları sıraya koy.'][i%3]:`${seasonFrom[i]} başlayarak mevsimleri sıraya koy.`,arr.join('|'),arr.join(' → '));
 }
 if(k==='measure'||k==='length'){const rulers=[3,4,5,6,7,8,9,10].map(n=>()=>{q.value=n;q.key=[`ruler:${n}`];q.type='measure';return set(phrase(rulerAsks,23),n,`Kalem sıfırdan başlıyor, ${n} çizgisinde bitiyor. Uzunluğu ${n} cm.`)});
  if(k==='measure'){const units=unitFacts.map(f=>()=>fact(f));return deal(units,[...rulers,...units]);}
  const compare=()=>{const est=int(3,9),real=Math.max(2,est+one([-3,-2,-1,1,2,3])),name=one(['Ece','Can','Deniz','Lara']),diff=Math.abs(real-est),less=real>est;q.key=[`${est}:${real}`];return choices(`${name}, kalemin ${est} cm olduğunu tahmin etti. Cetvelle ölçünce ${real} cm buldu. Tahmini ölçümden kaç santimetre ${less?'az':'fazla'}?`,diff,`${Math.max(real,est)} − ${Math.min(real,est)} = ${diff}. Tahmin ölçümden ${diff} cm ${less?'az':'fazla'}.`)};
  const closer=()=>{const real=int(5,12),near=real+one([-1,1]),far=real+one([-4,-3,3,4]),close=one(['Ece','Can']),other=close==='Ece'?'Can':'Ece',first=random()<.5;return choices(`${first?close:other} ${first?near:far} cm, ${first?other:close} ${first?far:near} cm tahmin etti. Kurdele ölçülünce ${real} cm çıktı. Kimin tahmini ölçüme daha yakın?`,close,`${close} yalnızca ${Math.abs(near-real)} cm, ${other} ${Math.abs(far-real)} cm yanıldı.`,[close,other])};
  return deal(rulers,[...rulers,compare,closer,...massFacts.map(f=>()=>{q.hints=['Terazide ağır olan taraf aşağı iner.','Büyük görünen her şey ağır olmayabilir; içinde ne olduğunu düşün.'];return fact(f)})]);
 }
 if(k==='solids'){const drawings=solidDrawings.map(([shape,name,explanation],i)=>()=>{q.type='geometry';q.items=[shape];return set(['Çizimi incele. Bu geometrik cismin adı ne?','Bu çizimdeki cisim hangisi?','Çizimdeki cismin yüzlerine bak. Bu hangi cisim?','Bu geometrik cismi tanıyor musun? Adını seç.'][i],name,explanation,solidNames)});
  return deal(drawings,[...drawings,...solidObjects.map(([emoji,thing,name,explanation])=>()=>{q.visual=emoji;return choices(`${thing} hangi geometrik cisme benzer?`,name,explanation,solidNames)}),...solidFacts.map(f=>()=>fact(f))]);
 }
 if(k==='rotate'){q.type='geometry';q.hints=['Şekli istediğin kadar döndürebilirsin. Kenarların birleştiği yerlere bak.','Her köşeye bir kez dokun. Dairenin köşesi yoktur.'];const polygons=flatShapes.slice(0,3),corners=(resize:boolean)=>flatShapes.map(([shape,of,,n])=>()=>{q.items=[shape];q.key=[`corners:${shape}`];return set(resize?`Şekli büyüt ve küçült, sonra köşelerine dokun. Bu ${of} kaç köşesi var?`:`Şekli döndür ve incele. Bu ${of} kaç köşesi var?`,n,`Yönü veya büyüklüğü değişince şeklin köşe sayısı değişmez. Bu şeklin ${n} köşesi var.`,['0','3','4'])});
  return deal(corners(false),[...corners(false),...corners(true),...polygons.map(([shape,of,name,n])=>()=>{q.items=[shape];q.hints=['Şeklin kenarlarını parmağınla takip et.','Her düz kenarı bir kez say. Döndürmek kenar sayısını değiştirmez.'];return set(`Şekli döndür. Bu ${of} kaç kenarı var?`,n,`Döndürünce kenar sayısı değişmez. ${name} ${n} kenarlıdır.`,['0','3','4'])}),...flatShapes.map(([shape,,name])=>()=>{q.items=[shape];q.key=['rotate:name'];return set('Şekli iki kez sağa döndür. Döndürünce bu şeklin adı ne olur?',name,`Döndürmek şeklin adını değiştirmez. Bu şekil yine bir ${name.toLocaleLowerCase('tr-TR')}.`,['Kare','Üçgen','Dikdörtgen','Daire'])}),...polygons.map(([shape,of,name,n])=>()=>{q.items=[shape];q.key=['rotate:size'];return set(`Şekli büyüt ve küçült. Bu ${of} köşe sayısı değişir mi?`,'Hayır, aynı kalır.',`Büyüklük değişince köşe sayısı değişmez. ${name} yine ${n} köşelidir.`,['Hayır, aynı kalır.','Evet, artar.','Evet, azalır.'])})]);
 }
 if(k==='build'||k==='shapes'){const mode=k==='build'?'build':'compose',plans=compositionPlans[mode].map((plan,v)=>()=>{q.type='geometry';q.visual=mode;q.value=v;q.key=[`${mode}:${v}`];return set(plan.instruction,'done',plan.explanation)});
  return deal(plans,[...plans,...(k==='build'?buildFacts:shapeFacts).map(f=>()=>fact(f))]);
 }
 if(k==='symmetry'){const mirror=()=>{const cells=shuffle([...Array(12).keys()],random).slice(0,int(difficulty===1?3:4,difficulty===1?4:difficulty===2?5:6)).sort((x,y)=>x-y);q.type='geometry';q.visual='symmetry';q.items=cells.map(String);const mirrored=cells.map(i=>Math.floor(i/3)*3+2-i%3).sort((x,y)=>x-y);q.hints=['Aynanın yanındaki kareye bak. Karşılığı da aynanın hemen yanında olmalı.','Her satırı ayrı düşün. Çizgiye uzak kare, sağda da çizgiye uzak kalır.'];return set(phrase(['Soldaki deseni aynadaki gibi sağ tarafa tamamla.','Sağ tarafı boya: soldaki desenin aynadaki görüntüsü olsun.','Deseni ayna çizgisinin öbür yanına yansıt.','Ayna çizgisine bak. Sağdaki kareleri soldaki desene göre boya.','Kelebeğin kanatları gibi olsun: sağ tarafı, soldakinin aynadaki görüntüsü olarak boya.','Soldaki boyalı karelerin sağdaki yansımasını boya.','Ayna çizgisine yakın kareler öbür yanda da yakın olur. Deseni tamamla.','Soldaki desen aynaya bakıyor. Aynadaki görüntüsünü sağa boya.'],24),mirrored.join('|'),'İki taraftaki boyalı karelerin ayna çizgisine uzaklığı aynıdır.')};
  return deal([mirror],[...Array.from({length:6},()=>mirror),...symmetryFacts.map(f=>()=>fact(f))]);
 }
 if(k==='liquid'){const cups=liquidSets.map(([box,drink,cup,cupsAcc,emoji])=>()=>{const n=int(2,difficulty===1?5:difficulty===2?6:8);q.visual=emoji.repeat(n);q.key=[box];return choices(`Bir ${box} ${drink}, bu eş ${cupsAcc} doldurdu. Önce tahmin et: ${box} kaç ${cup} ${drink} alır?`,n,`Aynı büyüklükte ${n} ${cup} doldu. Bu ${box} ${n} ${cup} ${drink} alır.`)});
  return deal(cups,[...cups,...liquidFacts.map(f=>()=>fact(f))]);
 }
 if(k==='directions'){const names:Record<string,string>={R:'Sağa',L:'Sola',U:'Yukarı',D:'Aşağı'},moves:Record<string,[number,number]>={R:[1,0],L:[-1,0],U:[0,-1],D:[0,1]};const vertical=(d:string)=>moves[d][0]===0;let route='',sx=0,sy=3;
  for(let tries=0;tries<400&&!route;tries++){const segments=difficulty===1?2:int(2,3),path:string[]=[];let x=int(0,4),y=int(0,3),prev='';sx=x;sy=y;const visited=new Set([`${x},${y}`]);
   while(path.length<segments){const dir=one(['R','L','U','D'].filter(d=>!prev||vertical(d)!==vertical(prev))),len=int(1,3);let ok=true;for(let i=0;i<len&&ok;i++){x+=moves[dir][0];y+=moves[dir][1];ok=x>=0&&x<5&&y>=0&&y<4&&!visited.has(`${x},${y}`);visited.add(`${x},${y}`)}if(!ok)break;path.push(`${dir}${len}`);prev=dir}
   if(path.length===segments&&new Set(path).size===segments)route=path.join(',')}
  if(!route){route='R2,U2';sx=0;sy=3}
  const steps=route.split(',').map(s=>`${names[s[0]]} ${s.slice(1)} adım`);let items=shuffle(steps,random);if(items.join('|')===steps.join('|'))items=[...items.slice(1),items[0]];q.visual=`route:${sx},${sy}:${route}`;q.items=items;q.hints=['Piko’nun durduğu kareden başla. İlk önce hangi yöne gidiyor?','Yol her döndüğünde yeni bir kart başlar. Her yönde kaç kare gittiğini say.'];return set(phrase(['Haritadaki noktalı yolu izle. Piko’nun evine giden yol tarifi kartlarını sıraya diz.','Piko evine dönüyor. Noktalı yolu takip et ve kartları sıraya koy.','Yol tarifini kur: kartları Piko’nun yürüdüğü sırayla diz.','Piko’nun izlediği yolu kartlarla anlat. İlk adım hangisi?','Noktalı yolu parmağınla izle, sonra yön kartlarını sırala.','Piko evine hangi adımlarla gider? Kartları sıraya diz.','Evin yolunu tarif et: önce hangi yöne, kaç adım?','Haritaya bak ve Piko’nun adımlarını baştan sona sırala.'],25),steps.join('|'),steps.join(' → '));
 }
 if(k==='graph'){const x=int(2,difficulty===1?5:6),y0=int(1,5),y=y0>=x?y0+1:y0,low=(w:string)=>w.toLocaleLowerCase('tr-TR'),task=(t:'tool'|'most'|'diff'|'total'|'read',[question,[ea,la],[eb,lb]]:typeof surveys[number])=>()=>{q.key=[`${t}:${la}`];
  if(t==='tool'){q.items=[`${ea}|${la}`,`${eb}|${lb}`];q.value=x;q.start=y;return set(`“${question}” anketinde ${x} kişi ${low(la)}, ${y} kişi ${low(lb)} seçti. Grafikte ${low(la)} sayısını ayarla.`,x,`Her simge bir kişiyi gösterir: ${x} ${low(la)}, ${y} ${low(lb)}.`);}
  q.visual=`chart:${ea}:${la}:${x}:${eb}:${lb}:${y}`;
  if(t==='most')return choices(`Grafiğe göre hangisi daha çok seçilmiş: ${low(la)} ya da ${low(lb)}?`,x>y?la:lb,`Grafikte ${la} ${x}, ${lb} ${y} simge. Uzun olan sıra ${x>y?la:lb}.`,[la,lb]);
  if(t==='diff')return choices(`Grafikte ${low(la)} ile ${low(lb)} arasında kaç kişi fark var?`,Math.abs(x-y),`${Math.max(x,y)} − ${Math.min(x,y)} = ${Math.abs(x-y)}. Uzun sıradaki fazla simgeleri sayarız.`);
  if(t==='total')return choices(`“${question}” anketine toplam kaç kişi katıldı?`,x+y,`${x} + ${y} = ${x+y}. Her simge bir kişidir.`);
  return choices(`Grafiğe bak: kaç kişi ${low(lb)} seçmiş?`,y,`${lb} sırasında ${y} simge var.`)},tools=surveys.map(s=>task('tool',s));
  return deal(tools,[...tools,...(['most','diff','total','read'] as const).flatMap(t=>surveys.map(s=>task(t,s)))]);
 }
 }
 if(l.subject==='tr'){
 const n=Number(l.generator?.split('-')[1]??0),s=stories[n],workshop=storyWorkshops[n],two=(pool:readonly string[])=>shuffle(pool,random).slice(0,2);
 if(l.generator?.startsWith('story')){
  const data:[string,string,string[],string][]=[[workshop.detail[0],workshop.detail[1],workshop.detail.slice(2),`Metindeki bilgi: ${workshop.detail[1]}. Hikâyeyi tekrar açıp bu bilgiyi bulabilirsin.`],[workshop.place,s.where,two(decoys.place),'Yer bildiren sözcükleri izleyince cevabı bulabiliriz.'],['Bu hikâyeye en uygun başlık hangisi?',s.title,two(decoys.title),'Başlık, hikâyenin ana konusunu anlatır.'],[`“${s.word}” sözcüğünün anlamı hangisi?`,s.meaning,two(decoys.meaning),`“${s.word}”: ${s.meaning.toLocaleLowerCase('tr-TR')}. Cümledeki anlamına baktık.`],['Olayları sıraya koyalım.',s.events.join('|'),[],s.events.join(' → ')],[workshop.cause,s.why,two(decoys.cause),'Bir davranışın nedenini bulmak için ondan önce ve sonra olanları düşünürüz.'],['Bu hikâyeden hangi sonucu çıkarabiliriz?',workshop.inference,workshop.alternatives,workshop.inference],['Hangisinin olduğunu metinden kesin olarak biliyoruz?',s.events[1],two(decoys.fact),`Metinde açıkça anlatılan olay: ${s.events[1]}`]];const t=draw([...data.keys()]),d=data[t];q.skill=t===4?'T.O.2.3':'T.O.2.2';q.hints=['Hikâyeyi hatırla bölümünü aç. Soruyla ilgili cümleyi bul.','Cevap metindeki olaylarla uyumlu olmalı. Metinde yazmayan bir bilgiyi eklemeyelim.'];
  if(t===4){q.type='ordering';q.items=shuffle(s.events,random);return set(d[0],d[1],d[3]);}
  return choices(d[0],d[1],d[3],d[2]);
 }
 if(l.generator?.startsWith('words')){
  /** Rol dağılımı turun tohumuna bağlıdır: 0. soru öğrenme örneği, cümleler bir turda bir kez kullanılır. */
  const order=rng(seed*31+n),swap=order()<.5,roles=shuffle([0,1,2],order),round=Math.floor(index/3);
  if(index%3===0){const id=round===0?0:(round===1)===swap?2:1,words=[s.sentence,...workshop.sentences][id];if([[0,1,3],[0,1,5],[3,4,6,7]][id].includes(n)){const alternative=[...words];[alternative[1],alternative[2]]=[alternative[2],alternative[1]];q.acceptedAnswers=[alternative.join('|')]}q.items=shuffle(words,random);q.type='ordering';q.skill='T.Y.2.2';q.hints=['Büyük harfle başlayan kartı bul. Cümlede kim, ne yapıyor? ',`İlk kelime “${words[0]}”. Sonunda nokta olan kartı sona getir.`];return set(['Kelimeleri taşıyarak cümleyi kur.','Kartları sıraya dizerek anlamlı bir cümle oluştur.','Kelimeleri doğru sıraya koy ve cümleyi oku.'][round],words.join('|'),words.join(' '));}
  if(index%3===1){q.skill='T.Y.2.3';q.type='punctuation';const questions=['Şemsiyeyi birlikte kullanalım mı','Bayramda hangi şiiri okuyacaksın','Tohum ne zaman filizlenir','Kitabı kütüphaneye götürdün mü','Sen hangi etkinliği seviyorsun','Araba neden hareket etmedi','Mendilde hangi desenler var','Oyuna ben de katılabilir miyim'];const variant=round%3;const sentence=variant===0?questions[n]:variant===1?workshop.more[roles[0]].join(' ').replace(/[.!?]$/,''):workshop.exclaim;q.items=[sentence];q.hints=['Cümle bir soru mu soruyor, haber mi veriyor, yoksa bir duyguyu mu anlatıyor?','Soru soruyorsa ?, haber veriyorsa ., güçlü bir duygu anlatıyorsa ! kullanırız.'];return set(['Cümlenin sonuna uygun işareti yerleştir.','Bu cümle hangi işaretle bitmeli? İşareti yerleştir.','Cümleyi oku ve sonuna uygun noktalama işaretini koy.'][variant],['?','.','!'][variant],['Bir soru sorulduğu için soru işareti kullanırız.','Tamamlanmış bir haber cümlesinin sonunda nokta kullanırız.','Güçlü bir duygu anlattığı için ünlem işareti kullanırız.'][variant]);}
  const words=workshop.more[roles[1+round%2]];q.skill='T.Y.2.2';return choices(`${words.slice(0,-1).join(' ')} ____`,words.at(-1)!,`Cümleyi tamamla: ${words.join(' ')}`,two(decoys.ending));
 }
 }
 if(l.vocabulary){const v=draw(l.vocabulary);q.type=index%2?'choice':'matching';q.visual=v.picture;q.items=l.vocabulary.slice(0,4).map(v=>`${v.word}|${v.meaning}`);q.skill=l.outcomes[index%2];return set(`“${v.meaning}” için doğru İngilizce kelimeyi seç.`,v.word,`${v.word}: ${v.meaning}.`,shuffle(l.vocabulary.filter(x=>x.word!==v.word).map(x=>x.word),random).slice(0,difficulty===1?2:3));}
 if(l.kind==='pitch'){const [low,high]=draw(pitchPairs,21),[ask,askHigh]=draw(pitchAsks,20),highFirst=random()<.5;q.value=highFirst?high:low;q.start=highFirst?low:high;q.key=[`${low}-${high}`,ask];set(ask,askHigh===highFirst?'1. ses':'2. ses',askHigh?'İnce ses, ses merdiveninde daha yukarıdaki ses gibidir. Sesin gücü ile inceliği farklı özelliklerdir.':'Kalın ses, ses merdiveninde daha aşağıdaki ses gibidir. Sesin gücü ile kalınlığı farklı özelliklerdir.');q.options=['1. ses','2. ses'];return q;}
 if(l.generator==='tempo'){const [fast,slow]=draw(tempoPairs,21),[ask,askFast]=draw(tempoAsks,20),fastFirst=random()<.5;q.type='tempo';q.value=fastFirst?fast:slow;q.start=fastFirst?slow:fast;q.key=[`${fast}-${slow}`,ask];set(ask,`${askFast===fastFirst?1:2}. örnek`,askFast?'Vuruşların arası kısaldıkça tempo hızlanır. Hızlı örnekte vuruşlar sık sık gelir.':'Vuruşların arası uzadıkça tempo yavaşlar. Yavaş örnekte vuruşlar arasında daha uzun beklenir.');q.options=['1. örnek','2. örnek'];q.hints=['İki örnekte de dört vuruş var. Vuruşların ne kadar sık geldiğine dikkat et.','Işıklar daha sık yanıyorsa tempo daha hızlıdır.'];return q;}
 if(l.kind==='rhythm'){q.items=draw(rhythms);return set(phrase(['Önce ritmi dinle. Aynı vuruş ve sus dizisini oluştur.','Ritmi dinle, sonra kartlarla aynısını kur.','Piko bir ritim çaldı. Sen de aynısını oluştur.','Dinle ve tekrarla: vuruşları ve susları sırayla seç.','Işıkları izle ya da ritmi dinle. Aynı diziyi yap.','Kulağını aç! Bu ritmi vuruş ve sus kartlarıyla yeniden kur.','Ritmi bir kez dinle, sonra parmaklarınla aynısını çal.','Vuruşları ve susları say. Aynı ritmi oluştur.'],26),q.items.join('|'),'Alkış bir vuruştur. Çizgi bir vuruş boyunca sessizliktir.');}
 if(l.kind==='drawing'||l.kind==='speaking'||l.kind==='physicalTask'){
  q.selfReport=true;q.type=l.kind;q.skill=l.outcomes[index%l.outcomes.length];const song=l.subject==='music',task=[l.task,...l.tasks??[]][index]??l.task;
  if(index>=3){q.type='speaking';return set(draw(reflections[song?'song':l.kind]),'done','Kendi çalışman hakkında düşünmen öğrenmene yardımcı olur. Bu gözlemini bir yetişkinle de paylaşabilirsin.');}
  if(l.kind==='drawing')return set(task??'Şekiller ekleyerek kendi modelini oluştur. Sonra modelini anlat.','done','Her resim farklı olabilir. Renklerini ve şekillerini neden seçtiğini bir yetişkine anlat.');
  if(l.kind==='physicalTask')return set(task??'Kendi hızında hareket et.','done','Kendini dinledin ve hareket etmeye zaman ayırdın. İstersen şimdi dinlen.');
  if(song){q.type='speaking';return set(task??'Şarkını kendi ezginle söyle.','done','Şarkı söylemek ve ritme eşlik etmek bir keşiftir. İstersen bir yetişkinle birlikte söyle.');}
  const s=stories[Number(l.generator?.split('-')[1]??0)];q.type=index===1?'writing':'speaking';return set(index===1?'Hikâyeye bir iki cümlelik yeni bir son yaz. Kişisel bilgilerini yazma.':index===2?`“${s.title}” hikâyesinde en sevdiğin bölümü seç. Neden sevdiğini anlat.`:l.task??'Hikâyeyi kendi sözlerinle anlat.','done','Bu çalışma bir öz değerlendirmedir. Anlatımını bir yetişkinle birlikte değerlendirebilirsin.');
 }
 throw new Error(`Soru üreticisi eksik: ${l.id}`);
}
