import type {Lesson,Question} from './types';
import {stories} from '@/content/tr/lessons';
import {storyWorkshops} from '@/content/tr/workshops';
export function rng(seed:number){return ()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296}}
export function shuffle<T>(items:T[],random= Math.random){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
export function makeQuestion(l:Lesson,index:number,difficulty:1|2|3=1,seed=1):Question{
 const random=rng(seed+index*311),int=(a:number,b:number)=>a+Math.floor(random()*(b-a+1));
 const q:Question={id:`${l.id}-${seed}-${index}`,type:l.kind,instruction:'',answer:'',hints:[l.learn[0],l.learn[l.learn.length-1]],explanation:'',skill:l.outcomes[0],difficulty};
 const set=(instruction:string,answer:string|number,explanation:string,options?:string[])=>{q.instruction=instruction;q.answer=String(answer);q.explanation=explanation;if(options)q.options=shuffle([...new Set([q.answer,...options])],random);return q};
 const choices=(instruction:string,answer:string|number,explanation:string,options?:string[])=>{q.type='choice';return set(instruction,answer,explanation,options??[String(Number(answer)+1),String(Math.max(0,Number(answer)-1))])};
 if(l.questions){const src=l.questions[index%l.questions.length];return {...src,id:q.id,options:src.options?shuffle(src.options,random):undefined};}
 if(l.subject==='math'){
 const a=int(1,difficulty===1?3:difficulty===2?6:9)*10+int(0,9),b=int(1,9),k=l.generator;
 if(k==='blocks'||k==='count'||k==='add'){
  const left=k==='add'?Math.min(a,79):a,n=k==='add'?left+b+10:a;q.value=n;
  const desc=k==='add'?`${left} + ${b+10}`:`${n}`;
  if(index%3===2){return choices(`${desc} ${k==='add'?'işleminin sonucunda':'sayısında'} kaç onluk var?`,Math.floor(n/10),`${n} içinde ${Math.floor(n/10)} onluk, ${n%10} birlik var.`,[String(Math.floor(n/10)+1),String(Math.max(0,Math.floor(n/10)-1))]);}
  q.type='baseTenBlocks';return set(`${k==='add'?`${desc} işlemini yap.`:`${n} sayısını kur.`} Blokları çalışma alanına taşı.`,n,`${Math.floor(n/10)} onluk ve ${n%10} birlik, ${n} eder.`);
 }
 if(['order','skip','subtract','mental'].includes(k??'')){
  const start=k==='order'?int(0,8)*10:k==='skip'?0:k==='subtract'?int(6,15):int(5,9);const step=k==='skip'?[2,3,4,5][index%4]:k==='subtract'?-1:1;
  const count=k==='order'?int(1,9):int(2,5),answer=start+step*count;q.start=start;q.step=step;q.value=count;
  return set(k==='order'?`${start} ile ${start+10} arasında ${answer} sayısına git.`:`${start}’dan başla. ${Math.abs(step)}’er ${count} kez ${step<0?'geri':'ileri'} zıpla.`,answer,`${start} ${step<0?'−':'+'} ${Math.abs(step)*count} = ${answer}. Her zıplayış ${Math.abs(step)} adım.`);
 }
 if(k==='pattern'){const step=[2,3,4,5][index%4],n=step*int(1,3);const arr=[n,n+step,n+step*2];q.type='ordering';q.items=shuffle([String(n+step*3),String(n+step*4),String(n+step*5)],random);return set(`${arr.join(', ')}… Sonraki üç sayıyı sırala.`,[n+step*3,n+step*4,n+step*5].join('|'),`Her seferinde ${step} ekleriz.`);}
 if(k==='estimate'){const n=int(2,5)*5;q.visual='🍒'.repeat(n);return choices('Önce tahmin et, sonra say. Bu gruba en yakın sayı hangisi?',n,`Beşerli grupladığında ${n/5} grup var. Toplam ${n} kiraz.`,[String(n+10),String(n-5)]);}
 if(k==='fractions'){q.value=[1,2,4][index%3];return set(`${q.value===1?'Bir bütün':q.value===2?'Bir yarım':'Bir çeyrek'} oluşturmak için dört eş parçadan kaçını seçmelisin?`,4/q.value,`Bir bütün dört çeyrektir. Bir yarım iki çeyrektir.`);}
 if(k==='money'){q.value=[50,75,100,125,150,200,250,300][index%8];return set(`${q.value} kuruşu kumbaraya koy.`,q.value,'25 kuruşları veya 50 kuruşları birleştir. 100 kuruş = 1 TL.');}
 if(k==='clock'){const h=int(1,11),m=[0,30,15,45][index%4];q.value=h*60+m;return set(`Saati ${h}.${String(m).padStart(2,'0')} yap.`,q.value,`Akrep ${h}${m?' ile '+(h+1)+' arasında':''}, yelkovan ${m===0?'12':m/5} üzerinde olmalı.`);}
 if(k==='calendar'){q.type='ordering';const days=['Pazartesi','Salı','Çarşamba','Perşembe','Cuma','Cumartesi','Pazar'];const start=index%5,arr=days.slice(start,start+3);q.items=shuffle(arr,random);return set('Bu günleri oluş sırasına koy.',arr.join('|'),arr.join(' → '));}
 if(k==='measure'||k==='length'){const n=int(3,9);q.value=n;return set('Önce uzunluğu tahmin et. Sonra cetvelle kontrol et: kalem kaç santimetre?',n,`Kalem sıfırdan başlıyor, ${n} çizgisinde bitiyor. Uzunluğu ${n} cm.`);}
 if(k==='inverse'){const x=int(5,20),y=int(1,9);return choices(`${x} + ${y} = ${x+y}. Peki ${x+y} − ${y} kaç eder?`,x,`Topladığımız ${y}’yi çıkarınca başlangıçtaki ${x} kalır.`);}
 if(k==='multiply'||k==='divide'||k==='multimental'){const groups=int(2,difficulty===3?5:3),each=int(2,5);q.visual=Array.from({length:groups},()=> '🍓'.repeat(each)).join('   /   ');return choices(k==='divide'?`${groups*each} çilek ${groups} tabağa eşit paylaşıldı. Her tabakta kaç çilek var?`:`${groups} grubun her birinde ${each} çilek var. Toplam kaç çilek?`,k==='divide'?each:groups*each,`${Array(groups).fill(each).join(' + ')} = ${groups*each}. ${groups*each} ÷ ${groups} = ${each}.`);}
 if(k==='balance'){const x=int(2,9),y=int(1,9);return choices(`${x} + ${y} = ${x-1} + ? Dengeyi tamamla.`,y+1,`Solda ${x+y} var. Sağda da ${x+y} olması için ${x-1}’e ${y+1} eklenir.`);}
 if(k==='solids'){const data=[['sphere','Küre','Top gibi yuvarlaktır; düz yüzü ve köşesi yoktur.'],['cube','Küp','Altı kare yüzü vardır. Yüzler aynı büyüklüktedir.'],['cylinder','Silindir','Altında ve üstünde daire biçimli iki düz yüz, yanında eğri bir yüzey vardır.'],['prism','Dikdörtgenler prizması','Bir kitap kutusu gibi görünür. Yüzleri dikdörtgen biçimindedir.']][index%4];q.type='geometry';q.items=[data[0]];return set('Çizimi incele. Bu geometrik cismin adı ne?',data[1],data[2],['Küre','Küp','Silindir','Dikdörtgenler prizması']);}
 if(k==='rotate'){const shapes=[['square','karenin',4],['triangle','üçgenin',3],['rectangle','dikdörtgenin',4],['circle','dairenin',0]] as const;const [shape,name,corners]=shapes[index%4];q.type='geometry';q.items=[shape];q.hints=['Şekli istediğin kadar döndürebilirsin. Kenarların birleştiği yerlere bak.','Her köşeye bir kez dokun. Dairenin köşesi yoktur.'];return set(`Şekli döndür ve incele. Bu ${name} kaç köşesi var?`,corners,`Yönü veya büyüklüğü değişince şeklin köşe sayısı değişmez. Bu şeklin ${corners} köşesi var.`,['0','3','4']);}
 if(k==='build'||k==='shapes'){q.type='geometry';q.visual=k==='build'?'build':'compose';q.value=index%2;return set(k==='build'?'Küpleri yerlerine taşı ve küçük bir yapı kur.':index%2?'Parçaları birleştirerek bir araç oluştur.':'Bir kare, bir üçgen ve bir daireyle güneşli bir ev kur.','done',k==='build'?'Küpleri yan yana ve üst üste getirerek bir yapı oluşturdun.':'Şekiller bir araya gelince yeni bir model oluşur. Her parçanın biçimi aynı kalır.');}
 if(k==='symmetry'){q.type='geometry';q.visual='symmetry';const patterns=[[1,2,4,8,10],[0,3,4,7,9],[2,4,5,8,11],[1,3,4,6,10]];const cells=patterns[index%patterns.length];q.items=cells.map(String);const mirrored=cells.map(i=>Math.floor(i/3)*3+2-i%3).sort((a,b)=>a-b);q.hints=['Aynanın yanındaki kareye bak. Karşılığı da aynanın hemen yanında olmalı.','Her satırı ayrı düşün. Çizgiye uzak kare, sağda da çizgiye uzak kalır.'];return set('Soldaki deseni aynadaki gibi sağ tarafa tamamla.',mirrored.join('|'),'İki taraftaki boyalı karelerin ayna çizgisine uzaklığı aynıdır.');}
 if(k==='liquid'){const n=int(2,5);q.visual='🥛'.repeat(n);return choices(`Bir sürahi, bu eş bardakları dolduruyor. Önce tahmin et; sürahi kaç bardak alır?`,n,`Aynı büyüklükte ${n} bardak doldu. Bu sürahi ${n} bardak su alır.`);}
 if(k==='directions'){const dirs=index%2?['Yukarı','Sağa','Sağa']:['Sağa','Sağa','Yukarı'];q.visual=index%2?'🏡 ⬅️ ⬅️\n⬆️\n🌱':'⬜ ⬜ 🏡\n🌱 ➡️ ⬆️';q.items=shuffle(dirs.map((x,i)=>`${i+1}. ${x}`),random);return set('Numaralı yol tarifini sırayla yerleştir.',dirs.map((x,i)=>`${i+1}. ${x}`).join('|'),dirs.join(' → '));}
 if(k==='graph'){const apples=int(2,5),pears=int(1,4);q.value=apples;q.start=pears;return set(`Ankette ${apples} kişi elma, ${pears} kişi armut seçti. Grafikte elma sayısını ayarla.`,apples,`Her simge bir kişiyi gösterir: ${apples} elma, ${pears} armut.`);}
 }
 if(l.subject==='tr'){
 const n=Number(l.generator?.split('-')[1]??0),s=stories[n],workshop=storyWorkshops[n];
 if(l.generator?.startsWith('story')){
  const data:[string,string,string[],string][]=[[workshop.detail[0],workshop.detail[1],workshop.detail.slice(2),`Metindeki bilgi: ${workshop.detail[1]}. Hikâyeyi tekrar açıp bu bilgiyi bulabilirsin.`],[workshop.place,s.where,['Spor salonunda','Marketin önünde'],'Yer bildiren sözcükleri izleyince cevabı bulabiliriz.'],['Bu hikâyeye en uygun başlık hangisi?',s.title,['Kaybolan Anahtar','Kış Tatili'],'Başlık, hikâyenin ana konusunu anlatır.'],[`“${s.word}” sözcüğünün anlamı hangisi?`,s.meaning,['Bir şeyi saklayıp unutmak','Bir yerden başka yere gitmek'],`“${s.word}”: ${s.meaning.toLocaleLowerCase('tr-TR')}. Cümledeki anlamına baktık.`],['Olayları sıraya koyalım.',s.events.join('|'),[],s.events.join(' → ')],[workshop.cause,s.why,['Okula geç kalmamak için','Bir yarışmayı kazanmak için'],'Bir davranışın nedenini bulmak için ondan önce ve sonra olanları düşünürüz.'],['Bu hikâyeden hangi sonucu çıkarabiliriz?',workshop.inference,workshop.alternatives,workshop.inference],['Hangisinin olduğunu metinden kesin olarak biliyoruz?',s.events[1],['Çocuklar dondurma aldı.','O gün kar yağıyordu.'],`Metinde açıkça anlatılan olay: ${s.events[1]}`]];const d=data[index%data.length];q.skill=index%8===4?'T.O.2.3':'T.O.2.2';q.hints=['Hikâyeyi hatırla bölümünü aç. Soruyla ilgili cümleyi bul.','Cevap metindeki olaylarla uyumlu olmalı. Metinde yazmayan bir bilgiyi eklemeyelim.'];
  if(index%8===4){q.type='ordering';q.items=shuffle(s.events,random);return set(d[0],d[1],d[3]);}
  return choices(d[0],d[1],d[3],d[2]);
 }
 if(l.generator?.startsWith('words')){
  if(index%3===0){const words=[s.sentence,...workshop.sentences][Math.floor(index/3)%3];if([[0,1,3],[0,1,3,4,5],[1,3,4,6,7]][Math.floor(index/3)%3].includes(n)){const alternative=[...words];[alternative[1],alternative[2]]=[alternative[2],alternative[1]];q.acceptedAnswers=[alternative.join('|')]}q.items=shuffle(words,random);q.type='ordering';q.skill='T.Y.2.2';q.hints=['Büyük harfle başlayan kartı bul. Cümlede kim, ne yapıyor? ',`İlk kelime “${words[0]}”. Sonunda nokta olan kartı sona getir.`];return set('Kelimeleri taşıyarak cümleyi kur.',words.join('|'),words.join(' '));}
  if(index%3===1){q.skill='T.Y.2.3';q.type='punctuation';const questions=['Şemsiyeyi birlikte kullanalım mı','Bayramda hangi şiiri okuyacaksın','Tohum ne zaman filizlenir','Kitabı kütüphaneye götürdün mü','Sen hangi etkinliği seviyorsun','Araba neden hareket etmedi','Mendilde hangi desenler var','Oyuna ben de katılabilir miyim'];const variant=Math.floor(index/3)%3;const sentence=variant===0?questions[n]:variant===1?s.sentence.join(' ').replace(/[.!?]$/,''):'Yaşasın, başardık';q.items=[sentence];q.hints=['Cümle bir soru mu soruyor, haber mi veriyor, yoksa bir duyguyu mu anlatıyor?','Soru soruyorsa ?, haber veriyorsa ., güçlü bir sevinç anlatıyorsa ! kullanırız.'];return set('Cümlenin sonuna uygun işareti yerleştir.',['?','.','!'][variant],['Bir soru sorulduğu için soru işareti kullanırız.','Tamamlanmış bir haber cümlesinin sonunda nokta kullanırız.','Güçlü bir sevinç anlattığı için ünlem işareti kullanırız.'][variant]);}
  q.skill='T.Y.2.2';return choices(`${s.sentence.slice(0,-1).join(' ')} ____`,s.sentence.at(-1)!,['Cümleyi tamamla:',s.sentence.join(' ')].join(' '),['uçurtma.','masada.']);
 }
 }
 if(l.vocabulary){const v=l.vocabulary[index%l.vocabulary.length];q.type=index%2?'choice':'matching';q.visual=v.picture;q.items=l.vocabulary.slice(0,4).map(v=>`${v.word}|${v.meaning}`);q.skill=l.outcomes[index%2];return set(`“${v.meaning}” için doğru İngilizce kelimeyi seç.`,v.word,`${v.word}: ${v.meaning}.`,l.vocabulary.filter(x=>x.word!==v.word).map(x=>x.word).slice(0,difficulty===1?2:3));}
 if(l.kind==='pitch'){q.value=index%2?660:220;q.start=index%2?220:660;return set('İki sesi dinle. Hangisi daha ince?',index%2?'1. ses':'2. ses','İnce ses, ses merdiveninde daha yukarıdaki ses gibidir. Sesin gücü ile inceliği farklı özelliklerdir.',['1. ses','2. ses']);}
 if(l.kind==='rhythm'){q.items=index%3===0?['👏','👏','—','👏']:index%3===1?['👏','—','👏','—']:['👏','—','👏','👏'];return set('Önce ritmi dinle. Aynı vuruş ve sus dizisini oluştur.',q.items.join('|'),'Alkış bir vuruştur. Çizgi bir vuruş boyunca sessizliktir.');}
 if(l.kind==='drawing'||l.kind==='speaking'||l.kind==='physicalTask'){
  q.selfReport=true;q.type=l.kind;q.skill=l.outcomes[index%l.outcomes.length];
  if(index>=3){q.type='speaking';const prompts=l.kind==='drawing'?['Resminde hangi şekilleri kullandığını anlat.','Seçtiğin iki rengin adını söyle.','Resminde en sevdiğin yeri göster ve anlat.','Bir dahaki denemede neyi farklı yapmak istersin?','Resmini bir yetişkine anlat. Birlikte resmin hakkında konuşun.']:l.kind==='physicalTask'?['Hareket ettiğin alan güvenli miydi? Nasıl kontrol ettin?','Hareketten sonra nefesinde bir değişiklik fark ettin mi?','En rahat yaptığın hareket hangisiydi?','Dinlenmeye ihtiyaç duyduğunda ne yaptın?','Bir sonraki hareket molanda ne yapmak istersin?']:['Anlatmaya başlamadan önce ne düşündüğünü söyle.','Sözcüklerini anlaşılır söyleyebildin mi? Kendini dinle.','Anlatımında önce ve sonra olanları sırayla söyle.','Bir dahaki denemende neyi geliştirmek istersin?','Bir yetişkinle paylaş: Çalışmanın en sevdiğin kısmı neydi?'];return set(prompts[index-3],'done','Kendi çalışman hakkında düşünmen öğrenmene yardımcı olur. Bu gözlemini bir yetişkinle de paylaşabilirsin.');}
  if(l.kind==='drawing')return set(l.task??'Şekiller ekleyerek kendi modelini oluştur. Sonra modelini anlat.','done','Her resim farklı olabilir. Renklerini ve şekillerini neden seçtiğini bir yetişkine anlat.');
  if(l.kind==='physicalTask')return set(l.task??'Kendi hızında hareket et.','done','Kendini dinledin ve hareket etmeye zaman ayırdın. İstersen şimdi dinlen.');
  q.type=index%2?'writing':'speaking';return set(index%2?'Hikâyeye bir iki cümlelik yeni bir son yaz. Kişisel bilgilerini yazma.':l.task??'Hikâyeyi kendi sözlerinle anlat.','done','Bu çalışma bir öz değerlendirmedir. Anlatımını bir yetişkinle birlikte değerlendirebilirsin.');
 }
 throw new Error(`Soru üreticisi eksik: ${l.id}`);
}
