export type SubjectId = 'tr'|'math'|'life'|'english'|'art'|'music'|'move';
export type ActivityType = 'choice'|'baseTenBlocks'|'numberLine'|'ordering'|'punctuation'|'clock'|'money'|'fractions'|'geometry'|'graph'|'drawing'|'rhythm'|'pitch'|'tempo'|'physicalTask'|'traffic'|'matching'|'writing'|'speaking'|'measure';
export interface Outcome {grade:number;subject:SubjectId;theme:string;learningOutcome:string;learningOutcomeCode:string;skills:string[];source:string;sourceUrl:string;academicYear:string;lastVerified:string;assessment:'automatic'|'observation'}
export interface Question {id:string;type:ActivityType;instruction:string;answer:string;acceptedAnswers?:string[];options?:string[];items?:string[];visual?:string;value?:number;start?:number;step?:number;hints:string[];explanation:string;skill:string;difficulty:1|2|3;selfReport?:boolean;/** Aynı turda tekrar etmemesi gereken özler (ör. sayı ve resim); yoksa yönerge ve görselden türetilir. */key?:string[]}
export interface Lesson {id:string;subject:SubjectId;theme:string;title:string;subtitle:string;icon:string;minutes:number;outcomes:string[];learn:string[];kind:ActivityType;generator?:string;story?:string;words?:string[];questions?:Question[];task?:string;/** task ile birlikte sırasıyla Birlikte yapalım, Sen dene ve Mini oyun görevleri. */tasks?:string[];vocabulary?:{word:string;picture:string;meaning:string}[]}
export interface SkillState {score:number;attempts:number;correct:number;streak:number;due:string;lastSeen:string}
export interface Attempt {id:string;lessonId:string;skill:string;correct:boolean;assisted:boolean;selfReport:boolean;at:string}
export interface GameRecord {plays:number;best:number;last:string}
export interface Progress {version:1;skills:Record<string,SkillState>;completed:Record<string,{at:string;correct:number;total:number}>;attempts:Attempt[];stars:number;lastLesson?:string;sound:boolean;games?:Record<string,GameRecord>}
